// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: test.proto

package test

import (
	_ "github.com/yaroher/protoc-gen-go-plain/goplain"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestEnum int32

const (
	TestEnum_TEST_ENUM_UNSPECIFIED TestEnum = 0
	TestEnum_TEST_ENUM_ONE         TestEnum = 1
	TestEnum_TEST_ENUM_TWO         TestEnum = 2
)

// Enum value maps for TestEnum.
var (
	TestEnum_name = map[int32]string{
		0: "TEST_ENUM_UNSPECIFIED",
		1: "TEST_ENUM_ONE",
		2: "TEST_ENUM_TWO",
	}
	TestEnum_value = map[string]int32{
		"TEST_ENUM_UNSPECIFIED": 0,
		"TEST_ENUM_ONE":         1,
		"TEST_ENUM_TWO":         2,
	}
)

func (x TestEnum) Enum() *TestEnum {
	p := new(TestEnum)
	*p = x
	return p
}

func (x TestEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TestEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_test_proto_enumTypes[0].Descriptor()
}

func (TestEnum) Type() protoreflect.EnumType {
	return &file_test_proto_enumTypes[0]
}

func (x TestEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TestEnum.Descriptor instead.
func (TestEnum) EnumDescriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

type OidcIdAlias struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OidcIdAlias) Reset() {
	*x = OidcIdAlias{}
	mi := &file_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OidcIdAlias) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OidcIdAlias) ProtoMessage() {}

func (x *OidcIdAlias) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OidcIdAlias.ProtoReflect.Descriptor instead.
func (*OidcIdAlias) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

func (x *OidcIdAlias) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type IdAlias struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdAlias) Reset() {
	*x = IdAlias{}
	mi := &file_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdAlias) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdAlias) ProtoMessage() {}

func (x *IdAlias) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdAlias.ProtoReflect.Descriptor instead.
func (*IdAlias) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{1}
}

func (x *IdAlias) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type EmbedWithAlias struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmbedOidcId   *OidcIdAlias           `protobuf:"bytes,1,opt,name=embed_oidc_id,json=embedOidcId,proto3" json:"embed_oidc_id,omitempty"`
	EmbedId       *IdAlias               `protobuf:"bytes,2,opt,name=embed_id,json=embedId,proto3" json:"embed_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedWithAlias) Reset() {
	*x = EmbedWithAlias{}
	mi := &file_test_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedWithAlias) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedWithAlias) ProtoMessage() {}

func (x *EmbedWithAlias) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedWithAlias.ProtoReflect.Descriptor instead.
func (*EmbedWithAlias) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{2}
}

func (x *EmbedWithAlias) GetEmbedOidcId() *OidcIdAlias {
	if x != nil {
		return x.EmbedOidcId
	}
	return nil
}

func (x *EmbedWithAlias) GetEmbedId() *IdAlias {
	if x != nil {
		return x.EmbedId
	}
	return nil
}

type TestMessage struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	OidcId *OidcIdAlias           `protobuf:"bytes,100,opt,name=oidc_id,json=oidcId,proto3" json:"oidc_id,omitempty"`
	Id     *IdAlias               `protobuf:"bytes,101,opt,name=id,proto3" json:"id,omitempty"`
	Embed  *EmbedWithAlias        `protobuf:"bytes,102,opt,name=embed,proto3" json:"embed,omitempty"`
	// Scalar numeric types.
	FDouble   float64 `protobuf:"fixed64,1,opt,name=f_double,json=fDouble,proto3" json:"f_double,omitempty"`
	FFloat    float32 `protobuf:"fixed32,2,opt,name=f_float,json=fFloat,proto3" json:"f_float,omitempty"`
	FInt32    int32   `protobuf:"varint,3,opt,name=f_int32,json=fInt32,proto3" json:"f_int32,omitempty"`
	FInt64    int64   `protobuf:"varint,4,opt,name=f_int64,json=fInt64,proto3" json:"f_int64,omitempty"`
	FUint32   uint32  `protobuf:"varint,5,opt,name=f_uint32,json=fUint32,proto3" json:"f_uint32,omitempty"`
	FUint64   uint64  `protobuf:"varint,6,opt,name=f_uint64,json=fUint64,proto3" json:"f_uint64,omitempty"`
	FSint32   int32   `protobuf:"zigzag32,7,opt,name=f_sint32,json=fSint32,proto3" json:"f_sint32,omitempty"`
	FSint64   int64   `protobuf:"zigzag64,8,opt,name=f_sint64,json=fSint64,proto3" json:"f_sint64,omitempty"`
	FFixed32  uint32  `protobuf:"fixed32,9,opt,name=f_fixed32,json=fFixed32,proto3" json:"f_fixed32,omitempty"`
	FFixed64  uint64  `protobuf:"fixed64,10,opt,name=f_fixed64,json=fFixed64,proto3" json:"f_fixed64,omitempty"`
	FSfixed32 int32   `protobuf:"fixed32,11,opt,name=f_sfixed32,json=fSfixed32,proto3" json:"f_sfixed32,omitempty"`
	FSfixed64 int64   `protobuf:"fixed64,12,opt,name=f_sfixed64,json=fSfixed64,proto3" json:"f_sfixed64,omitempty"`
	// Scalar non-numeric types.
	FBool   bool   `protobuf:"varint,13,opt,name=f_bool,json=fBool,proto3" json:"f_bool,omitempty"`
	FString string `protobuf:"bytes,14,opt,name=f_string,json=fString,proto3" json:"f_string,omitempty"`
	FUuid   string `protobuf:"bytes,62,opt,name=f_uuid,json=fUuid,proto3" json:"f_uuid,omitempty"`
	FBytes  []byte `protobuf:"bytes,15,opt,name=f_bytes,json=fBytes,proto3" json:"f_bytes,omitempty"`
	// Optional fields (proto3 optional).
	FOptInt32   *int32         `protobuf:"varint,16,opt,name=f_opt_int32,json=fOptInt32,proto3,oneof" json:"f_opt_int32,omitempty"`
	FOptString  *string        `protobuf:"bytes,17,opt,name=f_opt_string,json=fOptString,proto3,oneof" json:"f_opt_string,omitempty"`
	FOptMessage *NestedMessage `protobuf:"bytes,18,opt,name=f_opt_message,json=fOptMessage,proto3,oneof" json:"f_opt_message,omitempty"`
	FOptEnum    *TestEnum      `protobuf:"varint,190,opt,name=f_opt_enum,json=fOptEnum,proto3,enum=test.TestEnum,oneof" json:"f_opt_enum,omitempty"`
	// Repeated fields.
	FRepInt32             []int32          `protobuf:"varint,19,rep,packed,name=f_rep_int32,json=fRepInt32,proto3" json:"f_rep_int32,omitempty"`
	FRepString            []string         `protobuf:"bytes,20,rep,name=f_rep_string,json=fRepString,proto3" json:"f_rep_string,omitempty"`
	FRepMessage           []*NestedMessage `protobuf:"bytes,21,rep,name=f_rep_message,json=fRepMessage,proto3" json:"f_rep_message,omitempty"`
	FRepMessageSerialized []*NestedMessage `protobuf:"bytes,220,rep,name=f_rep_message_serialized,json=fRepMessageSerialized,proto3" json:"f_rep_message_serialized,omitempty"`
	FRepEnum              []TestEnum       `protobuf:"varint,22,rep,packed,name=f_rep_enum,json=fRepEnum,proto3,enum=test.TestEnum" json:"f_rep_enum,omitempty"`
	// Map fields (all allowed key types shown across maps).
	FMapInt32String    map[int32]string          `protobuf:"bytes,23,rep,name=f_map_int32_string,json=fMapInt32String,proto3" json:"f_map_int32_string,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	FMapInt64Int32     map[int64]int32           `protobuf:"bytes,24,rep,name=f_map_int64_int32,json=fMapInt64Int32,proto3" json:"f_map_int64_int32,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	FMapUint32Uint64   map[uint32]uint64         `protobuf:"bytes,25,rep,name=f_map_uint32_uint64,json=fMapUint32Uint64,proto3" json:"f_map_uint32_uint64,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	FMapUint64Bool     map[uint64]bool           `protobuf:"bytes,26,rep,name=f_map_uint64_bool,json=fMapUint64Bool,proto3" json:"f_map_uint64_bool,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	FMapSint32Bytes    map[int32][]byte          `protobuf:"bytes,27,rep,name=f_map_sint32_bytes,json=fMapSint32Bytes,proto3" json:"f_map_sint32_bytes,omitempty" protobuf_key:"zigzag32,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	FMapSint64Float    map[int64]float32         `protobuf:"bytes,28,rep,name=f_map_sint64_float,json=fMapSint64Float,proto3" json:"f_map_sint64_float,omitempty" protobuf_key:"zigzag64,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	FMapFixed32Double  map[uint32]float64        `protobuf:"bytes,29,rep,name=f_map_fixed32_double,json=fMapFixed32Double,proto3" json:"f_map_fixed32_double,omitempty" protobuf_key:"fixed32,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	FMapFixed64Message map[uint64]*NestedMessage `protobuf:"bytes,30,rep,name=f_map_fixed64_message,json=fMapFixed64Message,proto3" json:"f_map_fixed64_message,omitempty" protobuf_key:"fixed64,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	FMapSfixed32Enum   map[int32]TestEnum        `protobuf:"bytes,31,rep,name=f_map_sfixed32_enum,json=fMapSfixed32Enum,proto3" json:"f_map_sfixed32_enum,omitempty" protobuf_key:"fixed32,1,opt,name=key" protobuf_val:"varint,2,opt,name=value,enum=test.TestEnum"`
	FMapSfixed64String map[int64]string          `protobuf:"bytes,32,rep,name=f_map_sfixed64_string,json=fMapSfixed64String,proto3" json:"f_map_sfixed64_string,omitempty" protobuf_key:"fixed64,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	FMapBoolInt32      map[bool]int32            `protobuf:"bytes,33,rep,name=f_map_bool_int32,json=fMapBoolInt32,proto3" json:"f_map_bool_int32,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	FMapStringString   map[string]string         `protobuf:"bytes,34,rep,name=f_map_string_string,json=fMapStringString,proto3" json:"f_map_string_string,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Oneof fields.
	//
	// Types that are valid to be assigned to FOneof:
	//
	//	*TestMessage_FOneofInt32
	//	*TestMessage_FOneofString
	//	*TestMessage_FOneofBytes
	//	*TestMessage_FOneofMessage
	//	*TestMessage_FOneofEnum
	FOneof isTestMessage_FOneof `protobuf_oneof:"f_oneof"`
	// Nested message and enum fields.
	FNestedMessage           *NestedMessage `protobuf:"bytes,40,opt,name=f_nested_message,json=fNestedMessage,proto3" json:"f_nested_message,omitempty"`
	FNestedMessageEmbedded   *NestedMessage `protobuf:"bytes,42,opt,name=f_nested_message_embedded,json=fNestedMessageEmbedded,proto3" json:"f_nested_message_embedded,omitempty"`
	FNestedMessageSerialized *NestedMessage `protobuf:"bytes,43,opt,name=f_nested_message_serialized,json=fNestedMessageSerialized,proto3" json:"f_nested_message_serialized,omitempty"`
	FEnum                    TestEnum       `protobuf:"varint,41,opt,name=f_enum,json=fEnum,proto3,enum=test.TestEnum" json:"f_enum,omitempty"`
	// Well-known types (WKT).
	FAny          *anypb.Any                                    `protobuf:"bytes,45,opt,name=f_any,json=fAny,proto3" json:"f_any,omitempty"`
	FTimestamp    *timestamppb.Timestamp                        `protobuf:"bytes,46,opt,name=f_timestamp,json=fTimestamp,proto3" json:"f_timestamp,omitempty"`
	FDuration     *durationpb.Duration                          `protobuf:"bytes,47,opt,name=f_duration,json=fDuration,proto3" json:"f_duration,omitempty"`
	FStruct       *structpb.Struct                              `protobuf:"bytes,50,opt,name=f_struct,json=fStruct,proto3" json:"f_struct,omitempty"`
	FValue        *structpb.Value                               `protobuf:"bytes,51,opt,name=f_value,json=fValue,proto3" json:"f_value,omitempty"`
	FListValue    *structpb.ListValue                           `protobuf:"bytes,52,opt,name=f_list_value,json=fListValue,proto3" json:"f_list_value,omitempty"`
	FWktDouble    *wrapperspb.DoubleValue                       `protobuf:"bytes,53,opt,name=f_wkt_double,json=fWktDouble,proto3" json:"f_wkt_double,omitempty"`
	FWktFloat     *wrapperspb.FloatValue                        `protobuf:"bytes,54,opt,name=f_wkt_float,json=fWktFloat,proto3" json:"f_wkt_float,omitempty"`
	FWktInt64     *wrapperspb.Int64Value                        `protobuf:"bytes,55,opt,name=f_wkt_int64,json=fWktInt64,proto3" json:"f_wkt_int64,omitempty"`
	FWktUint64    *wrapperspb.UInt64Value                       `protobuf:"bytes,56,opt,name=f_wkt_uint64,json=fWktUint64,proto3" json:"f_wkt_uint64,omitempty"`
	FWktInt32     *wrapperspb.Int32Value                        `protobuf:"bytes,57,opt,name=f_wkt_int32,json=fWktInt32,proto3" json:"f_wkt_int32,omitempty"`
	FWktUint32    *wrapperspb.UInt32Value                       `protobuf:"bytes,58,opt,name=f_wkt_uint32,json=fWktUint32,proto3" json:"f_wkt_uint32,omitempty"`
	FWktBool      *wrapperspb.BoolValue                         `protobuf:"bytes,59,opt,name=f_wkt_bool,json=fWktBool,proto3" json:"f_wkt_bool,omitempty"`
	FWktString    *wrapperspb.StringValue                       `protobuf:"bytes,60,opt,name=f_wkt_string,json=fWktString,proto3" json:"f_wkt_string,omitempty"`
	FWktBytes     *wrapperspb.BytesValue                        `protobuf:"bytes,61,opt,name=f_wkt_bytes,json=fWktBytes,proto3" json:"f_wkt_bytes,omitempty"`
	FDoubleNested *NestedMessage_InnerMessage_InnerInnerMessage `protobuf:"bytes,64,opt,name=f_double_nested,json=fDoubleNested,proto3" json:"f_double_nested,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestMessage) Reset() {
	*x = TestMessage{}
	mi := &file_test_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestMessage) ProtoMessage() {}

func (x *TestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestMessage.ProtoReflect.Descriptor instead.
func (*TestMessage) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{3}
}

func (x *TestMessage) GetOidcId() *OidcIdAlias {
	if x != nil {
		return x.OidcId
	}
	return nil
}

func (x *TestMessage) GetId() *IdAlias {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *TestMessage) GetEmbed() *EmbedWithAlias {
	if x != nil {
		return x.Embed
	}
	return nil
}

func (x *TestMessage) GetFDouble() float64 {
	if x != nil {
		return x.FDouble
	}
	return 0
}

func (x *TestMessage) GetFFloat() float32 {
	if x != nil {
		return x.FFloat
	}
	return 0
}

func (x *TestMessage) GetFInt32() int32 {
	if x != nil {
		return x.FInt32
	}
	return 0
}

func (x *TestMessage) GetFInt64() int64 {
	if x != nil {
		return x.FInt64
	}
	return 0
}

func (x *TestMessage) GetFUint32() uint32 {
	if x != nil {
		return x.FUint32
	}
	return 0
}

func (x *TestMessage) GetFUint64() uint64 {
	if x != nil {
		return x.FUint64
	}
	return 0
}

func (x *TestMessage) GetFSint32() int32 {
	if x != nil {
		return x.FSint32
	}
	return 0
}

func (x *TestMessage) GetFSint64() int64 {
	if x != nil {
		return x.FSint64
	}
	return 0
}

func (x *TestMessage) GetFFixed32() uint32 {
	if x != nil {
		return x.FFixed32
	}
	return 0
}

func (x *TestMessage) GetFFixed64() uint64 {
	if x != nil {
		return x.FFixed64
	}
	return 0
}

func (x *TestMessage) GetFSfixed32() int32 {
	if x != nil {
		return x.FSfixed32
	}
	return 0
}

func (x *TestMessage) GetFSfixed64() int64 {
	if x != nil {
		return x.FSfixed64
	}
	return 0
}

func (x *TestMessage) GetFBool() bool {
	if x != nil {
		return x.FBool
	}
	return false
}

func (x *TestMessage) GetFString() string {
	if x != nil {
		return x.FString
	}
	return ""
}

func (x *TestMessage) GetFUuid() string {
	if x != nil {
		return x.FUuid
	}
	return ""
}

func (x *TestMessage) GetFBytes() []byte {
	if x != nil {
		return x.FBytes
	}
	return nil
}

func (x *TestMessage) GetFOptInt32() int32 {
	if x != nil && x.FOptInt32 != nil {
		return *x.FOptInt32
	}
	return 0
}

func (x *TestMessage) GetFOptString() string {
	if x != nil && x.FOptString != nil {
		return *x.FOptString
	}
	return ""
}

func (x *TestMessage) GetFOptMessage() *NestedMessage {
	if x != nil {
		return x.FOptMessage
	}
	return nil
}

func (x *TestMessage) GetFOptEnum() TestEnum {
	if x != nil && x.FOptEnum != nil {
		return *x.FOptEnum
	}
	return TestEnum_TEST_ENUM_UNSPECIFIED
}

func (x *TestMessage) GetFRepInt32() []int32 {
	if x != nil {
		return x.FRepInt32
	}
	return nil
}

func (x *TestMessage) GetFRepString() []string {
	if x != nil {
		return x.FRepString
	}
	return nil
}

func (x *TestMessage) GetFRepMessage() []*NestedMessage {
	if x != nil {
		return x.FRepMessage
	}
	return nil
}

func (x *TestMessage) GetFRepMessageSerialized() []*NestedMessage {
	if x != nil {
		return x.FRepMessageSerialized
	}
	return nil
}

func (x *TestMessage) GetFRepEnum() []TestEnum {
	if x != nil {
		return x.FRepEnum
	}
	return nil
}

func (x *TestMessage) GetFMapInt32String() map[int32]string {
	if x != nil {
		return x.FMapInt32String
	}
	return nil
}

func (x *TestMessage) GetFMapInt64Int32() map[int64]int32 {
	if x != nil {
		return x.FMapInt64Int32
	}
	return nil
}

func (x *TestMessage) GetFMapUint32Uint64() map[uint32]uint64 {
	if x != nil {
		return x.FMapUint32Uint64
	}
	return nil
}

func (x *TestMessage) GetFMapUint64Bool() map[uint64]bool {
	if x != nil {
		return x.FMapUint64Bool
	}
	return nil
}

func (x *TestMessage) GetFMapSint32Bytes() map[int32][]byte {
	if x != nil {
		return x.FMapSint32Bytes
	}
	return nil
}

func (x *TestMessage) GetFMapSint64Float() map[int64]float32 {
	if x != nil {
		return x.FMapSint64Float
	}
	return nil
}

func (x *TestMessage) GetFMapFixed32Double() map[uint32]float64 {
	if x != nil {
		return x.FMapFixed32Double
	}
	return nil
}

func (x *TestMessage) GetFMapFixed64Message() map[uint64]*NestedMessage {
	if x != nil {
		return x.FMapFixed64Message
	}
	return nil
}

func (x *TestMessage) GetFMapSfixed32Enum() map[int32]TestEnum {
	if x != nil {
		return x.FMapSfixed32Enum
	}
	return nil
}

func (x *TestMessage) GetFMapSfixed64String() map[int64]string {
	if x != nil {
		return x.FMapSfixed64String
	}
	return nil
}

func (x *TestMessage) GetFMapBoolInt32() map[bool]int32 {
	if x != nil {
		return x.FMapBoolInt32
	}
	return nil
}

func (x *TestMessage) GetFMapStringString() map[string]string {
	if x != nil {
		return x.FMapStringString
	}
	return nil
}

func (x *TestMessage) GetFOneof() isTestMessage_FOneof {
	if x != nil {
		return x.FOneof
	}
	return nil
}

func (x *TestMessage) GetFOneofInt32() int32 {
	if x != nil {
		if x, ok := x.FOneof.(*TestMessage_FOneofInt32); ok {
			return x.FOneofInt32
		}
	}
	return 0
}

func (x *TestMessage) GetFOneofString() string {
	if x != nil {
		if x, ok := x.FOneof.(*TestMessage_FOneofString); ok {
			return x.FOneofString
		}
	}
	return ""
}

func (x *TestMessage) GetFOneofBytes() []byte {
	if x != nil {
		if x, ok := x.FOneof.(*TestMessage_FOneofBytes); ok {
			return x.FOneofBytes
		}
	}
	return nil
}

func (x *TestMessage) GetFOneofMessage() *NestedMessage {
	if x != nil {
		if x, ok := x.FOneof.(*TestMessage_FOneofMessage); ok {
			return x.FOneofMessage
		}
	}
	return nil
}

func (x *TestMessage) GetFOneofEnum() TestEnum {
	if x != nil {
		if x, ok := x.FOneof.(*TestMessage_FOneofEnum); ok {
			return x.FOneofEnum
		}
	}
	return TestEnum_TEST_ENUM_UNSPECIFIED
}

func (x *TestMessage) GetFNestedMessage() *NestedMessage {
	if x != nil {
		return x.FNestedMessage
	}
	return nil
}

func (x *TestMessage) GetFNestedMessageEmbedded() *NestedMessage {
	if x != nil {
		return x.FNestedMessageEmbedded
	}
	return nil
}

func (x *TestMessage) GetFNestedMessageSerialized() *NestedMessage {
	if x != nil {
		return x.FNestedMessageSerialized
	}
	return nil
}

func (x *TestMessage) GetFEnum() TestEnum {
	if x != nil {
		return x.FEnum
	}
	return TestEnum_TEST_ENUM_UNSPECIFIED
}

func (x *TestMessage) GetFAny() *anypb.Any {
	if x != nil {
		return x.FAny
	}
	return nil
}

func (x *TestMessage) GetFTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.FTimestamp
	}
	return nil
}

func (x *TestMessage) GetFDuration() *durationpb.Duration {
	if x != nil {
		return x.FDuration
	}
	return nil
}

func (x *TestMessage) GetFStruct() *structpb.Struct {
	if x != nil {
		return x.FStruct
	}
	return nil
}

func (x *TestMessage) GetFValue() *structpb.Value {
	if x != nil {
		return x.FValue
	}
	return nil
}

func (x *TestMessage) GetFListValue() *structpb.ListValue {
	if x != nil {
		return x.FListValue
	}
	return nil
}

func (x *TestMessage) GetFWktDouble() *wrapperspb.DoubleValue {
	if x != nil {
		return x.FWktDouble
	}
	return nil
}

func (x *TestMessage) GetFWktFloat() *wrapperspb.FloatValue {
	if x != nil {
		return x.FWktFloat
	}
	return nil
}

func (x *TestMessage) GetFWktInt64() *wrapperspb.Int64Value {
	if x != nil {
		return x.FWktInt64
	}
	return nil
}

func (x *TestMessage) GetFWktUint64() *wrapperspb.UInt64Value {
	if x != nil {
		return x.FWktUint64
	}
	return nil
}

func (x *TestMessage) GetFWktInt32() *wrapperspb.Int32Value {
	if x != nil {
		return x.FWktInt32
	}
	return nil
}

func (x *TestMessage) GetFWktUint32() *wrapperspb.UInt32Value {
	if x != nil {
		return x.FWktUint32
	}
	return nil
}

func (x *TestMessage) GetFWktBool() *wrapperspb.BoolValue {
	if x != nil {
		return x.FWktBool
	}
	return nil
}

func (x *TestMessage) GetFWktString() *wrapperspb.StringValue {
	if x != nil {
		return x.FWktString
	}
	return nil
}

func (x *TestMessage) GetFWktBytes() *wrapperspb.BytesValue {
	if x != nil {
		return x.FWktBytes
	}
	return nil
}

func (x *TestMessage) GetFDoubleNested() *NestedMessage_InnerMessage_InnerInnerMessage {
	if x != nil {
		return x.FDoubleNested
	}
	return nil
}

type isTestMessage_FOneof interface {
	isTestMessage_FOneof()
}

type TestMessage_FOneofInt32 struct {
	FOneofInt32 int32 `protobuf:"varint,35,opt,name=f_oneof_int32,json=fOneofInt32,proto3,oneof"`
}

type TestMessage_FOneofString struct {
	FOneofString string `protobuf:"bytes,36,opt,name=f_oneof_string,json=fOneofString,proto3,oneof"`
}

type TestMessage_FOneofBytes struct {
	FOneofBytes []byte `protobuf:"bytes,37,opt,name=f_oneof_bytes,json=fOneofBytes,proto3,oneof"`
}

type TestMessage_FOneofMessage struct {
	FOneofMessage *NestedMessage `protobuf:"bytes,38,opt,name=f_oneof_message,json=fOneofMessage,proto3,oneof"`
}

type TestMessage_FOneofEnum struct {
	FOneofEnum TestEnum `protobuf:"varint,39,opt,name=f_oneof_enum,json=fOneofEnum,proto3,enum=test.TestEnum,oneof"`
}

func (*TestMessage_FOneofInt32) isTestMessage_FOneof() {}

func (*TestMessage_FOneofString) isTestMessage_FOneof() {}

func (*TestMessage_FOneofBytes) isTestMessage_FOneof() {}

func (*TestMessage_FOneofMessage) isTestMessage_FOneof() {}

func (*TestMessage_FOneofEnum) isTestMessage_FOneof() {}

type NestedMessage struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Name          string                      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Inner         *NestedMessage_InnerMessage `protobuf:"bytes,3,opt,name=inner,proto3" json:"inner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedMessage) Reset() {
	*x = NestedMessage{}
	mi := &file_test_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedMessage) ProtoMessage() {}

func (x *NestedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedMessage.ProtoReflect.Descriptor instead.
func (*NestedMessage) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{4}
}

func (x *NestedMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NestedMessage) GetInner() *NestedMessage_InnerMessage {
	if x != nil {
		return x.Inner
	}
	return nil
}

type NestedMessage_InnerMessage struct {
	state         protoimpl.MessageState                        `protogen:"open.v1"`
	InnerInner    *NestedMessage_InnerMessage_InnerInnerMessage `protobuf:"bytes,1,opt,name=inner_inner,json=innerInner,proto3" json:"inner_inner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedMessage_InnerMessage) Reset() {
	*x = NestedMessage_InnerMessage{}
	mi := &file_test_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedMessage_InnerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedMessage_InnerMessage) ProtoMessage() {}

func (x *NestedMessage_InnerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedMessage_InnerMessage.ProtoReflect.Descriptor instead.
func (*NestedMessage_InnerMessage) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{4, 0}
}

func (x *NestedMessage_InnerMessage) GetInnerInner() *NestedMessage_InnerMessage_InnerInnerMessage {
	if x != nil {
		return x.InnerInner
	}
	return nil
}

type NestedMessage_InnerMessage_InnerInnerMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Depth         int32                  `protobuf:"varint,1,opt,name=depth,proto3" json:"depth,omitempty"`
	Note          string                 `protobuf:"bytes,2,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedMessage_InnerMessage_InnerInnerMessage) Reset() {
	*x = NestedMessage_InnerMessage_InnerInnerMessage{}
	mi := &file_test_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedMessage_InnerMessage_InnerInnerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedMessage_InnerMessage_InnerInnerMessage) ProtoMessage() {}

func (x *NestedMessage_InnerMessage_InnerInnerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedMessage_InnerMessage_InnerInnerMessage.ProtoReflect.Descriptor instead.
func (*NestedMessage_InnerMessage_InnerInnerMessage) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{4, 0, 0}
}

func (x *NestedMessage_InnerMessage_InnerInnerMessage) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *NestedMessage_InnerMessage_InnerInnerMessage) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

var File_test_proto protoreflect.FileDescriptor

const file_test_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"test.proto\x12\x04test\x1a\x19google/protobuf/any.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x15goplain/goplain.proto\"+\n" +
	"\vOidcIdAlias\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value:\x06\x82\xb5\x18\x02\x10\x01\"'\n" +
	"\aIdAlias\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value:\x06\x82\xb5\x18\x02\x10\x01\"q\n" +
	"\x0eEmbedWithAlias\x125\n" +
	"\rembed_oidc_id\x18\x01 \x01(\v2\x11.test.OidcIdAliasR\vembedOidcId\x12(\n" +
	"\bembed_id\x18\x02 \x01(\v2\r.test.IdAliasR\aembedId\"\x85$\n" +
	"\vTestMessage\x12*\n" +
	"\aoidc_id\x18d \x01(\v2\x11.test.OidcIdAliasR\x06oidcId\x12\x1d\n" +
	"\x02id\x18e \x01(\v2\r.test.IdAliasR\x02id\x122\n" +
	"\x05embed\x18f \x01(\v2\x14.test.EmbedWithAliasB\x06\x82\xb5\x18\x02\b\x01R\x05embed\x12\x19\n" +
	"\bf_double\x18\x01 \x01(\x01R\afDouble\x12\x17\n" +
	"\af_float\x18\x02 \x01(\x02R\x06fFloat\x12\x17\n" +
	"\af_int32\x18\x03 \x01(\x05R\x06fInt32\x12\x17\n" +
	"\af_int64\x18\x04 \x01(\x03R\x06fInt64\x12\x19\n" +
	"\bf_uint32\x18\x05 \x01(\rR\afUint32\x12\x19\n" +
	"\bf_uint64\x18\x06 \x01(\x04R\afUint64\x12\x19\n" +
	"\bf_sint32\x18\a \x01(\x11R\afSint32\x12\x19\n" +
	"\bf_sint64\x18\b \x01(\x12R\afSint64\x12\x1b\n" +
	"\tf_fixed32\x18\t \x01(\aR\bfFixed32\x12\x1b\n" +
	"\tf_fixed64\x18\n" +
	" \x01(\x06R\bfFixed64\x12\x1d\n" +
	"\n" +
	"f_sfixed32\x18\v \x01(\x0fR\tfSfixed32\x12\x1d\n" +
	"\n" +
	"f_sfixed64\x18\f \x01(\x10R\tfSfixed64\x12\x15\n" +
	"\x06f_bool\x18\r \x01(\bR\x05fBool\x12\x19\n" +
	"\bf_string\x18\x0e \x01(\tR\afString\x12\x91\x01\n" +
	"\x06f_uuid\x18> \x01(\tBz\x82\xb5\x18v\x1at\x12\x1e\n" +
	"\x04UUID\x12\x16github.com/google/uuid2?id, err := uuid.Parse(v)\n" +
	"if err != nil { panic(err) }\n" +
	"return id:\x11return v.String()R\x05fUuid\x12\x17\n" +
	"\af_bytes\x18\x0f \x01(\fR\x06fBytes\x12#\n" +
	"\vf_opt_int32\x18\x10 \x01(\x05H\x01R\tfOptInt32\x88\x01\x01\x12%\n" +
	"\ff_opt_string\x18\x11 \x01(\tH\x02R\n" +
	"fOptString\x88\x01\x01\x12<\n" +
	"\rf_opt_message\x18\x12 \x01(\v2\x13.test.NestedMessageH\x03R\vfOptMessage\x88\x01\x01\x122\n" +
	"\n" +
	"f_opt_enum\x18\xbe\x01 \x01(\x0e2\x0e.test.TestEnumH\x04R\bfOptEnum\x88\x01\x01\x12\x1e\n" +
	"\vf_rep_int32\x18\x13 \x03(\x05R\tfRepInt32\x12 \n" +
	"\ff_rep_string\x18\x14 \x03(\tR\n" +
	"fRepString\x127\n" +
	"\rf_rep_message\x18\x15 \x03(\v2\x13.test.NestedMessageR\vfRepMessage\x12U\n" +
	"\x18f_rep_message_serialized\x18\xdc\x01 \x03(\v2\x13.test.NestedMessageB\x06\x82\xb5\x18\x02\x10\x01R\x15fRepMessageSerialized\x12,\n" +
	"\n" +
	"f_rep_enum\x18\x16 \x03(\x0e2\x0e.test.TestEnumR\bfRepEnum\x12S\n" +
	"\x12f_map_int32_string\x18\x17 \x03(\v2&.test.TestMessage.FMapInt32StringEntryR\x0ffMapInt32String\x12P\n" +
	"\x11f_map_int64_int32\x18\x18 \x03(\v2%.test.TestMessage.FMapInt64Int32EntryR\x0efMapInt64Int32\x12V\n" +
	"\x13f_map_uint32_uint64\x18\x19 \x03(\v2'.test.TestMessage.FMapUint32Uint64EntryR\x10fMapUint32Uint64\x12P\n" +
	"\x11f_map_uint64_bool\x18\x1a \x03(\v2%.test.TestMessage.FMapUint64BoolEntryR\x0efMapUint64Bool\x12S\n" +
	"\x12f_map_sint32_bytes\x18\x1b \x03(\v2&.test.TestMessage.FMapSint32BytesEntryR\x0ffMapSint32Bytes\x12S\n" +
	"\x12f_map_sint64_float\x18\x1c \x03(\v2&.test.TestMessage.FMapSint64FloatEntryR\x0ffMapSint64Float\x12Y\n" +
	"\x14f_map_fixed32_double\x18\x1d \x03(\v2(.test.TestMessage.FMapFixed32DoubleEntryR\x11fMapFixed32Double\x12\\\n" +
	"\x15f_map_fixed64_message\x18\x1e \x03(\v2).test.TestMessage.FMapFixed64MessageEntryR\x12fMapFixed64Message\x12V\n" +
	"\x13f_map_sfixed32_enum\x18\x1f \x03(\v2'.test.TestMessage.FMapSfixed32EnumEntryR\x10fMapSfixed32Enum\x12\\\n" +
	"\x15f_map_sfixed64_string\x18  \x03(\v2).test.TestMessage.FMapSfixed64StringEntryR\x12fMapSfixed64String\x12M\n" +
	"\x10f_map_bool_int32\x18! \x03(\v2$.test.TestMessage.FMapBoolInt32EntryR\rfMapBoolInt32\x12V\n" +
	"\x13f_map_string_string\x18\" \x03(\v2'.test.TestMessage.FMapStringStringEntryR\x10fMapStringString\x12$\n" +
	"\rf_oneof_int32\x18# \x01(\x05H\x00R\vfOneofInt32\x12&\n" +
	"\x0ef_oneof_string\x18$ \x01(\tH\x00R\ffOneofString\x12$\n" +
	"\rf_oneof_bytes\x18% \x01(\fH\x00R\vfOneofBytes\x12=\n" +
	"\x0ff_oneof_message\x18& \x01(\v2\x13.test.NestedMessageH\x00R\rfOneofMessage\x122\n" +
	"\ff_oneof_enum\x18' \x01(\x0e2\x0e.test.TestEnumH\x00R\n" +
	"fOneofEnum\x12=\n" +
	"\x10f_nested_message\x18( \x01(\v2\x13.test.NestedMessageR\x0efNestedMessage\x12V\n" +
	"\x19f_nested_message_embedded\x18* \x01(\v2\x13.test.NestedMessageB\x06\x82\xb5\x18\x02\b\x01R\x16fNestedMessageEmbedded\x12Z\n" +
	"\x1bf_nested_message_serialized\x18+ \x01(\v2\x13.test.NestedMessageB\x06\x82\xb5\x18\x02\x10\x01R\x18fNestedMessageSerialized\x12%\n" +
	"\x06f_enum\x18) \x01(\x0e2\x0e.test.TestEnumR\x05fEnum\x12)\n" +
	"\x05f_any\x18- \x01(\v2\x14.google.protobuf.AnyR\x04fAny\x12;\n" +
	"\vf_timestamp\x18. \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"fTimestamp\x128\n" +
	"\n" +
	"f_duration\x18/ \x01(\v2\x19.google.protobuf.DurationR\tfDuration\x122\n" +
	"\bf_struct\x182 \x01(\v2\x17.google.protobuf.StructR\afStruct\x12/\n" +
	"\af_value\x183 \x01(\v2\x16.google.protobuf.ValueR\x06fValue\x12<\n" +
	"\ff_list_value\x184 \x01(\v2\x1a.google.protobuf.ListValueR\n" +
	"fListValue\x12>\n" +
	"\ff_wkt_double\x185 \x01(\v2\x1c.google.protobuf.DoubleValueR\n" +
	"fWktDouble\x12;\n" +
	"\vf_wkt_float\x186 \x01(\v2\x1b.google.protobuf.FloatValueR\tfWktFloat\x12;\n" +
	"\vf_wkt_int64\x187 \x01(\v2\x1b.google.protobuf.Int64ValueR\tfWktInt64\x12>\n" +
	"\ff_wkt_uint64\x188 \x01(\v2\x1c.google.protobuf.UInt64ValueR\n" +
	"fWktUint64\x12;\n" +
	"\vf_wkt_int32\x189 \x01(\v2\x1b.google.protobuf.Int32ValueR\tfWktInt32\x12>\n" +
	"\ff_wkt_uint32\x18: \x01(\v2\x1c.google.protobuf.UInt32ValueR\n" +
	"fWktUint32\x128\n" +
	"\n" +
	"f_wkt_bool\x18; \x01(\v2\x1a.google.protobuf.BoolValueR\bfWktBool\x12>\n" +
	"\ff_wkt_string\x18< \x01(\v2\x1c.google.protobuf.StringValueR\n" +
	"fWktString\x12;\n" +
	"\vf_wkt_bytes\x18= \x01(\v2\x1b.google.protobuf.BytesValueR\tfWktBytes\x12Z\n" +
	"\x0ff_double_nested\x18@ \x01(\v22.test.NestedMessage.InnerMessage.InnerInnerMessageR\rfDoubleNested\x1aB\n" +
	"\x14FMapInt32StringEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aA\n" +
	"\x13FMapInt64Int32Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1aC\n" +
	"\x15FMapUint32Uint64Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\x1aA\n" +
	"\x13FMapUint64BoolEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\x1aB\n" +
	"\x14FMapSint32BytesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x11R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\x1aB\n" +
	"\x14FMapSint64FloatEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x12R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\x1aD\n" +
	"\x16FMapFixed32DoubleEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\aR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1aZ\n" +
	"\x17FMapFixed64MessageEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x06R\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.test.NestedMessageR\x05value:\x028\x01\x1aS\n" +
	"\x15FMapSfixed32EnumEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x0fR\x03key\x12$\n" +
	"\x05value\x18\x02 \x01(\x0e2\x0e.test.TestEnumR\x05value:\x028\x01\x1aE\n" +
	"\x17FMapSfixed64StringEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x10R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a@\n" +
	"\x12FMapBoolInt32Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\bR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1aC\n" +
	"\x15FMapStringStringEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01:\x06\x82\xb5\x18\x02\b\x01B\t\n" +
	"\af_oneofB\x0e\n" +
	"\f_f_opt_int32B\x0f\n" +
	"\r_f_opt_stringB\x10\n" +
	"\x0e_f_opt_messageB\r\n" +
	"\v_f_opt_enum\"\x80\x02\n" +
	"\rNestedMessage\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x126\n" +
	"\x05inner\x18\x03 \x01(\v2 .test.NestedMessage.InnerMessageR\x05inner\x1a\xa2\x01\n" +
	"\fInnerMessage\x12S\n" +
	"\vinner_inner\x18\x01 \x01(\v22.test.NestedMessage.InnerMessage.InnerInnerMessageR\n" +
	"innerInner\x1a=\n" +
	"\x11InnerInnerMessage\x12\x14\n" +
	"\x05depth\x18\x01 \x01(\x05R\x05depth\x12\x12\n" +
	"\x04note\x18\x02 \x01(\tR\x04note*K\n" +
	"\bTestEnum\x12\x19\n" +
	"\x15TEST_ENUM_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rTEST_ENUM_ONE\x10\x01\x12\x11\n" +
	"\rTEST_ENUM_TWO\x10\x02B-Z+github.com/yaroher/protoc-gen-go-plain/testb\x06proto3"

var (
	file_test_proto_rawDescOnce sync.Once
	file_test_proto_rawDescData []byte
)

func file_test_proto_rawDescGZIP() []byte {
	file_test_proto_rawDescOnce.Do(func() {
		file_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_proto_rawDesc), len(file_test_proto_rawDesc)))
	})
	return file_test_proto_rawDescData
}

var file_test_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_test_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_test_proto_goTypes = []any{
	(TestEnum)(0),                      // 0: test.TestEnum
	(*OidcIdAlias)(nil),                // 1: test.OidcIdAlias
	(*IdAlias)(nil),                    // 2: test.IdAlias
	(*EmbedWithAlias)(nil),             // 3: test.EmbedWithAlias
	(*TestMessage)(nil),                // 4: test.TestMessage
	(*NestedMessage)(nil),              // 5: test.NestedMessage
	nil,                                // 6: test.TestMessage.FMapInt32StringEntry
	nil,                                // 7: test.TestMessage.FMapInt64Int32Entry
	nil,                                // 8: test.TestMessage.FMapUint32Uint64Entry
	nil,                                // 9: test.TestMessage.FMapUint64BoolEntry
	nil,                                // 10: test.TestMessage.FMapSint32BytesEntry
	nil,                                // 11: test.TestMessage.FMapSint64FloatEntry
	nil,                                // 12: test.TestMessage.FMapFixed32DoubleEntry
	nil,                                // 13: test.TestMessage.FMapFixed64MessageEntry
	nil,                                // 14: test.TestMessage.FMapSfixed32EnumEntry
	nil,                                // 15: test.TestMessage.FMapSfixed64StringEntry
	nil,                                // 16: test.TestMessage.FMapBoolInt32Entry
	nil,                                // 17: test.TestMessage.FMapStringStringEntry
	(*NestedMessage_InnerMessage)(nil), // 18: test.NestedMessage.InnerMessage
	(*NestedMessage_InnerMessage_InnerInnerMessage)(nil), // 19: test.NestedMessage.InnerMessage.InnerInnerMessage
	(*anypb.Any)(nil),              // 20: google.protobuf.Any
	(*timestamppb.Timestamp)(nil),  // 21: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),    // 22: google.protobuf.Duration
	(*structpb.Struct)(nil),        // 23: google.protobuf.Struct
	(*structpb.Value)(nil),         // 24: google.protobuf.Value
	(*structpb.ListValue)(nil),     // 25: google.protobuf.ListValue
	(*wrapperspb.DoubleValue)(nil), // 26: google.protobuf.DoubleValue
	(*wrapperspb.FloatValue)(nil),  // 27: google.protobuf.FloatValue
	(*wrapperspb.Int64Value)(nil),  // 28: google.protobuf.Int64Value
	(*wrapperspb.UInt64Value)(nil), // 29: google.protobuf.UInt64Value
	(*wrapperspb.Int32Value)(nil),  // 30: google.protobuf.Int32Value
	(*wrapperspb.UInt32Value)(nil), // 31: google.protobuf.UInt32Value
	(*wrapperspb.BoolValue)(nil),   // 32: google.protobuf.BoolValue
	(*wrapperspb.StringValue)(nil), // 33: google.protobuf.StringValue
	(*wrapperspb.BytesValue)(nil),  // 34: google.protobuf.BytesValue
}
var file_test_proto_depIdxs = []int32{
	1,  // 0: test.EmbedWithAlias.embed_oidc_id:type_name -> test.OidcIdAlias
	2,  // 1: test.EmbedWithAlias.embed_id:type_name -> test.IdAlias
	1,  // 2: test.TestMessage.oidc_id:type_name -> test.OidcIdAlias
	2,  // 3: test.TestMessage.id:type_name -> test.IdAlias
	3,  // 4: test.TestMessage.embed:type_name -> test.EmbedWithAlias
	5,  // 5: test.TestMessage.f_opt_message:type_name -> test.NestedMessage
	0,  // 6: test.TestMessage.f_opt_enum:type_name -> test.TestEnum
	5,  // 7: test.TestMessage.f_rep_message:type_name -> test.NestedMessage
	5,  // 8: test.TestMessage.f_rep_message_serialized:type_name -> test.NestedMessage
	0,  // 9: test.TestMessage.f_rep_enum:type_name -> test.TestEnum
	6,  // 10: test.TestMessage.f_map_int32_string:type_name -> test.TestMessage.FMapInt32StringEntry
	7,  // 11: test.TestMessage.f_map_int64_int32:type_name -> test.TestMessage.FMapInt64Int32Entry
	8,  // 12: test.TestMessage.f_map_uint32_uint64:type_name -> test.TestMessage.FMapUint32Uint64Entry
	9,  // 13: test.TestMessage.f_map_uint64_bool:type_name -> test.TestMessage.FMapUint64BoolEntry
	10, // 14: test.TestMessage.f_map_sint32_bytes:type_name -> test.TestMessage.FMapSint32BytesEntry
	11, // 15: test.TestMessage.f_map_sint64_float:type_name -> test.TestMessage.FMapSint64FloatEntry
	12, // 16: test.TestMessage.f_map_fixed32_double:type_name -> test.TestMessage.FMapFixed32DoubleEntry
	13, // 17: test.TestMessage.f_map_fixed64_message:type_name -> test.TestMessage.FMapFixed64MessageEntry
	14, // 18: test.TestMessage.f_map_sfixed32_enum:type_name -> test.TestMessage.FMapSfixed32EnumEntry
	15, // 19: test.TestMessage.f_map_sfixed64_string:type_name -> test.TestMessage.FMapSfixed64StringEntry
	16, // 20: test.TestMessage.f_map_bool_int32:type_name -> test.TestMessage.FMapBoolInt32Entry
	17, // 21: test.TestMessage.f_map_string_string:type_name -> test.TestMessage.FMapStringStringEntry
	5,  // 22: test.TestMessage.f_oneof_message:type_name -> test.NestedMessage
	0,  // 23: test.TestMessage.f_oneof_enum:type_name -> test.TestEnum
	5,  // 24: test.TestMessage.f_nested_message:type_name -> test.NestedMessage
	5,  // 25: test.TestMessage.f_nested_message_embedded:type_name -> test.NestedMessage
	5,  // 26: test.TestMessage.f_nested_message_serialized:type_name -> test.NestedMessage
	0,  // 27: test.TestMessage.f_enum:type_name -> test.TestEnum
	20, // 28: test.TestMessage.f_any:type_name -> google.protobuf.Any
	21, // 29: test.TestMessage.f_timestamp:type_name -> google.protobuf.Timestamp
	22, // 30: test.TestMessage.f_duration:type_name -> google.protobuf.Duration
	23, // 31: test.TestMessage.f_struct:type_name -> google.protobuf.Struct
	24, // 32: test.TestMessage.f_value:type_name -> google.protobuf.Value
	25, // 33: test.TestMessage.f_list_value:type_name -> google.protobuf.ListValue
	26, // 34: test.TestMessage.f_wkt_double:type_name -> google.protobuf.DoubleValue
	27, // 35: test.TestMessage.f_wkt_float:type_name -> google.protobuf.FloatValue
	28, // 36: test.TestMessage.f_wkt_int64:type_name -> google.protobuf.Int64Value
	29, // 37: test.TestMessage.f_wkt_uint64:type_name -> google.protobuf.UInt64Value
	30, // 38: test.TestMessage.f_wkt_int32:type_name -> google.protobuf.Int32Value
	31, // 39: test.TestMessage.f_wkt_uint32:type_name -> google.protobuf.UInt32Value
	32, // 40: test.TestMessage.f_wkt_bool:type_name -> google.protobuf.BoolValue
	33, // 41: test.TestMessage.f_wkt_string:type_name -> google.protobuf.StringValue
	34, // 42: test.TestMessage.f_wkt_bytes:type_name -> google.protobuf.BytesValue
	19, // 43: test.TestMessage.f_double_nested:type_name -> test.NestedMessage.InnerMessage.InnerInnerMessage
	18, // 44: test.NestedMessage.inner:type_name -> test.NestedMessage.InnerMessage
	5,  // 45: test.TestMessage.FMapFixed64MessageEntry.value:type_name -> test.NestedMessage
	0,  // 46: test.TestMessage.FMapSfixed32EnumEntry.value:type_name -> test.TestEnum
	19, // 47: test.NestedMessage.InnerMessage.inner_inner:type_name -> test.NestedMessage.InnerMessage.InnerInnerMessage
	48, // [48:48] is the sub-list for method output_type
	48, // [48:48] is the sub-list for method input_type
	48, // [48:48] is the sub-list for extension type_name
	48, // [48:48] is the sub-list for extension extendee
	0,  // [0:48] is the sub-list for field type_name
}

func init() { file_test_proto_init() }
func file_test_proto_init() {
	if File_test_proto != nil {
		return
	}
	file_test_proto_msgTypes[3].OneofWrappers = []any{
		(*TestMessage_FOneofInt32)(nil),
		(*TestMessage_FOneofString)(nil),
		(*TestMessage_FOneofBytes)(nil),
		(*TestMessage_FOneofMessage)(nil),
		(*TestMessage_FOneofEnum)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_proto_rawDesc), len(file_test_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_proto_goTypes,
		DependencyIndexes: file_test_proto_depIdxs,
		EnumInfos:         file_test_proto_enumTypes,
		MessageInfos:      file_test_proto_msgTypes,
	}.Build()
	File_test_proto = out.File
	file_test_proto_goTypes = nil
	file_test_proto_depIdxs = nil
}
