// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: test/test.proto

package test

import (
	_ "github.com/yaroher/protoc-gen-go-plain/goplain"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestMessage_ContactType int32

const (
	TestMessage_CONTACT_TYPE_UNSPECIFIED TestMessage_ContactType = 0
	TestMessage_CONTACT_TYPE_EMAIL       TestMessage_ContactType = 1
	TestMessage_CONTACT_TYPE_PHONE       TestMessage_ContactType = 2
)

// Enum value maps for TestMessage_ContactType.
var (
	TestMessage_ContactType_name = map[int32]string{
		0: "CONTACT_TYPE_UNSPECIFIED",
		1: "CONTACT_TYPE_EMAIL",
		2: "CONTACT_TYPE_PHONE",
	}
	TestMessage_ContactType_value = map[string]int32{
		"CONTACT_TYPE_UNSPECIFIED": 0,
		"CONTACT_TYPE_EMAIL":       1,
		"CONTACT_TYPE_PHONE":       2,
	}
)

func (x TestMessage_ContactType) Enum() *TestMessage_ContactType {
	p := new(TestMessage_ContactType)
	*p = x
	return p
}

func (x TestMessage_ContactType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TestMessage_ContactType) Descriptor() protoreflect.EnumDescriptor {
	return file_test_test_proto_enumTypes[0].Descriptor()
}

func (TestMessage_ContactType) Type() protoreflect.EnumType {
	return &file_test_test_proto_enumTypes[0]
}

func (x TestMessage_ContactType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TestMessage_ContactType.Descriptor instead.
func (TestMessage_ContactType) EnumDescriptor() ([]byte, []int) {
	return file_test_test_proto_rawDescGZIP(), []int{0, 0}
}

type TestMessage struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id          *TestMessage_UserId    `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Email       *TestMessage_Email     `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Address     *TestMessage_Address   `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	WorkAddress *TestMessage_Address   `protobuf:"bytes,5,opt,name=work_address,json=workAddress,proto3" json:"work_address,omitempty"`
	Audit       *TestMessage_AuditInfo `protobuf:"bytes,6,opt,name=audit,proto3" json:"audit,omitempty"`
	Settings    *TestMessage_Settings  `protobuf:"bytes,7,opt,name=settings,proto3" json:"settings,omitempty"`
	RawId       string                 `protobuf:"bytes,8,opt,name=raw_id,json=rawId,proto3" json:"raw_id,omitempty"`
	CreatedAtTs *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at_ts,json=createdAtTs,proto3" json:"created_at_ts,omitempty"`
	// Types that are valid to be assigned to Contact:
	//
	//	*TestMessage_EmailContact
	//	*TestMessage_PhoneContact
	Contact isTestMessage_Contact `protobuf_oneof:"contact"`
	// Types that are valid to be assigned to BackupContact:
	//
	//	*TestMessage_BackupEmail
	//	*TestMessage_BackupPhone
	BackupContact isTestMessage_BackupContact `protobuf_oneof:"backup_contact"`
	// Types that are valid to be assigned to PaymentMethod:
	//
	//	*TestMessage_Card
	//	*TestMessage_Crypto
	PaymentMethod isTestMessage_PaymentMethod `protobuf_oneof:"payment_method"`
	// Types that are valid to be assigned to BackupPaymentMethod:
	//
	//	*TestMessage_BackupCard
	//	*TestMessage_BackupCrypto
	BackupPaymentMethod isTestMessage_BackupPaymentMethod `protobuf_oneof:"backup_payment_method"`
	ContactType         TestMessage_ContactType           `protobuf:"varint,18,opt,name=contact_type,json=contactType,proto3,enum=test.TestMessage_ContactType" json:"contact_type,omitempty"`
	// Types that are valid to be assigned to ContactEnumDispatch:
	//
	//	*TestMessage_EnumEmail
	//	*TestMessage_EnumPhone
	ContactEnumDispatch isTestMessage_ContactEnumDispatch `protobuf_oneof:"contact_enum_dispatch"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TestMessage) Reset() {
	*x = TestMessage{}
	mi := &file_test_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestMessage) ProtoMessage() {}

func (x *TestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_test_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestMessage.ProtoReflect.Descriptor instead.
func (*TestMessage) Descriptor() ([]byte, []int) {
	return file_test_test_proto_rawDescGZIP(), []int{0}
}

func (x *TestMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TestMessage) GetId() *TestMessage_UserId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *TestMessage) GetEmail() *TestMessage_Email {
	if x != nil {
		return x.Email
	}
	return nil
}

func (x *TestMessage) GetAddress() *TestMessage_Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *TestMessage) GetWorkAddress() *TestMessage_Address {
	if x != nil {
		return x.WorkAddress
	}
	return nil
}

func (x *TestMessage) GetAudit() *TestMessage_AuditInfo {
	if x != nil {
		return x.Audit
	}
	return nil
}

func (x *TestMessage) GetSettings() *TestMessage_Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *TestMessage) GetRawId() string {
	if x != nil {
		return x.RawId
	}
	return ""
}

func (x *TestMessage) GetCreatedAtTs() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAtTs
	}
	return nil
}

func (x *TestMessage) GetContact() isTestMessage_Contact {
	if x != nil {
		return x.Contact
	}
	return nil
}

func (x *TestMessage) GetEmailContact() *TestMessage_ContactEmail {
	if x != nil {
		if x, ok := x.Contact.(*TestMessage_EmailContact); ok {
			return x.EmailContact
		}
	}
	return nil
}

func (x *TestMessage) GetPhoneContact() *TestMessage_ContactPhone {
	if x != nil {
		if x, ok := x.Contact.(*TestMessage_PhoneContact); ok {
			return x.PhoneContact
		}
	}
	return nil
}

func (x *TestMessage) GetBackupContact() isTestMessage_BackupContact {
	if x != nil {
		return x.BackupContact
	}
	return nil
}

func (x *TestMessage) GetBackupEmail() *TestMessage_ContactEmail {
	if x != nil {
		if x, ok := x.BackupContact.(*TestMessage_BackupEmail); ok {
			return x.BackupEmail
		}
	}
	return nil
}

func (x *TestMessage) GetBackupPhone() *TestMessage_ContactPhone {
	if x != nil {
		if x, ok := x.BackupContact.(*TestMessage_BackupPhone); ok {
			return x.BackupPhone
		}
	}
	return nil
}

func (x *TestMessage) GetPaymentMethod() isTestMessage_PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return nil
}

func (x *TestMessage) GetCard() *TestMessage_PaymentCard {
	if x != nil {
		if x, ok := x.PaymentMethod.(*TestMessage_Card); ok {
			return x.Card
		}
	}
	return nil
}

func (x *TestMessage) GetCrypto() *TestMessage_PaymentCrypto {
	if x != nil {
		if x, ok := x.PaymentMethod.(*TestMessage_Crypto); ok {
			return x.Crypto
		}
	}
	return nil
}

func (x *TestMessage) GetBackupPaymentMethod() isTestMessage_BackupPaymentMethod {
	if x != nil {
		return x.BackupPaymentMethod
	}
	return nil
}

func (x *TestMessage) GetBackupCard() *TestMessage_PaymentCard {
	if x != nil {
		if x, ok := x.BackupPaymentMethod.(*TestMessage_BackupCard); ok {
			return x.BackupCard
		}
	}
	return nil
}

func (x *TestMessage) GetBackupCrypto() *TestMessage_PaymentCrypto {
	if x != nil {
		if x, ok := x.BackupPaymentMethod.(*TestMessage_BackupCrypto); ok {
			return x.BackupCrypto
		}
	}
	return nil
}

func (x *TestMessage) GetContactType() TestMessage_ContactType {
	if x != nil {
		return x.ContactType
	}
	return TestMessage_CONTACT_TYPE_UNSPECIFIED
}

func (x *TestMessage) GetContactEnumDispatch() isTestMessage_ContactEnumDispatch {
	if x != nil {
		return x.ContactEnumDispatch
	}
	return nil
}

func (x *TestMessage) GetEnumEmail() *TestMessage_ContactEmail {
	if x != nil {
		if x, ok := x.ContactEnumDispatch.(*TestMessage_EnumEmail); ok {
			return x.EnumEmail
		}
	}
	return nil
}

func (x *TestMessage) GetEnumPhone() *TestMessage_ContactPhone {
	if x != nil {
		if x, ok := x.ContactEnumDispatch.(*TestMessage_EnumPhone); ok {
			return x.EnumPhone
		}
	}
	return nil
}

type isTestMessage_Contact interface {
	isTestMessage_Contact()
}

type TestMessage_EmailContact struct {
	EmailContact *TestMessage_ContactEmail `protobuf:"bytes,10,opt,name=email_contact,json=emailContact,proto3,oneof"`
}

type TestMessage_PhoneContact struct {
	PhoneContact *TestMessage_ContactPhone `protobuf:"bytes,11,opt,name=phone_contact,json=phoneContact,proto3,oneof"`
}

func (*TestMessage_EmailContact) isTestMessage_Contact() {}

func (*TestMessage_PhoneContact) isTestMessage_Contact() {}

type isTestMessage_BackupContact interface {
	isTestMessage_BackupContact()
}

type TestMessage_BackupEmail struct {
	BackupEmail *TestMessage_ContactEmail `protobuf:"bytes,12,opt,name=backup_email,json=backupEmail,proto3,oneof"`
}

type TestMessage_BackupPhone struct {
	BackupPhone *TestMessage_ContactPhone `protobuf:"bytes,13,opt,name=backup_phone,json=backupPhone,proto3,oneof"`
}

func (*TestMessage_BackupEmail) isTestMessage_BackupContact() {}

func (*TestMessage_BackupPhone) isTestMessage_BackupContact() {}

type isTestMessage_PaymentMethod interface {
	isTestMessage_PaymentMethod()
}

type TestMessage_Card struct {
	Card *TestMessage_PaymentCard `protobuf:"bytes,14,opt,name=card,proto3,oneof"`
}

type TestMessage_Crypto struct {
	Crypto *TestMessage_PaymentCrypto `protobuf:"bytes,15,opt,name=crypto,proto3,oneof"`
}

func (*TestMessage_Card) isTestMessage_PaymentMethod() {}

func (*TestMessage_Crypto) isTestMessage_PaymentMethod() {}

type isTestMessage_BackupPaymentMethod interface {
	isTestMessage_BackupPaymentMethod()
}

type TestMessage_BackupCard struct {
	BackupCard *TestMessage_PaymentCard `protobuf:"bytes,16,opt,name=backup_card,json=backupCard,proto3,oneof"`
}

type TestMessage_BackupCrypto struct {
	BackupCrypto *TestMessage_PaymentCrypto `protobuf:"bytes,17,opt,name=backup_crypto,json=backupCrypto,proto3,oneof"`
}

func (*TestMessage_BackupCard) isTestMessage_BackupPaymentMethod() {}

func (*TestMessage_BackupCrypto) isTestMessage_BackupPaymentMethod() {}

type isTestMessage_ContactEnumDispatch interface {
	isTestMessage_ContactEnumDispatch()
}

type TestMessage_EnumEmail struct {
	EnumEmail *TestMessage_ContactEmail `protobuf:"bytes,19,opt,name=enum_email,json=enumEmail,proto3,oneof"`
}

type TestMessage_EnumPhone struct {
	EnumPhone *TestMessage_ContactPhone `protobuf:"bytes,20,opt,name=enum_phone,json=enumPhone,proto3,oneof"`
}

func (*TestMessage_EnumEmail) isTestMessage_ContactEnumDispatch() {}

func (*TestMessage_EnumPhone) isTestMessage_ContactEnumDispatch() {}

type TestMessage_UserId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestMessage_UserId) Reset() {
	*x = TestMessage_UserId{}
	mi := &file_test_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestMessage_UserId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestMessage_UserId) ProtoMessage() {}

func (x *TestMessage_UserId) ProtoReflect() protoreflect.Message {
	mi := &file_test_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestMessage_UserId.ProtoReflect.Descriptor instead.
func (*TestMessage_UserId) Descriptor() ([]byte, []int) {
	return file_test_test_proto_rawDescGZIP(), []int{0, 0}
}

func (x *TestMessage_UserId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type TestMessage_Email struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestMessage_Email) Reset() {
	*x = TestMessage_Email{}
	mi := &file_test_test_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestMessage_Email) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestMessage_Email) ProtoMessage() {}

func (x *TestMessage_Email) ProtoReflect() protoreflect.Message {
	mi := &file_test_test_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestMessage_Email.ProtoReflect.Descriptor instead.
func (*TestMessage_Email) Descriptor() ([]byte, []int) {
	return file_test_test_proto_rawDescGZIP(), []int{0, 1}
}

func (x *TestMessage_Email) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type TestMessage_Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street        string                 `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Country       string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestMessage_Address) Reset() {
	*x = TestMessage_Address{}
	mi := &file_test_test_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestMessage_Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestMessage_Address) ProtoMessage() {}

func (x *TestMessage_Address) ProtoReflect() protoreflect.Message {
	mi := &file_test_test_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestMessage_Address.ProtoReflect.Descriptor instead.
func (*TestMessage_Address) Descriptor() ([]byte, []int) {
	return file_test_test_proto_rawDescGZIP(), []int{0, 2}
}

func (x *TestMessage_Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *TestMessage_Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *TestMessage_Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type TestMessage_AuditInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestMessage_AuditInfo) Reset() {
	*x = TestMessage_AuditInfo{}
	mi := &file_test_test_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestMessage_AuditInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestMessage_AuditInfo) ProtoMessage() {}

func (x *TestMessage_AuditInfo) ProtoReflect() protoreflect.Message {
	mi := &file_test_test_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestMessage_AuditInfo.ProtoReflect.Descriptor instead.
func (*TestMessage_AuditInfo) Descriptor() ([]byte, []int) {
	return file_test_test_proto_rawDescGZIP(), []int{0, 3}
}

func (x *TestMessage_AuditInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *TestMessage_AuditInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type TestMessage_Settings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Theme         string                 `protobuf:"bytes,1,opt,name=theme,proto3" json:"theme,omitempty"`
	Notifications bool                   `protobuf:"varint,2,opt,name=notifications,proto3" json:"notifications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestMessage_Settings) Reset() {
	*x = TestMessage_Settings{}
	mi := &file_test_test_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestMessage_Settings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestMessage_Settings) ProtoMessage() {}

func (x *TestMessage_Settings) ProtoReflect() protoreflect.Message {
	mi := &file_test_test_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestMessage_Settings.ProtoReflect.Descriptor instead.
func (*TestMessage_Settings) Descriptor() ([]byte, []int) {
	return file_test_test_proto_rawDescGZIP(), []int{0, 4}
}

func (x *TestMessage_Settings) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *TestMessage_Settings) GetNotifications() bool {
	if x != nil {
		return x.Notifications
	}
	return false
}

type TestMessage_ContactEmail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestMessage_ContactEmail) Reset() {
	*x = TestMessage_ContactEmail{}
	mi := &file_test_test_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestMessage_ContactEmail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestMessage_ContactEmail) ProtoMessage() {}

func (x *TestMessage_ContactEmail) ProtoReflect() protoreflect.Message {
	mi := &file_test_test_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestMessage_ContactEmail.ProtoReflect.Descriptor instead.
func (*TestMessage_ContactEmail) Descriptor() ([]byte, []int) {
	return file_test_test_proto_rawDescGZIP(), []int{0, 5}
}

func (x *TestMessage_ContactEmail) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type TestMessage_ContactPhone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestMessage_ContactPhone) Reset() {
	*x = TestMessage_ContactPhone{}
	mi := &file_test_test_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestMessage_ContactPhone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestMessage_ContactPhone) ProtoMessage() {}

func (x *TestMessage_ContactPhone) ProtoReflect() protoreflect.Message {
	mi := &file_test_test_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestMessage_ContactPhone.ProtoReflect.Descriptor instead.
func (*TestMessage_ContactPhone) Descriptor() ([]byte, []int) {
	return file_test_test_proto_rawDescGZIP(), []int{0, 6}
}

func (x *TestMessage_ContactPhone) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type TestMessage_PaymentCard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardNumber    string                 `protobuf:"bytes,1,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestMessage_PaymentCard) Reset() {
	*x = TestMessage_PaymentCard{}
	mi := &file_test_test_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestMessage_PaymentCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestMessage_PaymentCard) ProtoMessage() {}

func (x *TestMessage_PaymentCard) ProtoReflect() protoreflect.Message {
	mi := &file_test_test_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestMessage_PaymentCard.ProtoReflect.Descriptor instead.
func (*TestMessage_PaymentCard) Descriptor() ([]byte, []int) {
	return file_test_test_proto_rawDescGZIP(), []int{0, 7}
}

func (x *TestMessage_PaymentCard) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

type TestMessage_PaymentCrypto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wallet        string                 `protobuf:"bytes,1,opt,name=wallet,proto3" json:"wallet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestMessage_PaymentCrypto) Reset() {
	*x = TestMessage_PaymentCrypto{}
	mi := &file_test_test_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestMessage_PaymentCrypto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestMessage_PaymentCrypto) ProtoMessage() {}

func (x *TestMessage_PaymentCrypto) ProtoReflect() protoreflect.Message {
	mi := &file_test_test_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestMessage_PaymentCrypto.ProtoReflect.Descriptor instead.
func (*TestMessage_PaymentCrypto) Descriptor() ([]byte, []int) {
	return file_test_test_proto_rawDescGZIP(), []int{0, 8}
}

func (x *TestMessage_PaymentCrypto) GetWallet() string {
	if x != nil {
		return x.Wallet
	}
	return ""
}

var File_test_test_proto protoreflect.FileDescriptor

const file_test_test_proto_rawDesc = "" +
	"\n" +
	"\x0ftest/test.proto\x12\x04test\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x15goplain/goplain.proto\"\xb0\x11\n" +
	"\vTestMessage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12(\n" +
	"\x02id\x18\x02 \x01(\v2\x18.test.TestMessage.UserIdR\x02id\x12-\n" +
	"\x05email\x18\x03 \x01(\v2\x17.test.TestMessage.EmailR\x05email\x12;\n" +
	"\aaddress\x18\x04 \x01(\v2\x19.test.TestMessage.AddressB\x06\x82\xa6\x1d\x02 \x01R\aaddress\x12D\n" +
	"\fwork_address\x18\x05 \x01(\v2\x19.test.TestMessage.AddressB\x06\x82\xa6\x1d\x02(\x01R\vworkAddress\x129\n" +
	"\x05audit\x18\x06 \x01(\v2\x1b.test.TestMessage.AuditInfoB\x06\x82\xa6\x1d\x02 \x01R\x05audit\x12>\n" +
	"\bsettings\x18\a \x01(\v2\x1a.test.TestMessage.SettingsB\x06\x82\xa6\x1d\x02\x10\x01R\bsettings\x12;\n" +
	"\x06raw_id\x18\b \x01(\tB$\x82\xa6\x1d \n" +
	"\x1e\n" +
	"\x04UUID\x12\x16github.com/google/uuidR\x05rawId\x12R\n" +
	"\rcreated_at_ts\x18\t \x01(\v2\x1a.google.protobuf.TimestampB\x12\x82\xa6\x1d\x0e\n" +
	"\f\n" +
	"\x04Time\x12\x04timeR\vcreatedAtTs\x12E\n" +
	"\remail_contact\x18\n" +
	" \x01(\v2\x1e.test.TestMessage.ContactEmailH\x00R\femailContact\x12E\n" +
	"\rphone_contact\x18\v \x01(\v2\x1e.test.TestMessage.ContactPhoneH\x00R\fphoneContact\x12C\n" +
	"\fbackup_email\x18\f \x01(\v2\x1e.test.TestMessage.ContactEmailH\x01R\vbackupEmail\x12C\n" +
	"\fbackup_phone\x18\r \x01(\v2\x1e.test.TestMessage.ContactPhoneH\x01R\vbackupPhone\x123\n" +
	"\x04card\x18\x0e \x01(\v2\x1d.test.TestMessage.PaymentCardH\x02R\x04card\x129\n" +
	"\x06crypto\x18\x0f \x01(\v2\x1f.test.TestMessage.PaymentCryptoH\x02R\x06crypto\x12@\n" +
	"\vbackup_card\x18\x10 \x01(\v2\x1d.test.TestMessage.PaymentCardH\x03R\n" +
	"backupCard\x12F\n" +
	"\rbackup_crypto\x18\x11 \x01(\v2\x1f.test.TestMessage.PaymentCryptoH\x03R\fbackupCrypto\x12@\n" +
	"\fcontact_type\x18\x12 \x01(\x0e2\x1d.test.TestMessage.ContactTypeR\vcontactType\x12Y\n" +
	"\n" +
	"enum_email\x18\x13 \x01(\v2\x1e.test.TestMessage.ContactEmailB\x18\x82\xa6\x1d\x142\x12CONTACT_TYPE_EMAILH\x04R\tenumEmail\x12Y\n" +
	"\n" +
	"enum_phone\x18\x14 \x01(\v2\x1e.test.TestMessage.ContactPhoneB\x18\x82\xa6\x1d\x142\x12CONTACT_TYPE_PHONEH\x04R\tenumPhone\x1a&\n" +
	"\x06UserId\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value:\x06\x82\xa6\x1d\x02\x10\x01\x1a%\n" +
	"\x05Email\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value:\x06\x82\xa6\x1d\x02\x10\x01\x1aO\n" +
	"\aAddress\x12\x16\n" +
	"\x06street\x18\x01 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\x1a\x81\x01\n" +
	"\tAuditInfo\x129\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1aF\n" +
	"\bSettings\x12\x14\n" +
	"\x05theme\x18\x01 \x01(\tR\x05theme\x12$\n" +
	"\rnotifications\x18\x02 \x01(\bR\rnotifications\x1a$\n" +
	"\fContactEmail\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x1a$\n" +
	"\fContactPhone\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x1a.\n" +
	"\vPaymentCard\x12\x1f\n" +
	"\vcard_number\x18\x01 \x01(\tR\n" +
	"cardNumber\x1a'\n" +
	"\rPaymentCrypto\x12\x16\n" +
	"\x06wallet\x18\x01 \x01(\tR\x06wallet\"[\n" +
	"\vContactType\x12\x1c\n" +
	"\x18CONTACT_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12CONTACT_TYPE_EMAIL\x10\x01\x12\x16\n" +
	"\x12CONTACT_TYPE_PHONE\x10\x02:\x87\x01\x82\xa6\x1d\x82\x01\b\x01\x1a\x11\b\f\"\rpassword_hash\x1a\x13\b\x03\"\x0fcreated_at_unix\x1a(\b\v\"\tvirt_addr2\x19.test.TestMessage.Address\x1a,\b\x0e\"\tvirt_enum2\x1d.test.TestMessage.ContactTypeB\x11\n" +
	"\acontact\x12\x06\x82\xb5\x18\x02\b\x01B\x18\n" +
	"\x0ebackup_contact\x12\x06\x82\xb5\x18\x02\x10\x01B\x18\n" +
	"\x0epayment_method\x12\x06\x82\xb5\x18\x02\x18\x01B\x1f\n" +
	"\x15backup_payment_method\x12\x06\x82\xb5\x18\x02 \x01B;\n" +
	"\x15contact_enum_dispatch\x12\"\x82\xb5\x18\x1e*\x1ctest.TestMessage.ContactTypeBW\x82\xa6\x1d&\n" +
	"$\n" +
	"\x02\x10\t\x12\x1e\n" +
	"\x04UUID\x12\x16github.com/google/uuidZ+github.com/yaroher/protoc-gen-go-plain/testb\x06proto3"

var (
	file_test_test_proto_rawDescOnce sync.Once
	file_test_test_proto_rawDescData []byte
)

func file_test_test_proto_rawDescGZIP() []byte {
	file_test_test_proto_rawDescOnce.Do(func() {
		file_test_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_test_proto_rawDesc), len(file_test_test_proto_rawDesc)))
	})
	return file_test_test_proto_rawDescData
}

var file_test_test_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_test_test_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_test_test_proto_goTypes = []any{
	(TestMessage_ContactType)(0),      // 0: test.TestMessage.ContactType
	(*TestMessage)(nil),               // 1: test.TestMessage
	(*TestMessage_UserId)(nil),        // 2: test.TestMessage.UserId
	(*TestMessage_Email)(nil),         // 3: test.TestMessage.Email
	(*TestMessage_Address)(nil),       // 4: test.TestMessage.Address
	(*TestMessage_AuditInfo)(nil),     // 5: test.TestMessage.AuditInfo
	(*TestMessage_Settings)(nil),      // 6: test.TestMessage.Settings
	(*TestMessage_ContactEmail)(nil),  // 7: test.TestMessage.ContactEmail
	(*TestMessage_ContactPhone)(nil),  // 8: test.TestMessage.ContactPhone
	(*TestMessage_PaymentCard)(nil),   // 9: test.TestMessage.PaymentCard
	(*TestMessage_PaymentCrypto)(nil), // 10: test.TestMessage.PaymentCrypto
	(*timestamppb.Timestamp)(nil),     // 11: google.protobuf.Timestamp
}
var file_test_test_proto_depIdxs = []int32{
	2,  // 0: test.TestMessage.id:type_name -> test.TestMessage.UserId
	3,  // 1: test.TestMessage.email:type_name -> test.TestMessage.Email
	4,  // 2: test.TestMessage.address:type_name -> test.TestMessage.Address
	4,  // 3: test.TestMessage.work_address:type_name -> test.TestMessage.Address
	5,  // 4: test.TestMessage.audit:type_name -> test.TestMessage.AuditInfo
	6,  // 5: test.TestMessage.settings:type_name -> test.TestMessage.Settings
	11, // 6: test.TestMessage.created_at_ts:type_name -> google.protobuf.Timestamp
	7,  // 7: test.TestMessage.email_contact:type_name -> test.TestMessage.ContactEmail
	8,  // 8: test.TestMessage.phone_contact:type_name -> test.TestMessage.ContactPhone
	7,  // 9: test.TestMessage.backup_email:type_name -> test.TestMessage.ContactEmail
	8,  // 10: test.TestMessage.backup_phone:type_name -> test.TestMessage.ContactPhone
	9,  // 11: test.TestMessage.card:type_name -> test.TestMessage.PaymentCard
	10, // 12: test.TestMessage.crypto:type_name -> test.TestMessage.PaymentCrypto
	9,  // 13: test.TestMessage.backup_card:type_name -> test.TestMessage.PaymentCard
	10, // 14: test.TestMessage.backup_crypto:type_name -> test.TestMessage.PaymentCrypto
	0,  // 15: test.TestMessage.contact_type:type_name -> test.TestMessage.ContactType
	7,  // 16: test.TestMessage.enum_email:type_name -> test.TestMessage.ContactEmail
	8,  // 17: test.TestMessage.enum_phone:type_name -> test.TestMessage.ContactPhone
	11, // 18: test.TestMessage.AuditInfo.created_at:type_name -> google.protobuf.Timestamp
	11, // 19: test.TestMessage.AuditInfo.updated_at:type_name -> google.protobuf.Timestamp
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_test_test_proto_init() }
func file_test_test_proto_init() {
	if File_test_test_proto != nil {
		return
	}
	file_test_test_proto_msgTypes[0].OneofWrappers = []any{
		(*TestMessage_EmailContact)(nil),
		(*TestMessage_PhoneContact)(nil),
		(*TestMessage_BackupEmail)(nil),
		(*TestMessage_BackupPhone)(nil),
		(*TestMessage_Card)(nil),
		(*TestMessage_Crypto)(nil),
		(*TestMessage_BackupCard)(nil),
		(*TestMessage_BackupCrypto)(nil),
		(*TestMessage_EnumEmail)(nil),
		(*TestMessage_EnumPhone)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_test_proto_rawDesc), len(file_test_test_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_test_proto_goTypes,
		DependencyIndexes: file_test_test_proto_depIdxs,
		EnumInfos:         file_test_test_proto_enumTypes,
		MessageInfos:      file_test_test_proto_msgTypes,
	}.Build()
	File_test_test_proto = out.File
	file_test_test_proto_goTypes = nil
	file_test_test_proto_depIdxs = nil
}
