// Code generated by protoc-gen-go-plain. DO NOT EDIT.

package enum_dispatched

type PaymentPlain_MethodType int32

const (
	PaymentPlain_METHOD_TYPE_UNSPECIFIED PaymentPlain_MethodType = 0
	PaymentPlain_METHOD_TYPE_CARD        PaymentPlain_MethodType = 1
	PaymentPlain_METHOD_TYPE_CRYPTO      PaymentPlain_MethodType = 2
)

type PaymentPlain_BackupMethodType int32

const (
	PaymentPlain_BACKUP_METHOD_TYPE_UNSPECIFIED   PaymentPlain_BackupMethodType = 0
	PaymentPlain_BACKUP_METHOD_TYPE_BACKUP_CARD   PaymentPlain_BackupMethodType = 1
	PaymentPlain_BACKUP_METHOD_TYPE_BACKUP_CRYPTO PaymentPlain_BackupMethodType = 2
)

type PaymentPlain struct {

	// src: <virtual>; transform: virtual
	MethodType PaymentPlain_MethodType
	// src: .test.enum_dispatched.Payment.card; transform: oneof
	Card *PaymentCard
	// src: .test.enum_dispatched.Payment.crypto; transform: oneof
	Crypto *PaymentCrypto
	// src: <virtual>; transform: virtual
	BackupMethodBackupMethodType PaymentPlain_BackupMethodType
	// src: .test.enum_dispatched.Payment.backup_card; transform: oneof
	BackupMethodBackupCard *PaymentCard
	// src: .test.enum_dispatched.Payment.backup_crypto; transform: oneof
	BackupMethodBackupCrypto *PaymentCrypto
}

func (m *Payment) IntoPlain() *PaymentPlain {
	if m == nil {
		return nil
	}
	var oneof_card *PaymentCard
	var oneof_crypto *PaymentCrypto
	switch x := m.GetMethod().(type) {
	case *Payment_Card:
		oneof_card = x.Card
	case *Payment_Crypto:
		oneof_crypto = x.Crypto
	}
	var oneof_backupMethodBackupCard *PaymentCard
	var oneof_backupMethodBackupCrypto *PaymentCrypto
	switch x := m.GetBackupMethod().(type) {
	case *Payment_BackupCard:
		oneof_backupMethodBackupCard = x.BackupCard
	case *Payment_BackupCrypto:
		oneof_backupMethodBackupCrypto = x.BackupCrypto
	}
	return &PaymentPlain{
		Card:                     oneof_card,
		Crypto:                   oneof_crypto,
		BackupMethodBackupCard:   oneof_backupMethodBackupCard,
		BackupMethodBackupCrypto: oneof_backupMethodBackupCrypto,
	}
}

func (m *Payment) IntoPlainErr() (*PaymentPlain, error) {
	if m == nil {
		return nil, nil
	}
	var oneof_backupMethodBackupCard *PaymentCard
	var oneof_backupMethodBackupCrypto *PaymentCrypto
	switch x := m.GetBackupMethod().(type) {
	case *Payment_BackupCard:
		oneof_backupMethodBackupCard = x.BackupCard
	case *Payment_BackupCrypto:
		oneof_backupMethodBackupCrypto = x.BackupCrypto
	}
	var oneof_card *PaymentCard
	var oneof_crypto *PaymentCrypto
	switch x := m.GetMethod().(type) {
	case *Payment_Card:
		oneof_card = x.Card
	case *Payment_Crypto:
		oneof_crypto = x.Crypto
	}
	return &PaymentPlain{
		Card:                     oneof_card,
		Crypto:                   oneof_crypto,
		BackupMethodBackupCard:   oneof_backupMethodBackupCard,
		BackupMethodBackupCrypto: oneof_backupMethodBackupCrypto,
	}, nil
}

func (m *PaymentPlain) IntoPb() *Payment {
	if m == nil {
		return nil
	}
	var oneof_method isPayment_Method
	if m.Card != nil {
		oneof_method = &Payment_Card{Card: m.Card}
	}
	if m.Crypto != nil {
		oneof_method = &Payment_Crypto{Crypto: m.Crypto}
	}
	var oneof_backupMethod isPayment_BackupMethod
	if m.BackupMethodBackupCard != nil {
		oneof_backupMethod = &Payment_BackupCard{BackupCard: m.BackupMethodBackupCard}
	}
	if m.BackupMethodBackupCrypto != nil {
		oneof_backupMethod = &Payment_BackupCrypto{BackupCrypto: m.BackupMethodBackupCrypto}
	}
	return &Payment{
		Method:       oneof_method,
		BackupMethod: oneof_backupMethod,
	}
}

func (m *PaymentPlain) IntoPbErr() (*Payment, error) {
	if m == nil {
		return nil, nil
	}
	var oneof_method isPayment_Method
	if m.Card != nil {
		oneof_method = &Payment_Card{Card: m.Card}
	}
	if m.Crypto != nil {
		oneof_method = &Payment_Crypto{Crypto: m.Crypto}
	}
	var oneof_backupMethod isPayment_BackupMethod
	if m.BackupMethodBackupCard != nil {
		oneof_backupMethod = &Payment_BackupCard{BackupCard: m.BackupMethodBackupCard}
	}
	if m.BackupMethodBackupCrypto != nil {
		oneof_backupMethod = &Payment_BackupCrypto{BackupCrypto: m.BackupMethodBackupCrypto}
	}
	return &Payment{
		Method:       oneof_method,
		BackupMethod: oneof_backupMethod,
	}, nil
}
