// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: tests/integrations/discriminator/test.proto

package discriminator

import (
	_ "github.com/yaroher/protoc-gen-go-plain/goplain"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContactKind int32

const (
	ContactKind_CONTACT_KIND_UNSPECIFIED ContactKind = 0
	ContactKind_CONTACT_KIND_EMAIL       ContactKind = 1
	ContactKind_CONTACT_KIND_PHONE       ContactKind = 2
)

// Enum value maps for ContactKind.
var (
	ContactKind_name = map[int32]string{
		0: "CONTACT_KIND_UNSPECIFIED",
		1: "CONTACT_KIND_EMAIL",
		2: "CONTACT_KIND_PHONE",
	}
	ContactKind_value = map[string]int32{
		"CONTACT_KIND_UNSPECIFIED": 0,
		"CONTACT_KIND_EMAIL":       1,
		"CONTACT_KIND_PHONE":       2,
	}
)

func (x ContactKind) Enum() *ContactKind {
	p := new(ContactKind)
	*p = x
	return p
}

func (x ContactKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContactKind) Descriptor() protoreflect.EnumDescriptor {
	return file_tests_integrations_discriminator_test_proto_enumTypes[0].Descriptor()
}

func (ContactKind) Type() protoreflect.EnumType {
	return &file_tests_integrations_discriminator_test_proto_enumTypes[0]
}

func (x ContactKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContactKind.Descriptor instead.
func (ContactKind) EnumDescriptor() ([]byte, []int) {
	return file_tests_integrations_discriminator_test_proto_rawDescGZIP(), []int{0}
}

type IdKind int32

const (
	IdKind_ID_KIND_UNSPECIFIED IdKind = 0
	IdKind_ID_KIND_USER        IdKind = 1
)

// Enum value maps for IdKind.
var (
	IdKind_name = map[int32]string{
		0: "ID_KIND_UNSPECIFIED",
		1: "ID_KIND_USER",
	}
	IdKind_value = map[string]int32{
		"ID_KIND_UNSPECIFIED": 0,
		"ID_KIND_USER":        1,
	}
)

func (x IdKind) Enum() *IdKind {
	p := new(IdKind)
	*p = x
	return p
}

func (x IdKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IdKind) Descriptor() protoreflect.EnumDescriptor {
	return file_tests_integrations_discriminator_test_proto_enumTypes[1].Descriptor()
}

func (IdKind) Type() protoreflect.EnumType {
	return &file_tests_integrations_discriminator_test_proto_enumTypes[1]
}

func (x IdKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IdKind.Descriptor instead.
func (IdKind) EnumDescriptor() ([]byte, []int) {
	return file_tests_integrations_discriminator_test_proto_rawDescGZIP(), []int{1}
}

type Email struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Email) Reset() {
	*x = Email{}
	mi := &file_tests_integrations_discriminator_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Email) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Email) ProtoMessage() {}

func (x *Email) ProtoReflect() protoreflect.Message {
	mi := &file_tests_integrations_discriminator_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Email.ProtoReflect.Descriptor instead.
func (*Email) Descriptor() ([]byte, []int) {
	return file_tests_integrations_discriminator_test_proto_rawDescGZIP(), []int{0}
}

func (x *Email) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Phone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Phone) Reset() {
	*x = Phone{}
	mi := &file_tests_integrations_discriminator_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Phone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Phone) ProtoMessage() {}

func (x *Phone) ProtoReflect() protoreflect.Message {
	mi := &file_tests_integrations_discriminator_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Phone.ProtoReflect.Descriptor instead.
func (*Phone) Descriptor() ([]byte, []int) {
	return file_tests_integrations_discriminator_test_proto_rawDescGZIP(), []int{1}
}

func (x *Phone) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type UserId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserId) Reset() {
	*x = UserId{}
	mi := &file_tests_integrations_discriminator_test_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserId) ProtoMessage() {}

func (x *UserId) ProtoReflect() protoreflect.Message {
	mi := &file_tests_integrations_discriminator_test_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserId.ProtoReflect.Descriptor instead.
func (*UserId) Descriptor() ([]byte, []int) {
	return file_tests_integrations_discriminator_test_proto_rawDescGZIP(), []int{2}
}

func (x *UserId) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type User struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ContactKind ContactKind            `protobuf:"varint,1,opt,name=contact_kind,json=contactKind,proto3,enum=test.discriminator.ContactKind" json:"contact_kind,omitempty"`
	IdKind      IdKind                 `protobuf:"varint,2,opt,name=id_kind,json=idKind,proto3,enum=test.discriminator.IdKind" json:"id_kind,omitempty"`
	// Types that are valid to be assigned to Contact:
	//
	//	*User_Email
	//	*User_Phone
	Contact isUser_Contact `protobuf_oneof:"contact"`
	// Types that are valid to be assigned to Identity:
	//
	//	*User_UserId
	Identity      isUser_Identity `protobuf_oneof:"identity"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_tests_integrations_discriminator_test_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_tests_integrations_discriminator_test_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_tests_integrations_discriminator_test_proto_rawDescGZIP(), []int{3}
}

func (x *User) GetContactKind() ContactKind {
	if x != nil {
		return x.ContactKind
	}
	return ContactKind_CONTACT_KIND_UNSPECIFIED
}

func (x *User) GetIdKind() IdKind {
	if x != nil {
		return x.IdKind
	}
	return IdKind_ID_KIND_UNSPECIFIED
}

func (x *User) GetContact() isUser_Contact {
	if x != nil {
		return x.Contact
	}
	return nil
}

func (x *User) GetEmail() *Email {
	if x != nil {
		if x, ok := x.Contact.(*User_Email); ok {
			return x.Email
		}
	}
	return nil
}

func (x *User) GetPhone() *Phone {
	if x != nil {
		if x, ok := x.Contact.(*User_Phone); ok {
			return x.Phone
		}
	}
	return nil
}

func (x *User) GetIdentity() isUser_Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *User) GetUserId() *UserId {
	if x != nil {
		if x, ok := x.Identity.(*User_UserId); ok {
			return x.UserId
		}
	}
	return nil
}

type isUser_Contact interface {
	isUser_Contact()
}

type User_Email struct {
	Email *Email `protobuf:"bytes,3,opt,name=email,proto3,oneof"`
}

type User_Phone struct {
	Phone *Phone `protobuf:"bytes,4,opt,name=phone,proto3,oneof"`
}

func (*User_Email) isUser_Contact() {}

func (*User_Phone) isUser_Contact() {}

type isUser_Identity interface {
	isUser_Identity()
}

type User_UserId struct {
	UserId *UserId `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3,oneof"`
}

func (*User_UserId) isUser_Identity() {}

var File_tests_integrations_discriminator_test_proto protoreflect.FileDescriptor

const file_tests_integrations_discriminator_test_proto_rawDesc = "" +
	"\n" +
	"+tests/integrations/discriminator/test.proto\x12\x12test.discriminator\x1a\x15goplain/goplain.proto\"\x1d\n" +
	"\x05Email\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\x1d\n" +
	"\x05Phone\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\x1e\n" +
	"\x06UserId\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\xde\x03\n" +
	"\x04User\x12B\n" +
	"\fcontact_kind\x18\x01 \x01(\x0e2\x1f.test.discriminator.ContactKindR\vcontactKind\x123\n" +
	"\aid_kind\x18\x02 \x01(\x0e2\x1a.test.discriminator.IdKindR\x06idKind\x12k\n" +
	"\x05email\x18\x03 \x01(\v2\x19.test.discriminator.EmailB8\x82\xa6\x1d422.test.discriminator.ContactKind.CONTACT_KIND_EMAILH\x00R\x05email\x12k\n" +
	"\x05phone\x18\x04 \x01(\v2\x19.test.discriminator.PhoneB8\x82\xa6\x1d422.test.discriminator.ContactKind.CONTACT_KIND_PHONEH\x00R\x05phone\x12d\n" +
	"\auser_id\x18\x05 \x01(\v2\x1a.test.discriminator.UserIdB-\x82\xa6\x1d)2'.test.discriminator.IdKind.ID_KIND_USERH\x01R\x06userId:\x06\x82\xa6\x1d\x02\b\x01B\t\n" +
	"\acontactB\n" +
	"\n" +
	"\bidentity*[\n" +
	"\vContactKind\x12\x1c\n" +
	"\x18CONTACT_KIND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12CONTACT_KIND_EMAIL\x10\x01\x12\x16\n" +
	"\x12CONTACT_KIND_PHONE\x10\x02*3\n" +
	"\x06IdKind\x12\x17\n" +
	"\x13ID_KIND_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fID_KIND_USER\x10\x01BWZUgithub.com/yaroher/protoc-gen-go-plain/tests/integrations/discriminator;discriminatorb\x06proto3"

var (
	file_tests_integrations_discriminator_test_proto_rawDescOnce sync.Once
	file_tests_integrations_discriminator_test_proto_rawDescData []byte
)

func file_tests_integrations_discriminator_test_proto_rawDescGZIP() []byte {
	file_tests_integrations_discriminator_test_proto_rawDescOnce.Do(func() {
		file_tests_integrations_discriminator_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tests_integrations_discriminator_test_proto_rawDesc), len(file_tests_integrations_discriminator_test_proto_rawDesc)))
	})
	return file_tests_integrations_discriminator_test_proto_rawDescData
}

var file_tests_integrations_discriminator_test_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_tests_integrations_discriminator_test_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tests_integrations_discriminator_test_proto_goTypes = []any{
	(ContactKind)(0), // 0: test.discriminator.ContactKind
	(IdKind)(0),      // 1: test.discriminator.IdKind
	(*Email)(nil),    // 2: test.discriminator.Email
	(*Phone)(nil),    // 3: test.discriminator.Phone
	(*UserId)(nil),   // 4: test.discriminator.UserId
	(*User)(nil),     // 5: test.discriminator.User
}
var file_tests_integrations_discriminator_test_proto_depIdxs = []int32{
	0, // 0: test.discriminator.User.contact_kind:type_name -> test.discriminator.ContactKind
	1, // 1: test.discriminator.User.id_kind:type_name -> test.discriminator.IdKind
	2, // 2: test.discriminator.User.email:type_name -> test.discriminator.Email
	3, // 3: test.discriminator.User.phone:type_name -> test.discriminator.Phone
	4, // 4: test.discriminator.User.user_id:type_name -> test.discriminator.UserId
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_tests_integrations_discriminator_test_proto_init() }
func file_tests_integrations_discriminator_test_proto_init() {
	if File_tests_integrations_discriminator_test_proto != nil {
		return
	}
	file_tests_integrations_discriminator_test_proto_msgTypes[3].OneofWrappers = []any{
		(*User_Email)(nil),
		(*User_Phone)(nil),
		(*User_UserId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tests_integrations_discriminator_test_proto_rawDesc), len(file_tests_integrations_discriminator_test_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tests_integrations_discriminator_test_proto_goTypes,
		DependencyIndexes: file_tests_integrations_discriminator_test_proto_depIdxs,
		EnumInfos:         file_tests_integrations_discriminator_test_proto_enumTypes,
		MessageInfos:      file_tests_integrations_discriminator_test_proto_msgTypes,
	}.Build()
	File_tests_integrations_discriminator_test_proto = out.File
	file_tests_integrations_discriminator_test_proto_goTypes = nil
	file_tests_integrations_discriminator_test_proto_depIdxs = nil
}
