// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: test/crf/test.proto

package crf

import (
	_ "github.com/yaroher/protoc-gen-go-plain/goplain"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_test_crf_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_test_crf_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_test_crf_test_proto_rawDescGZIP(), []int{0}
}

func (x *File) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type FileRename struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *File                  `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRename) Reset() {
	*x = FileRename{}
	mi := &file_test_crf_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRename) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRename) ProtoMessage() {}

func (x *FileRename) ProtoReflect() protoreflect.Message {
	mi := &file_test_crf_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRename.ProtoReflect.Descriptor instead.
func (*FileRename) Descriptor() ([]byte, []int) {
	return file_test_crf_test_proto_rawDescGZIP(), []int{1}
}

func (x *FileRename) GetFile() *File {
	if x != nil {
		return x.File
	}
	return nil
}

type FileCreate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *File                  `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileCreate) Reset() {
	*x = FileCreate{}
	mi := &file_test_crf_test_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileCreate) ProtoMessage() {}

func (x *FileCreate) ProtoReflect() protoreflect.Message {
	mi := &file_test_crf_test_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileCreate.ProtoReflect.Descriptor instead.
func (*FileCreate) Descriptor() ([]byte, []int) {
	return file_test_crf_test_proto_rawDescGZIP(), []int{2}
}

func (x *FileCreate) GetFile() *File {
	if x != nil {
		return x.File
	}
	return nil
}

type Process struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *File                  `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Process) Reset() {
	*x = Process{}
	mi := &file_test_crf_test_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Process) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Process) ProtoMessage() {}

func (x *Process) ProtoReflect() protoreflect.Message {
	mi := &file_test_crf_test_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Process.ProtoReflect.Descriptor instead.
func (*Process) Descriptor() ([]byte, []int) {
	return file_test_crf_test_proto_rawDescGZIP(), []int{3}
}

func (x *Process) GetFile() *File {
	if x != nil {
		return x.File
	}
	return nil
}

type EventData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to PlatformEvent:
	//
	//	*EventData_FileRename
	//	*EventData_FileCreate
	//	*EventData_OtherEvent
	PlatformEvent isEventData_PlatformEvent `protobuf_oneof:"platform_event"`
	// Types that are valid to be assigned to NonPlatformEvent:
	//
	//	*EventData_CustomEvent
	//	*EventData_File
	NonPlatformEvent isEventData_NonPlatformEvent `protobuf_oneof:"non_platform_event"`
	// Types that are valid to be assigned to NoRemovedOneof:
	//
	//	*EventData_NoRemove
	//	*EventData_NotRemovedFile
	NoRemovedOneof isEventData_NoRemovedOneof `protobuf_oneof:"no_removed_oneof"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EventData) Reset() {
	*x = EventData{}
	mi := &file_test_crf_test_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventData) ProtoMessage() {}

func (x *EventData) ProtoReflect() protoreflect.Message {
	mi := &file_test_crf_test_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventData.ProtoReflect.Descriptor instead.
func (*EventData) Descriptor() ([]byte, []int) {
	return file_test_crf_test_proto_rawDescGZIP(), []int{4}
}

func (x *EventData) GetPlatformEvent() isEventData_PlatformEvent {
	if x != nil {
		return x.PlatformEvent
	}
	return nil
}

func (x *EventData) GetFileRename() *FileRename {
	if x != nil {
		if x, ok := x.PlatformEvent.(*EventData_FileRename); ok {
			return x.FileRename
		}
	}
	return nil
}

func (x *EventData) GetFileCreate() *FileCreate {
	if x != nil {
		if x, ok := x.PlatformEvent.(*EventData_FileCreate); ok {
			return x.FileCreate
		}
	}
	return nil
}

func (x *EventData) GetOtherEvent() string {
	if x != nil {
		if x, ok := x.PlatformEvent.(*EventData_OtherEvent); ok {
			return x.OtherEvent
		}
	}
	return ""
}

func (x *EventData) GetNonPlatformEvent() isEventData_NonPlatformEvent {
	if x != nil {
		return x.NonPlatformEvent
	}
	return nil
}

func (x *EventData) GetCustomEvent() string {
	if x != nil {
		if x, ok := x.NonPlatformEvent.(*EventData_CustomEvent); ok {
			return x.CustomEvent
		}
	}
	return ""
}

func (x *EventData) GetFile() *File {
	if x != nil {
		if x, ok := x.NonPlatformEvent.(*EventData_File); ok {
			return x.File
		}
	}
	return nil
}

func (x *EventData) GetNoRemovedOneof() isEventData_NoRemovedOneof {
	if x != nil {
		return x.NoRemovedOneof
	}
	return nil
}

func (x *EventData) GetNoRemove() string {
	if x != nil {
		if x, ok := x.NoRemovedOneof.(*EventData_NoRemove); ok {
			return x.NoRemove
		}
	}
	return ""
}

func (x *EventData) GetNotRemovedFile() *File {
	if x != nil {
		if x, ok := x.NoRemovedOneof.(*EventData_NotRemovedFile); ok {
			return x.NotRemovedFile
		}
	}
	return nil
}

type isEventData_PlatformEvent interface {
	isEventData_PlatformEvent()
}

type EventData_FileRename struct {
	FileRename *FileRename `protobuf:"bytes,1,opt,name=file_rename,json=fileRename,proto3,oneof"`
}

type EventData_FileCreate struct {
	FileCreate *FileCreate `protobuf:"bytes,2,opt,name=file_create,json=fileCreate,proto3,oneof"`
}

type EventData_OtherEvent struct {
	OtherEvent string `protobuf:"bytes,3,opt,name=other_event,json=otherEvent,proto3,oneof"`
}

func (*EventData_FileRename) isEventData_PlatformEvent() {}

func (*EventData_FileCreate) isEventData_PlatformEvent() {}

func (*EventData_OtherEvent) isEventData_PlatformEvent() {}

type isEventData_NonPlatformEvent interface {
	isEventData_NonPlatformEvent()
}

type EventData_CustomEvent struct {
	CustomEvent string `protobuf:"bytes,4,opt,name=custom_event,json=customEvent,proto3,oneof"`
}

type EventData_File struct {
	File *File `protobuf:"bytes,5,opt,name=file,proto3,oneof"`
}

func (*EventData_CustomEvent) isEventData_NonPlatformEvent() {}

func (*EventData_File) isEventData_NonPlatformEvent() {}

type isEventData_NoRemovedOneof interface {
	isEventData_NoRemovedOneof()
}

type EventData_NoRemove struct {
	NoRemove string `protobuf:"bytes,6,opt,name=no_remove,json=noRemove,proto3,oneof"`
}

type EventData_NotRemovedFile struct {
	NotRemovedFile *File `protobuf:"bytes,7,opt,name=not_removed_file,json=notRemovedFile,proto3,oneof"`
}

func (*EventData_NoRemove) isEventData_NoRemovedOneof() {}

func (*EventData_NotRemovedFile) isEventData_NoRemovedOneof() {}

type Event struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	EventId                int32                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	SomeEventStringPayload string                 `protobuf:"bytes,2,opt,name=some_event_string_payload,json=someEventStringPayload,proto3" json:"some_event_string_payload,omitempty"`
	Process                *Process               `protobuf:"bytes,3,opt,name=process,proto3" json:"process,omitempty"`
	Data                   *EventData             `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	ParentEventId          string                 `protobuf:"bytes,5,opt,name=parent_event_id,json=parentEventId,proto3" json:"parent_event_id,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_test_crf_test_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_test_crf_test_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_test_crf_test_proto_rawDescGZIP(), []int{5}
}

func (x *Event) GetEventId() int32 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *Event) GetSomeEventStringPayload() string {
	if x != nil {
		return x.SomeEventStringPayload
	}
	return ""
}

func (x *Event) GetProcess() *Process {
	if x != nil {
		return x.Process
	}
	return nil
}

func (x *Event) GetData() *EventData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Event) GetParentEventId() string {
	if x != nil {
		return x.ParentEventId
	}
	return ""
}

var File_test_crf_test_proto protoreflect.FileDescriptor

const file_test_crf_test_proto_rawDesc = "" +
	"\n" +
	"\x13test/crf/test.proto\x12\atestcrf\x1a\x15goplain/goplain.proto\"\x1a\n" +
	"\x04File\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"?\n" +
	"\n" +
	"FileRename\x12)\n" +
	"\x04file\x18\x01 \x01(\v2\r.testcrf.FileB\x06\x82\xa6\x1d\x02 \x01R\x04file:\x06\x82\xa6\x1d\x02\b\x01\"?\n" +
	"\n" +
	"FileCreate\x12)\n" +
	"\x04file\x18\x01 \x01(\v2\r.testcrf.FileB\x06\x82\xa6\x1d\x02 \x01R\x04file:\x06\x82\xa6\x1d\x02\b\x01\"4\n" +
	"\aProcess\x12!\n" +
	"\x04file\x18\x01 \x01(\v2\r.testcrf.FileR\x04file:\x06\x82\xa6\x1d\x02\b\x01\"\xbe\x03\n" +
	"\tEventData\x12>\n" +
	"\vfile_rename\x18\x01 \x01(\v2\x13.testcrf.FileRenameB\x06\x82\xa6\x1d\x02 \x01H\x00R\n" +
	"fileRename\x12>\n" +
	"\vfile_create\x18\x02 \x01(\v2\x13.testcrf.FileCreateB\x06\x82\xa6\x1d\x02 \x01H\x00R\n" +
	"fileCreate\x12)\n" +
	"\vother_event\x18\x03 \x01(\tB\x06\x82\xa6\x1d\x02 \x01H\x00R\n" +
	"otherEvent\x12#\n" +
	"\fcustom_event\x18\x04 \x01(\tH\x01R\vcustomEvent\x12+\n" +
	"\x04file\x18\x05 \x01(\v2\r.testcrf.FileB\x06\x82\xa6\x1d\x02 \x01H\x01R\x04file\x12\x1d\n" +
	"\tno_remove\x18\x06 \x01(\tH\x02R\bnoRemove\x12A\n" +
	"\x10not_removed_file\x18\a \x01(\v2\r.testcrf.FileB\x06\x82\xa6\x1d\x02 \x01H\x02R\x0enotRemovedFile:\x06\x82\xa6\x1d\x02\b\x01B\x18\n" +
	"\x0eplatform_event\x12\x06\x82\xb5\x18\x02\b\x01B\x1c\n" +
	"\x12non_platform_event\x12\x06\x82\xb5\x18\x02\x10\x01B\x12\n" +
	"\x10no_removed_oneof\"\xa7\x02\n" +
	"\x05Event\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x05R\aeventId\x12_\n" +
	"\x19some_event_string_payload\x18\x02 \x01(\tB$\x82\xa6\x1d \n" +
	"\x1e\n" +
	"\x04UUID\x12\x16github.com/google/uuidR\x16someEventStringPayload\x12*\n" +
	"\aprocess\x18\x03 \x01(\v2\x10.testcrf.ProcessR\aprocess\x12.\n" +
	"\x04data\x18\x04 \x01(\v2\x12.testcrf.EventDataB\x06\x82\xa6\x1d\x02 \x01R\x04data\x12&\n" +
	"\x0fparent_event_id\x18\x05 \x01(\tR\rparentEventId:\x1e\x82\xa6\x1d\x1a\b\x01\x1a\x16\b\t\"\x12event_virtual_typeB`\x82\xa6\x1d+\x12)\n" +
	"\vVirtualType\x12\x1a\b\v\x10\x01\x18\x01\"\x04file2\ftestcrf.FileZ/github.com/yaroher/protoc-gen-go-plain/test/crfb\x06proto3"

var (
	file_test_crf_test_proto_rawDescOnce sync.Once
	file_test_crf_test_proto_rawDescData []byte
)

func file_test_crf_test_proto_rawDescGZIP() []byte {
	file_test_crf_test_proto_rawDescOnce.Do(func() {
		file_test_crf_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_crf_test_proto_rawDesc), len(file_test_crf_test_proto_rawDesc)))
	})
	return file_test_crf_test_proto_rawDescData
}

var file_test_crf_test_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_test_crf_test_proto_goTypes = []any{
	(*File)(nil),       // 0: testcrf.File
	(*FileRename)(nil), // 1: testcrf.FileRename
	(*FileCreate)(nil), // 2: testcrf.FileCreate
	(*Process)(nil),    // 3: testcrf.Process
	(*EventData)(nil),  // 4: testcrf.EventData
	(*Event)(nil),      // 5: testcrf.Event
}
var file_test_crf_test_proto_depIdxs = []int32{
	0, // 0: testcrf.FileRename.file:type_name -> testcrf.File
	0, // 1: testcrf.FileCreate.file:type_name -> testcrf.File
	0, // 2: testcrf.Process.file:type_name -> testcrf.File
	1, // 3: testcrf.EventData.file_rename:type_name -> testcrf.FileRename
	2, // 4: testcrf.EventData.file_create:type_name -> testcrf.FileCreate
	0, // 5: testcrf.EventData.file:type_name -> testcrf.File
	0, // 6: testcrf.EventData.not_removed_file:type_name -> testcrf.File
	3, // 7: testcrf.Event.process:type_name -> testcrf.Process
	4, // 8: testcrf.Event.data:type_name -> testcrf.EventData
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_test_crf_test_proto_init() }
func file_test_crf_test_proto_init() {
	if File_test_crf_test_proto != nil {
		return
	}
	file_test_crf_test_proto_msgTypes[4].OneofWrappers = []any{
		(*EventData_FileRename)(nil),
		(*EventData_FileCreate)(nil),
		(*EventData_OtherEvent)(nil),
		(*EventData_CustomEvent)(nil),
		(*EventData_File)(nil),
		(*EventData_NoRemove)(nil),
		(*EventData_NotRemovedFile)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_crf_test_proto_rawDesc), len(file_test_crf_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_crf_test_proto_goTypes,
		DependencyIndexes: file_test_crf_test_proto_depIdxs,
		MessageInfos:      file_test_crf_test_proto_msgTypes,
	}.Build()
	File_test_crf_test_proto = out.File
	file_test_crf_test_proto_goTypes = nil
	file_test_crf_test_proto_depIdxs = nil
}
