// Code generated by protoc-gen-go-plain. DO NOT EDIT.

package crf

import (
	"github.com/google/uuid"
)

type VirtualTypePlain struct {
	File *FilePlain `json:"file,omitempty"`
}

type EventPlain struct {
	PathCRF                     string        `json:"pathCRF"`
	EventVirtualType            string        `json:"eventVirtualType"`
	Process                     *ProcessPlain `json:"process,omitempty"`
	NonPlatformEventCustomEvent *string       `json:"nonPlatformEventCustomEvent,omitempty"`
	ParentEventId               string        `json:"parentEventId"`
	EventId                     int32         `json:"eventId"`
	SomeEventStringPayload      uuid.UUID     `json:"someEventStringPayload"`
	OtherEvent                  *string       `json:"otherEvent,omitempty"`
	NonPlatformEventPath        string        `json:"nonPlatformEventPath"`
	Path                        *string       `json:"path,omitempty"`
}

type EventDataPlain struct {
	OtherEvent                  *string                    `json:"otherEvent,omitempty"`
	NonPlatformEventCustomEvent *string                    `json:"nonPlatformEventCustomEvent,omitempty"`
	NonPlatformEventPath        string                     `json:"nonPlatformEventPath"`
	Path                        *string                    `json:"path,omitempty"`
	PathCRF                     string                     `json:"pathCRF"`
	NoRemovedOneof              isEventData_NoRemovedOneof `json:"noRemovedOneof"`
}

type FilePlain struct {
	Path string `json:"path"`
}

type FileCreatePlain struct {
	Path string `json:"path"`
}

type FileRenamePlain struct {
	Path string `json:"path"`
}

type ProcessPlain struct {
	File *FilePlain `json:"file,omitempty"`
}
