// Code generated by protoc-gen-go-plain. DO NOT EDIT.

package crf

import (
	"fmt"
	"github.com/google/uuid"
	"github.com/yaroher/protoc-gen-go-plain/cast"
	"strings"
)

func parseCRFPath(s string) []string {
	if s == "" {
		return nil
	}
	parts := strings.Split(s, "/")
	result := make([]string, 0, len(parts))
	for _, p := range parts {
		if p == "" {
			continue
		}
		if idx := strings.Index(p, "?"); idx >= 0 {
			p = p[:idx]
		}
		result = append(result, p)
	}
	return result
}

func (x *EventPlain) IntoPb(casterUuidUuidToString cast.Caster[uuid.UUID, string]) *Event {
	if x == nil {
		return nil
	}
	out := &Event{}
	// skip invalid path for EventVirtualType
	if x.Process != nil {
		out.Process = x.Process.IntoPb()
	}
	if x.PathCRF != "" {
		_crfPath := strings.Join(parseCRFPath(x.PathCRF), "/")
		switch _crfPath {
		case "data/file_rename/file/path":
			if x.Path != nil {
				if out.Data == nil {
					out.Data = &EventData{}
				}
				var _oneofFileRename1 *FileRename
				if v, ok := out.Data.PlatformEvent.(*EventData_FileRename); ok {
					_oneofFileRename1 = v.FileRename
				}
				if _oneofFileRename1 == nil {
					_oneofFileRename1 = &FileRename{}
					out.Data.PlatformEvent = &EventData_FileRename{FileRename: _oneofFileRename1}
				}
				if _oneofFileRename1.File == nil {
					_oneofFileRename1.File = &File{}
				}
				_oneofFileRename1.File.Path = *x.Path
			}
		}
	} else {
		if x.Path != nil {
			if out.Data == nil {
				out.Data = &EventData{}
			}
			var _oneofFileRename1 *FileRename
			if v, ok := out.Data.PlatformEvent.(*EventData_FileRename); ok {
				_oneofFileRename1 = v.FileRename
			}
			if _oneofFileRename1 == nil {
				_oneofFileRename1 = &FileRename{}
				out.Data.PlatformEvent = &EventData_FileRename{FileRename: _oneofFileRename1}
			}
			if _oneofFileRename1.File == nil {
				_oneofFileRename1.File = &File{}
			}
			_oneofFileRename1.File.Path = *x.Path
		}
	}
	// skip invalid path for PathCRF
	if x.OtherEvent != nil {
		if out.Data == nil {
			out.Data = &EventData{}
		}
		out.Data.PlatformEvent = &EventData_OtherEvent{OtherEvent: *x.OtherEvent}
	}
	if x.NonPlatformEventCustomEvent != nil {
		if out.Data == nil {
			out.Data = &EventData{}
		}
		out.Data.NonPlatformEvent = &EventData_CustomEvent{CustomEvent: *x.NonPlatformEventCustomEvent}
	}
	out.ParentEventId = x.ParentEventId
	out.EventId = x.EventId
	if casterUuidUuidToString == nil {
		panic("missing caster: casterUuidUuidToString")
	}
	val := casterUuidUuidToString.Cast(x.SomeEventStringPayload)
	out.SomeEventStringPayload = val
	if out.Data == nil {
		out.Data = &EventData{}
	}
	var _oneofFile1 *File
	if v, ok := out.Data.NonPlatformEvent.(*EventData_File); ok {
		_oneofFile1 = v.File
	}
	if _oneofFile1 == nil {
		_oneofFile1 = &File{}
		out.Data.NonPlatformEvent = &EventData_File{File: _oneofFile1}
	}
	_oneofFile1.Path = x.NonPlatformEventPath
	return out
}

func (x *Event) IntoPlain(casterStringToUuidUuid cast.Caster[string, uuid.UUID]) *EventPlain {
	if x == nil {
		return nil
	}
	out := &EventPlain{}
	// skip invalid path for EventVirtualType
	if x.Process != nil {
		out.Process = x.Process.IntoPlain()
	}
	// CRF paths
	if x.Data != nil {
		if _oneofFileRename1, ok := x.Data.PlatformEvent.(*EventData_FileRename); ok {
			if _oneofFileRename1.FileRename != nil {
				if _oneofFileRename1.FileRename.File != nil {
					if _oneofFileRename1.FileRename.File.Path != "" {
						_valPath := _oneofFileRename1.FileRename.File.Path
						out.Path = &_valPath
						out.PathCRF = "data/file_rename/file/path"
					}
				}
			}
		}
	}
	// skip invalid path for PathCRF
	if x.Data != nil {
		if _oneofOtherEvent1, ok := x.Data.PlatformEvent.(*EventData_OtherEvent); ok {
			_valOtherEvent := _oneofOtherEvent1.OtherEvent
			out.OtherEvent = &_valOtherEvent
		}
	}
	if x.Data != nil {
		if _oneofCustomEvent1, ok := x.Data.NonPlatformEvent.(*EventData_CustomEvent); ok {
			_valNonPlatformEventCustomEvent := _oneofCustomEvent1.CustomEvent
			out.NonPlatformEventCustomEvent = &_valNonPlatformEventCustomEvent
		}
	}
	out.ParentEventId = x.ParentEventId
	out.EventId = x.EventId
	if x.SomeEventStringPayload != "" {
		if casterStringToUuidUuid == nil {
			panic("missing caster: casterStringToUuidUuid")
		}
		out.SomeEventStringPayload = casterStringToUuidUuid.Cast(x.SomeEventStringPayload)
	}
	if x.Data != nil {
		if _oneofFile1, ok := x.Data.NonPlatformEvent.(*EventData_File); ok {
			if _oneofFile1.File != nil {
				out.NonPlatformEventPath = _oneofFile1.File.Path
			}
		}
	}
	return out
}

func (x *EventPlain) IntoPbErr(casterUuidUuidToString cast.CasterErr[uuid.UUID, string]) (*Event, error) {
	if x == nil {
		return nil, nil
	}
	out := &Event{}
	// skip invalid path for EventVirtualType
	if x.Process != nil {
		mv, err := x.Process.IntoPbErr()
		if err != nil {
			return nil, err
		}
		out.Process = mv
	}
	if x.PathCRF != "" {
		_crfPath := strings.Join(parseCRFPath(x.PathCRF), "/")
		switch _crfPath {
		case "data/file_rename/file/path":
			if x.Path != nil {
				if out.Data == nil {
					out.Data = &EventData{}
				}
				var _oneofFileRename1 *FileRename
				if v, ok := out.Data.PlatformEvent.(*EventData_FileRename); ok {
					_oneofFileRename1 = v.FileRename
				}
				if _oneofFileRename1 == nil {
					_oneofFileRename1 = &FileRename{}
					out.Data.PlatformEvent = &EventData_FileRename{FileRename: _oneofFileRename1}
				}
				if _oneofFileRename1.File == nil {
					_oneofFileRename1.File = &File{}
				}
				_oneofFileRename1.File.Path = *x.Path
			}
		}
	} else {
		if x.Path != nil {
			if out.Data == nil {
				out.Data = &EventData{}
			}
			var _oneofFileRename1 *FileRename
			if v, ok := out.Data.PlatformEvent.(*EventData_FileRename); ok {
				_oneofFileRename1 = v.FileRename
			}
			if _oneofFileRename1 == nil {
				_oneofFileRename1 = &FileRename{}
				out.Data.PlatformEvent = &EventData_FileRename{FileRename: _oneofFileRename1}
			}
			if _oneofFileRename1.File == nil {
				_oneofFileRename1.File = &File{}
			}
			_oneofFileRename1.File.Path = *x.Path
		}
	}
	// skip invalid path for PathCRF
	if x.OtherEvent != nil {
		if out.Data == nil {
			out.Data = &EventData{}
		}
		out.Data.PlatformEvent = &EventData_OtherEvent{OtherEvent: *x.OtherEvent}
	}
	if x.NonPlatformEventCustomEvent != nil {
		if out.Data == nil {
			out.Data = &EventData{}
		}
		out.Data.NonPlatformEvent = &EventData_CustomEvent{CustomEvent: *x.NonPlatformEventCustomEvent}
	}
	out.ParentEventId = x.ParentEventId
	out.EventId = x.EventId
	if casterUuidUuidToString == nil {
		return nil, fmt.Errorf("missing caster: casterUuidUuidToString")
	}
	val, err := casterUuidUuidToString.CastErr(x.SomeEventStringPayload)
	if err != nil {
		return nil, err
	}
	out.SomeEventStringPayload = val
	if out.Data == nil {
		out.Data = &EventData{}
	}
	var _oneofFile1 *File
	if v, ok := out.Data.NonPlatformEvent.(*EventData_File); ok {
		_oneofFile1 = v.File
	}
	if _oneofFile1 == nil {
		_oneofFile1 = &File{}
		out.Data.NonPlatformEvent = &EventData_File{File: _oneofFile1}
	}
	_oneofFile1.Path = x.NonPlatformEventPath
	return out, nil
}

func (x *Event) IntoPlainErr(casterStringToUuidUuid cast.CasterErr[string, uuid.UUID]) (*EventPlain, error) {
	if x == nil {
		return nil, nil
	}
	out := &EventPlain{}
	// skip invalid path for EventVirtualType
	if x.Process != nil {
		plainVal, err := x.Process.IntoPlainErr()
		if err != nil {
			return nil, err
		}
		out.Process = plainVal
	}
	// CRF paths
	if x.Data != nil {
		if _oneofFileRename1, ok := x.Data.PlatformEvent.(*EventData_FileRename); ok {
			if _oneofFileRename1.FileRename != nil {
				if _oneofFileRename1.FileRename.File != nil {
					if _oneofFileRename1.FileRename.File.Path != "" {
						_valPath := _oneofFileRename1.FileRename.File.Path
						out.Path = &_valPath
						out.PathCRF = "data/file_rename/file/path"
					}
				}
			}
		}
	}
	// skip invalid path for PathCRF
	if x.Data != nil {
		if _oneofOtherEvent1, ok := x.Data.PlatformEvent.(*EventData_OtherEvent); ok {
			_valOtherEvent := _oneofOtherEvent1.OtherEvent
			out.OtherEvent = &_valOtherEvent
		}
	}
	if x.Data != nil {
		if _oneofCustomEvent1, ok := x.Data.NonPlatformEvent.(*EventData_CustomEvent); ok {
			_valNonPlatformEventCustomEvent := _oneofCustomEvent1.CustomEvent
			out.NonPlatformEventCustomEvent = &_valNonPlatformEventCustomEvent
		}
	}
	out.ParentEventId = x.ParentEventId
	out.EventId = x.EventId
	if x.SomeEventStringPayload != "" {
		if casterStringToUuidUuid == nil {
			return nil, fmt.Errorf("missing caster: casterStringToUuidUuid")
		}
		val, err := casterStringToUuidUuid.CastErr(x.SomeEventStringPayload)
		if err != nil {
			return nil, err
		}
		out.SomeEventStringPayload = val
	}
	if x.Data != nil {
		if _oneofFile1, ok := x.Data.NonPlatformEvent.(*EventData_File); ok {
			if _oneofFile1.File != nil {
				out.NonPlatformEventPath = _oneofFile1.File.Path
			}
		}
	}
	return out, nil
}

func (x *EventDataPlain) IntoPb() *EventData {
	if x == nil {
		return nil
	}
	out := &EventData{}
	if x.PathCRF != "" {
		_crfPath := strings.Join(parseCRFPath(x.PathCRF), "/")
		switch _crfPath {
		case "file_rename/file/path":
			if x.Path != nil {
				var _oneofFileRename0 *FileRename
				if v, ok := out.PlatformEvent.(*EventData_FileRename); ok {
					_oneofFileRename0 = v.FileRename
				}
				if _oneofFileRename0 == nil {
					_oneofFileRename0 = &FileRename{}
					out.PlatformEvent = &EventData_FileRename{FileRename: _oneofFileRename0}
				}
				if _oneofFileRename0.File == nil {
					_oneofFileRename0.File = &File{}
				}
				_oneofFileRename0.File.Path = *x.Path
			}
		case "file_create/file/path":
			if x.Path != nil {
				var _oneofFileCreate0 *FileCreate
				if v, ok := out.PlatformEvent.(*EventData_FileCreate); ok {
					_oneofFileCreate0 = v.FileCreate
				}
				if _oneofFileCreate0 == nil {
					_oneofFileCreate0 = &FileCreate{}
					out.PlatformEvent = &EventData_FileCreate{FileCreate: _oneofFileCreate0}
				}
				if _oneofFileCreate0.File == nil {
					_oneofFileCreate0.File = &File{}
				}
				_oneofFileCreate0.File.Path = *x.Path
			}
		}
	} else {
		if x.Path != nil {
			var _oneofFileRename0 *FileRename
			if v, ok := out.PlatformEvent.(*EventData_FileRename); ok {
				_oneofFileRename0 = v.FileRename
			}
			if _oneofFileRename0 == nil {
				_oneofFileRename0 = &FileRename{}
				out.PlatformEvent = &EventData_FileRename{FileRename: _oneofFileRename0}
			}
			if _oneofFileRename0.File == nil {
				_oneofFileRename0.File = &File{}
			}
			_oneofFileRename0.File.Path = *x.Path
		}
	}
	// skip invalid path for PathCRF
	if x.OtherEvent != nil {
		out.PlatformEvent = &EventData_OtherEvent{OtherEvent: *x.OtherEvent}
	}
	if x.NonPlatformEventCustomEvent != nil {
		out.NonPlatformEvent = &EventData_CustomEvent{CustomEvent: *x.NonPlatformEventCustomEvent}
	}
	var _oneofFile0 *File
	if v, ok := out.NonPlatformEvent.(*EventData_File); ok {
		_oneofFile0 = v.File
	}
	if _oneofFile0 == nil {
		_oneofFile0 = &File{}
		out.NonPlatformEvent = &EventData_File{File: _oneofFile0}
	}
	_oneofFile0.Path = x.NonPlatformEventPath
	out.NoRemovedOneof = x.NoRemovedOneof
	return out
}

func (x *EventData) IntoPlain() *EventDataPlain {
	if x == nil {
		return nil
	}
	out := &EventDataPlain{}
	// CRF paths
	if _oneofFileRename0, ok := x.PlatformEvent.(*EventData_FileRename); ok {
		if _oneofFileRename0.FileRename != nil {
			if _oneofFileRename0.FileRename.File != nil {
				if _oneofFileRename0.FileRename.File.Path != "" {
					_valPath := _oneofFileRename0.FileRename.File.Path
					out.Path = &_valPath
					out.PathCRF = "file_rename/file/path"
				}
			}
		}
	}
	if _oneofFileCreate0, ok := x.PlatformEvent.(*EventData_FileCreate); ok {
		if _oneofFileCreate0.FileCreate != nil {
			if _oneofFileCreate0.FileCreate.File != nil {
				if _oneofFileCreate0.FileCreate.File.Path != "" {
					_valPath := _oneofFileCreate0.FileCreate.File.Path
					out.Path = &_valPath
					out.PathCRF = "file_create/file/path"
				}
			}
		}
	}
	// skip invalid path for PathCRF
	if _oneofOtherEvent0, ok := x.PlatformEvent.(*EventData_OtherEvent); ok {
		_valOtherEvent := _oneofOtherEvent0.OtherEvent
		out.OtherEvent = &_valOtherEvent
	}
	if _oneofCustomEvent0, ok := x.NonPlatformEvent.(*EventData_CustomEvent); ok {
		_valNonPlatformEventCustomEvent := _oneofCustomEvent0.CustomEvent
		out.NonPlatformEventCustomEvent = &_valNonPlatformEventCustomEvent
	}
	if _oneofFile0, ok := x.NonPlatformEvent.(*EventData_File); ok {
		if _oneofFile0.File != nil {
			out.NonPlatformEventPath = _oneofFile0.File.Path
		}
	}
	out.NoRemovedOneof = x.NoRemovedOneof
	return out
}

func (x *EventDataPlain) IntoPbErr() (*EventData, error) {
	if x == nil {
		return nil, nil
	}
	out := &EventData{}
	if x.PathCRF != "" {
		_crfPath := strings.Join(parseCRFPath(x.PathCRF), "/")
		switch _crfPath {
		case "file_rename/file/path":
			if x.Path != nil {
				var _oneofFileRename0 *FileRename
				if v, ok := out.PlatformEvent.(*EventData_FileRename); ok {
					_oneofFileRename0 = v.FileRename
				}
				if _oneofFileRename0 == nil {
					_oneofFileRename0 = &FileRename{}
					out.PlatformEvent = &EventData_FileRename{FileRename: _oneofFileRename0}
				}
				if _oneofFileRename0.File == nil {
					_oneofFileRename0.File = &File{}
				}
				_oneofFileRename0.File.Path = *x.Path
			}
		case "file_create/file/path":
			if x.Path != nil {
				var _oneofFileCreate0 *FileCreate
				if v, ok := out.PlatformEvent.(*EventData_FileCreate); ok {
					_oneofFileCreate0 = v.FileCreate
				}
				if _oneofFileCreate0 == nil {
					_oneofFileCreate0 = &FileCreate{}
					out.PlatformEvent = &EventData_FileCreate{FileCreate: _oneofFileCreate0}
				}
				if _oneofFileCreate0.File == nil {
					_oneofFileCreate0.File = &File{}
				}
				_oneofFileCreate0.File.Path = *x.Path
			}
		}
	} else {
		if x.Path != nil {
			var _oneofFileRename0 *FileRename
			if v, ok := out.PlatformEvent.(*EventData_FileRename); ok {
				_oneofFileRename0 = v.FileRename
			}
			if _oneofFileRename0 == nil {
				_oneofFileRename0 = &FileRename{}
				out.PlatformEvent = &EventData_FileRename{FileRename: _oneofFileRename0}
			}
			if _oneofFileRename0.File == nil {
				_oneofFileRename0.File = &File{}
			}
			_oneofFileRename0.File.Path = *x.Path
		}
	}
	// skip invalid path for PathCRF
	if x.OtherEvent != nil {
		out.PlatformEvent = &EventData_OtherEvent{OtherEvent: *x.OtherEvent}
	}
	if x.NonPlatformEventCustomEvent != nil {
		out.NonPlatformEvent = &EventData_CustomEvent{CustomEvent: *x.NonPlatformEventCustomEvent}
	}
	var _oneofFile0 *File
	if v, ok := out.NonPlatformEvent.(*EventData_File); ok {
		_oneofFile0 = v.File
	}
	if _oneofFile0 == nil {
		_oneofFile0 = &File{}
		out.NonPlatformEvent = &EventData_File{File: _oneofFile0}
	}
	_oneofFile0.Path = x.NonPlatformEventPath
	out.NoRemovedOneof = x.NoRemovedOneof
	return out, nil
}

func (x *EventData) IntoPlainErr() (*EventDataPlain, error) {
	if x == nil {
		return nil, nil
	}
	out := &EventDataPlain{}
	// CRF paths
	if _oneofFileRename0, ok := x.PlatformEvent.(*EventData_FileRename); ok {
		if _oneofFileRename0.FileRename != nil {
			if _oneofFileRename0.FileRename.File != nil {
				if _oneofFileRename0.FileRename.File.Path != "" {
					_valPath := _oneofFileRename0.FileRename.File.Path
					out.Path = &_valPath
					out.PathCRF = "file_rename/file/path"
				}
			}
		}
	}
	if _oneofFileCreate0, ok := x.PlatformEvent.(*EventData_FileCreate); ok {
		if _oneofFileCreate0.FileCreate != nil {
			if _oneofFileCreate0.FileCreate.File != nil {
				if _oneofFileCreate0.FileCreate.File.Path != "" {
					_valPath := _oneofFileCreate0.FileCreate.File.Path
					out.Path = &_valPath
					out.PathCRF = "file_create/file/path"
				}
			}
		}
	}
	// skip invalid path for PathCRF
	if _oneofOtherEvent0, ok := x.PlatformEvent.(*EventData_OtherEvent); ok {
		_valOtherEvent := _oneofOtherEvent0.OtherEvent
		out.OtherEvent = &_valOtherEvent
	}
	if _oneofCustomEvent0, ok := x.NonPlatformEvent.(*EventData_CustomEvent); ok {
		_valNonPlatformEventCustomEvent := _oneofCustomEvent0.CustomEvent
		out.NonPlatformEventCustomEvent = &_valNonPlatformEventCustomEvent
	}
	if _oneofFile0, ok := x.NonPlatformEvent.(*EventData_File); ok {
		if _oneofFile0.File != nil {
			out.NonPlatformEventPath = _oneofFile0.File.Path
		}
	}
	out.NoRemovedOneof = x.NoRemovedOneof
	return out, nil
}

func (x *FilePlain) IntoPb() *File {
	if x == nil {
		return nil
	}
	out := &File{}
	out.Path = x.Path
	return out
}

func (x *File) IntoPlain() *FilePlain {
	if x == nil {
		return nil
	}
	out := &FilePlain{}
	out.Path = x.Path
	return out
}

func (x *FilePlain) IntoPbErr() (*File, error) {
	if x == nil {
		return nil, nil
	}
	out := &File{}
	out.Path = x.Path
	return out, nil
}

func (x *File) IntoPlainErr() (*FilePlain, error) {
	if x == nil {
		return nil, nil
	}
	out := &FilePlain{}
	out.Path = x.Path
	return out, nil
}

func (x *FileCreatePlain) IntoPb() *FileCreate {
	if x == nil {
		return nil
	}
	out := &FileCreate{}
	if out.File == nil {
		out.File = &File{}
	}
	out.File.Path = x.Path
	return out
}

func (x *FileCreate) IntoPlain() *FileCreatePlain {
	if x == nil {
		return nil
	}
	out := &FileCreatePlain{}
	if x.File != nil {
		out.Path = x.File.Path
	}
	return out
}

func (x *FileCreatePlain) IntoPbErr() (*FileCreate, error) {
	if x == nil {
		return nil, nil
	}
	out := &FileCreate{}
	if out.File == nil {
		out.File = &File{}
	}
	out.File.Path = x.Path
	return out, nil
}

func (x *FileCreate) IntoPlainErr() (*FileCreatePlain, error) {
	if x == nil {
		return nil, nil
	}
	out := &FileCreatePlain{}
	if x.File != nil {
		out.Path = x.File.Path
	}
	return out, nil
}

func (x *FileRenamePlain) IntoPb() *FileRename {
	if x == nil {
		return nil
	}
	out := &FileRename{}
	if out.File == nil {
		out.File = &File{}
	}
	out.File.Path = x.Path
	return out
}

func (x *FileRename) IntoPlain() *FileRenamePlain {
	if x == nil {
		return nil
	}
	out := &FileRenamePlain{}
	if x.File != nil {
		out.Path = x.File.Path
	}
	return out
}

func (x *FileRenamePlain) IntoPbErr() (*FileRename, error) {
	if x == nil {
		return nil, nil
	}
	out := &FileRename{}
	if out.File == nil {
		out.File = &File{}
	}
	out.File.Path = x.Path
	return out, nil
}

func (x *FileRename) IntoPlainErr() (*FileRenamePlain, error) {
	if x == nil {
		return nil, nil
	}
	out := &FileRenamePlain{}
	if x.File != nil {
		out.Path = x.File.Path
	}
	return out, nil
}

func (x *ProcessPlain) IntoPb() *Process {
	if x == nil {
		return nil
	}
	out := &Process{}
	if x.File != nil {
		out.File = x.File.IntoPb()
	}
	return out
}

func (x *Process) IntoPlain() *ProcessPlain {
	if x == nil {
		return nil
	}
	out := &ProcessPlain{}
	if x.File != nil {
		out.File = x.File.IntoPlain()
	}
	return out
}

func (x *ProcessPlain) IntoPbErr() (*Process, error) {
	if x == nil {
		return nil, nil
	}
	out := &Process{}
	if x.File != nil {
		mv, err := x.File.IntoPbErr()
		if err != nil {
			return nil, err
		}
		out.File = mv
	}
	return out, nil
}

func (x *Process) IntoPlainErr() (*ProcessPlain, error) {
	if x == nil {
		return nil, nil
	}
	out := &ProcessPlain{}
	if x.File != nil {
		plainVal, err := x.File.IntoPlainErr()
		if err != nil {
			return nil, err
		}
		out.File = plainVal
	}
	return out, nil
}
