// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: tests/integrations/override_type/test.proto

package override_type

import (
	_ "github.com/yaroher/protoc-gen-go-plain/goplain"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawId         string                 `protobuf:"bytes,1,opt,name=raw_id,json=rawId,proto3" json:"raw_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_tests_integrations_override_type_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_tests_integrations_override_type_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_tests_integrations_override_type_test_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetRawId() string {
	if x != nil {
		return x.RawId
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_tests_integrations_override_type_test_proto protoreflect.FileDescriptor

const file_tests_integrations_override_type_test_proto_rawDesc = "" +
	"\n" +
	"+tests/integrations/override_type/test.proto\x12\x12test.override_type\x1a\x15goplain/goplain.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9a\x01\n" +
	"\x04User\x12;\n" +
	"\x06raw_id\x18\x01 \x01(\tB$\x82\xa6\x1d \n" +
	"\x1e\n" +
	"\x04UUID\x12\x16github.com/google/uuidR\x05rawId\x12M\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB\x12\x82\xa6\x1d\x0e\n" +
	"\f\n" +
	"\x04Time\x12\x04timeR\tcreatedAt:\x06\x82\xa6\x1d\x02\b\x01BWZUgithub.com/yaroher/protoc-gen-go-plain/tests/integrations/override_type;override_typeb\x06proto3"

var (
	file_tests_integrations_override_type_test_proto_rawDescOnce sync.Once
	file_tests_integrations_override_type_test_proto_rawDescData []byte
)

func file_tests_integrations_override_type_test_proto_rawDescGZIP() []byte {
	file_tests_integrations_override_type_test_proto_rawDescOnce.Do(func() {
		file_tests_integrations_override_type_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tests_integrations_override_type_test_proto_rawDesc), len(file_tests_integrations_override_type_test_proto_rawDesc)))
	})
	return file_tests_integrations_override_type_test_proto_rawDescData
}

var file_tests_integrations_override_type_test_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tests_integrations_override_type_test_proto_goTypes = []any{
	(*User)(nil),                  // 0: test.override_type.User
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_tests_integrations_override_type_test_proto_depIdxs = []int32{
	1, // 0: test.override_type.User.created_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tests_integrations_override_type_test_proto_init() }
func file_tests_integrations_override_type_test_proto_init() {
	if File_tests_integrations_override_type_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tests_integrations_override_type_test_proto_rawDesc), len(file_tests_integrations_override_type_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tests_integrations_override_type_test_proto_goTypes,
		DependencyIndexes: file_tests_integrations_override_type_test_proto_depIdxs,
		MessageInfos:      file_tests_integrations_override_type_test_proto_msgTypes,
	}.Build()
	File_tests_integrations_override_type_test_proto = out.File
	file_tests_integrations_override_type_test_proto_goTypes = nil
	file_tests_integrations_override_type_test_proto_depIdxs = nil
}
