// Code generated by protoc-gen-go-plain. DO NOT EDIT.

package override_type

import (
	json "encoding/json"
	jx "github.com/go-faster/jx"
	uuid "github.com/google/uuid"
	cast "github.com/yaroher/protoc-gen-go-plain/cast"
	protojson "google.golang.org/protobuf/encoding/protojson"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	time "time"
)

type UserPlain struct {

	// src: .test.override_type.User.raw_id; transform: override_type
	RawId uuid.UUID
	// src: .test.override_type.User.created_at; transform: override_type
	CreatedAt time.Time
}

func (m *User) IntoPlain(rawIdCast cast.Caster[string, uuid.UUID], createdAtCast cast.Caster[*timestamppb.Timestamp, time.Time]) *UserPlain {
	if m == nil {
		return nil
	}
	return &UserPlain{
		RawId:     rawIdCast(m.GetRawId()),
		CreatedAt: createdAtCast(m.GetCreatedAt()),
	}
}

func (m *User) IntoPlainErr(rawIdCast cast.CasterErr[string, uuid.UUID], createdAtCast cast.CasterErr[*timestamppb.Timestamp, time.Time]) (*UserPlain, error) {
	if m == nil {
		return nil, nil
	}
	RawIdVal, err := rawIdCast(m.GetRawId())
	if err != nil {
		return nil, err
	}
	CreatedAtVal, err := createdAtCast(m.GetCreatedAt())
	if err != nil {
		return nil, err
	}
	return &UserPlain{
		RawId:     RawIdVal,
		CreatedAt: CreatedAtVal,
	}, nil
}

func (m *UserPlain) IntoPb(rawIdCast cast.Caster[uuid.UUID, string], createdAtCast cast.Caster[time.Time, *timestamppb.Timestamp]) *User {
	if m == nil {
		return nil
	}
	return &User{
		RawId:     rawIdCast(m.RawId),
		CreatedAt: createdAtCast(m.CreatedAt),
	}
}

func (m *UserPlain) IntoPbErr(rawIdCast cast.CasterErr[uuid.UUID, string], createdAtCast cast.CasterErr[time.Time, *timestamppb.Timestamp]) (*User, error) {
	if m == nil {
		return nil, nil
	}
	RawIdVal, err := rawIdCast(m.RawId)
	if err != nil {
		return nil, err
	}
	CreatedAtVal, err := createdAtCast(m.CreatedAt)
	if err != nil {
		return nil, err
	}
	return &User{
		RawId:     RawIdVal,
		CreatedAt: CreatedAtVal,
	}, nil
}

func (m *UserPlain) MarshalJSON() ([]byte, error) {
	if m == nil {
		return []byte("null"), nil
	}
	_ = protojson.Marshal
	_ = json.Marshal
	var e jx.Encoder
	e.ObjStart()
	e.FieldStart("rawId")
	if b, err := json.Marshal(m.RawId); err != nil {
		return nil, err
	} else {
		e.Raw(b)
	}
	e.FieldStart("createdAt")
	if b, err := json.Marshal(m.CreatedAt); err != nil {
		return nil, err
	} else {
		e.Raw(b)
	}
	e.ObjEnd()
	return e.Bytes(), nil
}

func (m *UserPlain) UnmarshalJSON(data []byte) error {
	if m == nil {
		return nil
	}
	_ = protojson.Unmarshal
	_ = json.Unmarshal
	d := jx.DecodeBytes(data)
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		case "rawId":
			raw, err := d.Raw()
			if err != nil {
				return err
			}
			return json.Unmarshal(raw, &m.RawId)
		case "createdAt":
			raw, err := d.Raw()
			if err != nil {
				return err
			}
			return json.Unmarshal(raw, &m.CreatedAt)
		default:
			return d.Skip()
		}
	})
}
