// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: tests/integrations/wkt_map/test.proto

package wkt_map

import (
	_ "github.com/yaroher/protoc-gen-go-plain/goplain"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street        string                 `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_tests_integrations_wkt_map_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_tests_integrations_wkt_map_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_tests_integrations_wkt_map_test_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// WKT
	FAny      *anypb.Any              `protobuf:"bytes,1,opt,name=f_any,json=fAny,proto3" json:"f_any,omitempty"`
	FDuration *durationpb.Duration    `protobuf:"bytes,2,opt,name=f_duration,json=fDuration,proto3" json:"f_duration,omitempty"`
	FEmpty    *emptypb.Empty          `protobuf:"bytes,3,opt,name=f_empty,json=fEmpty,proto3" json:"f_empty,omitempty"`
	FStruct   *structpb.Struct        `protobuf:"bytes,4,opt,name=f_struct,json=fStruct,proto3" json:"f_struct,omitempty"`
	FTs       *timestamppb.Timestamp  `protobuf:"bytes,5,opt,name=f_ts,json=fTs,proto3" json:"f_ts,omitempty"`
	FBool     *wrapperspb.BoolValue   `protobuf:"bytes,6,opt,name=f_bool,json=fBool,proto3" json:"f_bool,omitempty"`
	FString   *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=f_string,json=fString,proto3" json:"f_string,omitempty"`
	// map
	FMapInt32     map[string]int32    `protobuf:"bytes,8,rep,name=f_map_int32,json=fMapInt32,proto3" json:"f_map_int32,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	FMapMsg       map[string]*Address `protobuf:"bytes,9,rep,name=f_map_msg,json=fMapMsg,proto3" json:"f_map_msg,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_tests_integrations_wkt_map_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_tests_integrations_wkt_map_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_tests_integrations_wkt_map_test_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetFAny() *anypb.Any {
	if x != nil {
		return x.FAny
	}
	return nil
}

func (x *User) GetFDuration() *durationpb.Duration {
	if x != nil {
		return x.FDuration
	}
	return nil
}

func (x *User) GetFEmpty() *emptypb.Empty {
	if x != nil {
		return x.FEmpty
	}
	return nil
}

func (x *User) GetFStruct() *structpb.Struct {
	if x != nil {
		return x.FStruct
	}
	return nil
}

func (x *User) GetFTs() *timestamppb.Timestamp {
	if x != nil {
		return x.FTs
	}
	return nil
}

func (x *User) GetFBool() *wrapperspb.BoolValue {
	if x != nil {
		return x.FBool
	}
	return nil
}

func (x *User) GetFString() *wrapperspb.StringValue {
	if x != nil {
		return x.FString
	}
	return nil
}

func (x *User) GetFMapInt32() map[string]int32 {
	if x != nil {
		return x.FMapInt32
	}
	return nil
}

func (x *User) GetFMapMsg() map[string]*Address {
	if x != nil {
		return x.FMapMsg
	}
	return nil
}

var File_tests_integrations_wkt_map_test_proto protoreflect.FileDescriptor

const file_tests_integrations_wkt_map_test_proto_rawDesc = "" +
	"\n" +
	"%tests/integrations/wkt_map/test.proto\x12\ftest.wkt_map\x1a\x15goplain/goplain.proto\x1a\x19google/protobuf/any.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"!\n" +
	"\aAddress\x12\x16\n" +
	"\x06street\x18\x01 \x01(\tR\x06street\"\x84\x05\n" +
	"\x04User\x12)\n" +
	"\x05f_any\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\x04fAny\x128\n" +
	"\n" +
	"f_duration\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\tfDuration\x12/\n" +
	"\af_empty\x18\x03 \x01(\v2\x16.google.protobuf.EmptyR\x06fEmpty\x122\n" +
	"\bf_struct\x18\x04 \x01(\v2\x17.google.protobuf.StructR\afStruct\x12-\n" +
	"\x04f_ts\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x03fTs\x121\n" +
	"\x06f_bool\x18\x06 \x01(\v2\x1a.google.protobuf.BoolValueR\x05fBool\x127\n" +
	"\bf_string\x18\a \x01(\v2\x1c.google.protobuf.StringValueR\afString\x12A\n" +
	"\vf_map_int32\x18\b \x03(\v2!.test.wkt_map.User.FMapInt32EntryR\tfMapInt32\x12;\n" +
	"\tf_map_msg\x18\t \x03(\v2\x1f.test.wkt_map.User.FMapMsgEntryR\afMapMsg\x1a<\n" +
	"\x0eFMapInt32Entry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1aQ\n" +
	"\fFMapMsgEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.test.wkt_map.AddressR\x05value:\x028\x01:\x06\x82\xa6\x1d\x02\b\x01BKZIgithub.com/yaroher/protoc-gen-go-plain/tests/integrations/wkt_map;wkt_mapb\x06proto3"

var (
	file_tests_integrations_wkt_map_test_proto_rawDescOnce sync.Once
	file_tests_integrations_wkt_map_test_proto_rawDescData []byte
)

func file_tests_integrations_wkt_map_test_proto_rawDescGZIP() []byte {
	file_tests_integrations_wkt_map_test_proto_rawDescOnce.Do(func() {
		file_tests_integrations_wkt_map_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tests_integrations_wkt_map_test_proto_rawDesc), len(file_tests_integrations_wkt_map_test_proto_rawDesc)))
	})
	return file_tests_integrations_wkt_map_test_proto_rawDescData
}

var file_tests_integrations_wkt_map_test_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_tests_integrations_wkt_map_test_proto_goTypes = []any{
	(*Address)(nil),                // 0: test.wkt_map.Address
	(*User)(nil),                   // 1: test.wkt_map.User
	nil,                            // 2: test.wkt_map.User.FMapInt32Entry
	nil,                            // 3: test.wkt_map.User.FMapMsgEntry
	(*anypb.Any)(nil),              // 4: google.protobuf.Any
	(*durationpb.Duration)(nil),    // 5: google.protobuf.Duration
	(*emptypb.Empty)(nil),          // 6: google.protobuf.Empty
	(*structpb.Struct)(nil),        // 7: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),  // 8: google.protobuf.Timestamp
	(*wrapperspb.BoolValue)(nil),   // 9: google.protobuf.BoolValue
	(*wrapperspb.StringValue)(nil), // 10: google.protobuf.StringValue
}
var file_tests_integrations_wkt_map_test_proto_depIdxs = []int32{
	4,  // 0: test.wkt_map.User.f_any:type_name -> google.protobuf.Any
	5,  // 1: test.wkt_map.User.f_duration:type_name -> google.protobuf.Duration
	6,  // 2: test.wkt_map.User.f_empty:type_name -> google.protobuf.Empty
	7,  // 3: test.wkt_map.User.f_struct:type_name -> google.protobuf.Struct
	8,  // 4: test.wkt_map.User.f_ts:type_name -> google.protobuf.Timestamp
	9,  // 5: test.wkt_map.User.f_bool:type_name -> google.protobuf.BoolValue
	10, // 6: test.wkt_map.User.f_string:type_name -> google.protobuf.StringValue
	2,  // 7: test.wkt_map.User.f_map_int32:type_name -> test.wkt_map.User.FMapInt32Entry
	3,  // 8: test.wkt_map.User.f_map_msg:type_name -> test.wkt_map.User.FMapMsgEntry
	0,  // 9: test.wkt_map.User.FMapMsgEntry.value:type_name -> test.wkt_map.Address
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_tests_integrations_wkt_map_test_proto_init() }
func file_tests_integrations_wkt_map_test_proto_init() {
	if File_tests_integrations_wkt_map_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tests_integrations_wkt_map_test_proto_rawDesc), len(file_tests_integrations_wkt_map_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tests_integrations_wkt_map_test_proto_goTypes,
		DependencyIndexes: file_tests_integrations_wkt_map_test_proto_depIdxs,
		MessageInfos:      file_tests_integrations_wkt_map_test_proto_msgTypes,
	}.Build()
	File_tests_integrations_wkt_map_test_proto = out.File
	file_tests_integrations_wkt_map_test_proto_goTypes = nil
	file_tests_integrations_wkt_map_test_proto_depIdxs = nil
}
