// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: goplain.proto

package goplain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OverwriteType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoType        string                 `protobuf:"bytes,2,opt,name=go_type,json=goType,proto3" json:"go_type,omitempty"`
	CastFunc      string                 `protobuf:"bytes,3,opt,name=cast_func,json=castFunc,proto3" json:"cast_func,omitempty"`
	Imports       []string               `protobuf:"bytes,4,rep,name=imports,proto3" json:"imports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverwriteType) Reset() {
	*x = OverwriteType{}
	mi := &file_goplain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverwriteType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverwriteType) ProtoMessage() {}

func (x *OverwriteType) ProtoReflect() protoreflect.Message {
	mi := &file_goplain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverwriteType.ProtoReflect.Descriptor instead.
func (*OverwriteType) Descriptor() ([]byte, []int) {
	return file_goplain_proto_rawDescGZIP(), []int{0}
}

func (x *OverwriteType) GetGoType() string {
	if x != nil {
		return x.GoType
	}
	return ""
}

func (x *OverwriteType) GetCastFunc() string {
	if x != nil {
		return x.CastFunc
	}
	return ""
}

func (x *OverwriteType) GetImports() []string {
	if x != nil {
		return x.Imports
	}
	return nil
}

type PlainFieldParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embedded      bool                   `protobuf:"varint,1,opt,name=embedded,proto3" json:"embedded,omitempty"`
	Serialized    bool                   `protobuf:"varint,2,opt,name=serialized,proto3" json:"serialized,omitempty"`
	Overwrite     *OverwriteType         `protobuf:"bytes,3,opt,name=overwrite,proto3" json:"overwrite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlainFieldParams) Reset() {
	*x = PlainFieldParams{}
	mi := &file_goplain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlainFieldParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlainFieldParams) ProtoMessage() {}

func (x *PlainFieldParams) ProtoReflect() protoreflect.Message {
	mi := &file_goplain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlainFieldParams.ProtoReflect.Descriptor instead.
func (*PlainFieldParams) Descriptor() ([]byte, []int) {
	return file_goplain_proto_rawDescGZIP(), []int{1}
}

func (x *PlainFieldParams) GetEmbedded() bool {
	if x != nil {
		return x.Embedded
	}
	return false
}

func (x *PlainFieldParams) GetSerialized() bool {
	if x != nil {
		return x.Serialized
	}
	return false
}

func (x *PlainFieldParams) GetOverwrite() *OverwriteType {
	if x != nil {
		return x.Overwrite
	}
	return nil
}

type PlainMessageParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generate      bool                   `protobuf:"varint,1,opt,name=generate,proto3" json:"generate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlainMessageParams) Reset() {
	*x = PlainMessageParams{}
	mi := &file_goplain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlainMessageParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlainMessageParams) ProtoMessage() {}

func (x *PlainMessageParams) ProtoReflect() protoreflect.Message {
	mi := &file_goplain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlainMessageParams.ProtoReflect.Descriptor instead.
func (*PlainMessageParams) Descriptor() ([]byte, []int) {
	return file_goplain_proto_rawDescGZIP(), []int{2}
}

func (x *PlainMessageParams) GetGenerate() bool {
	if x != nil {
		return x.Generate
	}
	return false
}

var file_goplain_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*PlainFieldParams)(nil),
		Field:         50000,
		Name:          "goplain.field",
		Tag:           "bytes,50000,opt,name=field",
		Filename:      "goplain.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*PlainMessageParams)(nil),
		Field:         50000,
		Name:          "goplain.message",
		Tag:           "bytes,50000,opt,name=message",
		Filename:      "goplain.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional goplain.PlainFieldParams field = 50000;
	E_Field = &file_goplain_proto_extTypes[0]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional goplain.PlainMessageParams message = 50000;
	E_Message = &file_goplain_proto_extTypes[1]
)

var File_goplain_proto protoreflect.FileDescriptor

const file_goplain_proto_rawDesc = "" +
	"\n" +
	"\rgoplain.proto\x12\agoplain\x1a google/protobuf/descriptor.proto\"_\n" +
	"\rOverwriteType\x12\x17\n" +
	"\ago_type\x18\x02 \x01(\tR\x06goType\x12\x1b\n" +
	"\tcast_func\x18\x03 \x01(\tR\bcastFunc\x12\x18\n" +
	"\aimports\x18\x04 \x03(\tR\aimports\"\x84\x01\n" +
	"\x10PlainFieldParams\x12\x1a\n" +
	"\bembedded\x18\x01 \x01(\bR\bembedded\x12\x1e\n" +
	"\n" +
	"serialized\x18\x02 \x01(\bR\n" +
	"serialized\x124\n" +
	"\toverwrite\x18\x03 \x01(\v2\x16.goplain.OverwriteTypeR\toverwrite\"0\n" +
	"\x12PlainMessageParams\x12\x1a\n" +
	"\bgenerate\x18\x01 \x01(\bR\bgenerate:P\n" +
	"\x05field\x12\x1d.google.protobuf.FieldOptions\x18І\x03 \x01(\v2\x19.goplain.PlainFieldParamsR\x05field:X\n" +
	"\amessage\x12\x1f.google.protobuf.MessageOptions\x18І\x03 \x01(\v2\x1b.goplain.PlainMessageParamsR\amessageB0Z.github.com/yaroher/protoc-gen-go-plain/goplainb\x06proto3"

var (
	file_goplain_proto_rawDescOnce sync.Once
	file_goplain_proto_rawDescData []byte
)

func file_goplain_proto_rawDescGZIP() []byte {
	file_goplain_proto_rawDescOnce.Do(func() {
		file_goplain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_goplain_proto_rawDesc), len(file_goplain_proto_rawDesc)))
	})
	return file_goplain_proto_rawDescData
}

var file_goplain_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_goplain_proto_goTypes = []any{
	(*OverwriteType)(nil),               // 0: goplain.OverwriteType
	(*PlainFieldParams)(nil),            // 1: goplain.PlainFieldParams
	(*PlainMessageParams)(nil),          // 2: goplain.PlainMessageParams
	(*descriptorpb.FieldOptions)(nil),   // 3: google.protobuf.FieldOptions
	(*descriptorpb.MessageOptions)(nil), // 4: google.protobuf.MessageOptions
}
var file_goplain_proto_depIdxs = []int32{
	0, // 0: goplain.PlainFieldParams.overwrite:type_name -> goplain.OverwriteType
	3, // 1: goplain.field:extendee -> google.protobuf.FieldOptions
	4, // 2: goplain.message:extendee -> google.protobuf.MessageOptions
	1, // 3: goplain.field:type_name -> goplain.PlainFieldParams
	2, // 4: goplain.message:type_name -> goplain.PlainMessageParams
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	3, // [3:5] is the sub-list for extension type_name
	1, // [1:3] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_goplain_proto_init() }
func file_goplain_proto_init() {
	if File_goplain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_goplain_proto_rawDesc), len(file_goplain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_goplain_proto_goTypes,
		DependencyIndexes: file_goplain_proto_depIdxs,
		MessageInfos:      file_goplain_proto_msgTypes,
		ExtensionInfos:    file_goplain_proto_extTypes,
	}.Build()
	File_goplain_proto = out.File
	file_goplain_proto_goTypes = nil
	file_goplain_proto_depIdxs = nil
}
