// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: goplain.proto

package goplain

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GoIdent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ImportPath    string                 `protobuf:"bytes,2,opt,name=import_path,json=importPath,proto3" json:"import_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoIdent) Reset() {
	*x = GoIdent{}
	mi := &file_goplain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoIdent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoIdent) ProtoMessage() {}

func (x *GoIdent) ProtoReflect() protoreflect.Message {
	mi := &file_goplain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoIdent.ProtoReflect.Descriptor instead.
func (*GoIdent) Descriptor() ([]byte, []int) {
	return file_goplain_proto_rawDescGZIP(), []int{0}
}

func (x *GoIdent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GoIdent) GetImportPath() string {
	if x != nil {
		return x.ImportPath
	}
	return ""
}

type OverwriteType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selector      []*OverrideSelector    `protobuf:"bytes,1,rep,name=selector,proto3" json:"selector,omitempty"`
	GoType        *GoIdent               `protobuf:"bytes,2,opt,name=go_type,json=goType,proto3" json:"go_type,omitempty"`
	ToPlain       *GoIdent               `protobuf:"bytes,3,opt,name=to_plain,json=toPlain,proto3" json:"to_plain,omitempty"`
	ToPb          *GoIdent               `protobuf:"bytes,4,opt,name=to_pb,json=toPb,proto3" json:"to_pb,omitempty"`
	Pointer       bool                   `protobuf:"varint,5,opt,name=pointer,proto3" json:"pointer,omitempty"`
	ToPlainBody   string                 `protobuf:"bytes,6,opt,name=to_plain_body,json=toPlainBody,proto3" json:"to_plain_body,omitempty"`
	ToPbBody      string                 `protobuf:"bytes,7,opt,name=to_pb_body,json=toPbBody,proto3" json:"to_pb_body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverwriteType) Reset() {
	*x = OverwriteType{}
	mi := &file_goplain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverwriteType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverwriteType) ProtoMessage() {}

func (x *OverwriteType) ProtoReflect() protoreflect.Message {
	mi := &file_goplain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverwriteType.ProtoReflect.Descriptor instead.
func (*OverwriteType) Descriptor() ([]byte, []int) {
	return file_goplain_proto_rawDescGZIP(), []int{1}
}

func (x *OverwriteType) GetSelector() []*OverrideSelector {
	if x != nil {
		return x.Selector
	}
	return nil
}

func (x *OverwriteType) GetGoType() *GoIdent {
	if x != nil {
		return x.GoType
	}
	return nil
}

func (x *OverwriteType) GetToPlain() *GoIdent {
	if x != nil {
		return x.ToPlain
	}
	return nil
}

func (x *OverwriteType) GetToPb() *GoIdent {
	if x != nil {
		return x.ToPb
	}
	return nil
}

func (x *OverwriteType) GetPointer() bool {
	if x != nil {
		return x.Pointer
	}
	return false
}

func (x *OverwriteType) GetToPlainBody() string {
	if x != nil {
		return x.ToPlainBody
	}
	return ""
}

func (x *OverwriteType) GetToPbBody() string {
	if x != nil {
		return x.ToPbBody
	}
	return ""
}

type OverrideSelector struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full proto type name or scalar kind name (e.g. "string", "google.protobuf.Timestamp").
	ProtoType     string `protobuf:"bytes,1,opt,name=proto_type,json=protoType,proto3" json:"proto_type,omitempty"`
	IsList        *bool  `protobuf:"varint,2,opt,name=is_list,json=isList,proto3,oneof" json:"is_list,omitempty"`
	IsMap         *bool  `protobuf:"varint,3,opt,name=is_map,json=isMap,proto3,oneof" json:"is_map,omitempty"`
	IsOptional    *bool  `protobuf:"varint,4,opt,name=is_optional,json=isOptional,proto3,oneof" json:"is_optional,omitempty"`
	IsOneof       *bool  `protobuf:"varint,5,opt,name=is_oneof,json=isOneof,proto3,oneof" json:"is_oneof,omitempty"`
	IsEmbedded    *bool  `protobuf:"varint,6,opt,name=is_embedded,json=isEmbedded,proto3,oneof" json:"is_embedded,omitempty"`
	IsSerialized  *bool  `protobuf:"varint,7,opt,name=is_serialized,json=isSerialized,proto3,oneof" json:"is_serialized,omitempty"`
	IsVirtual     *bool  `protobuf:"varint,8,opt,name=is_virtual,json=isVirtual,proto3,oneof" json:"is_virtual,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverrideSelector) Reset() {
	*x = OverrideSelector{}
	mi := &file_goplain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverrideSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverrideSelector) ProtoMessage() {}

func (x *OverrideSelector) ProtoReflect() protoreflect.Message {
	mi := &file_goplain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverrideSelector.ProtoReflect.Descriptor instead.
func (*OverrideSelector) Descriptor() ([]byte, []int) {
	return file_goplain_proto_rawDescGZIP(), []int{2}
}

func (x *OverrideSelector) GetProtoType() string {
	if x != nil {
		return x.ProtoType
	}
	return ""
}

func (x *OverrideSelector) GetIsList() bool {
	if x != nil && x.IsList != nil {
		return *x.IsList
	}
	return false
}

func (x *OverrideSelector) GetIsMap() bool {
	if x != nil && x.IsMap != nil {
		return *x.IsMap
	}
	return false
}

func (x *OverrideSelector) GetIsOptional() bool {
	if x != nil && x.IsOptional != nil {
		return *x.IsOptional
	}
	return false
}

func (x *OverrideSelector) GetIsOneof() bool {
	if x != nil && x.IsOneof != nil {
		return *x.IsOneof
	}
	return false
}

func (x *OverrideSelector) GetIsEmbedded() bool {
	if x != nil && x.IsEmbedded != nil {
		return *x.IsEmbedded
	}
	return false
}

func (x *OverrideSelector) GetIsSerialized() bool {
	if x != nil && x.IsSerialized != nil {
		return *x.IsSerialized
	}
	return false
}

func (x *OverrideSelector) GetIsVirtual() bool {
	if x != nil && x.IsVirtual != nil {
		return *x.IsVirtual
	}
	return false
}

type VirtualFieldSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	GoType        *GoIdent               `protobuf:"bytes,2,opt,name=go_type,json=goType,proto3" json:"go_type,omitempty"`
	ProtoType     string                 `protobuf:"bytes,3,opt,name=proto_type,json=protoType,proto3" json:"proto_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualFieldSpec) Reset() {
	*x = VirtualFieldSpec{}
	mi := &file_goplain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualFieldSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualFieldSpec) ProtoMessage() {}

func (x *VirtualFieldSpec) ProtoReflect() protoreflect.Message {
	mi := &file_goplain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualFieldSpec.ProtoReflect.Descriptor instead.
func (*VirtualFieldSpec) Descriptor() ([]byte, []int) {
	return file_goplain_proto_rawDescGZIP(), []int{3}
}

func (x *VirtualFieldSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VirtualFieldSpec) GetGoType() *GoIdent {
	if x != nil {
		return x.GoType
	}
	return nil
}

func (x *VirtualFieldSpec) GetProtoType() string {
	if x != nil {
		return x.ProtoType
	}
	return ""
}

type VirtualField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Field         *VirtualFieldSpec      `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualField) Reset() {
	*x = VirtualField{}
	mi := &file_goplain_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualField) ProtoMessage() {}

func (x *VirtualField) ProtoReflect() protoreflect.Message {
	mi := &file_goplain_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualField.ProtoReflect.Descriptor instead.
func (*VirtualField) Descriptor() ([]byte, []int) {
	return file_goplain_proto_rawDescGZIP(), []int{4}
}

func (x *VirtualField) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VirtualField) GetField() *VirtualFieldSpec {
	if x != nil {
		return x.Field
	}
	return nil
}

type VirtualMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Fields        []*VirtualFieldSpec    `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualMessage) Reset() {
	*x = VirtualMessage{}
	mi := &file_goplain_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualMessage) ProtoMessage() {}

func (x *VirtualMessage) ProtoReflect() protoreflect.Message {
	mi := &file_goplain_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualMessage.ProtoReflect.Descriptor instead.
func (*VirtualMessage) Descriptor() ([]byte, []int) {
	return file_goplain_proto_rawDescGZIP(), []int{5}
}

func (x *VirtualMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VirtualMessage) GetFields() []*VirtualFieldSpec {
	if x != nil {
		return x.Fields
	}
	return nil
}

type PlainFieldParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embedded      bool                   `protobuf:"varint,1,opt,name=embedded,proto3" json:"embedded,omitempty"`
	Serialized    bool                   `protobuf:"varint,2,opt,name=serialized,proto3" json:"serialized,omitempty"`
	Overwrite     *OverwriteType         `protobuf:"bytes,3,opt,name=overwrite,proto3" json:"overwrite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlainFieldParams) Reset() {
	*x = PlainFieldParams{}
	mi := &file_goplain_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlainFieldParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlainFieldParams) ProtoMessage() {}

func (x *PlainFieldParams) ProtoReflect() protoreflect.Message {
	mi := &file_goplain_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlainFieldParams.ProtoReflect.Descriptor instead.
func (*PlainFieldParams) Descriptor() ([]byte, []int) {
	return file_goplain_proto_rawDescGZIP(), []int{6}
}

func (x *PlainFieldParams) GetEmbedded() bool {
	if x != nil {
		return x.Embedded
	}
	return false
}

func (x *PlainFieldParams) GetSerialized() bool {
	if x != nil {
		return x.Serialized
	}
	return false
}

func (x *PlainFieldParams) GetOverwrite() *OverwriteType {
	if x != nil {
		return x.Overwrite
	}
	return nil
}

type PlainFileParams struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Overwrite      []*OverwriteType       `protobuf:"bytes,1,rep,name=overwrite,proto3" json:"overwrite,omitempty"`
	VirtualField   []*VirtualField        `protobuf:"bytes,2,rep,name=virtual_field,json=virtualField,proto3" json:"virtual_field,omitempty"`
	VirtualMessage []*VirtualMessage      `protobuf:"bytes,3,rep,name=virtual_message,json=virtualMessage,proto3" json:"virtual_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlainFileParams) Reset() {
	*x = PlainFileParams{}
	mi := &file_goplain_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlainFileParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlainFileParams) ProtoMessage() {}

func (x *PlainFileParams) ProtoReflect() protoreflect.Message {
	mi := &file_goplain_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlainFileParams.ProtoReflect.Descriptor instead.
func (*PlainFileParams) Descriptor() ([]byte, []int) {
	return file_goplain_proto_rawDescGZIP(), []int{7}
}

func (x *PlainFileParams) GetOverwrite() []*OverwriteType {
	if x != nil {
		return x.Overwrite
	}
	return nil
}

func (x *PlainFileParams) GetVirtualField() []*VirtualField {
	if x != nil {
		return x.VirtualField
	}
	return nil
}

func (x *PlainFileParams) GetVirtualMessage() []*VirtualMessage {
	if x != nil {
		return x.VirtualMessage
	}
	return nil
}

type PlainMessageParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generate      bool                   `protobuf:"varint,1,opt,name=generate,proto3" json:"generate,omitempty"`
	TypeAlias     bool                   `protobuf:"varint,2,opt,name=type_alias,json=typeAlias,proto3" json:"type_alias,omitempty"`
	VirtualFields []*VirtualFieldSpec    `protobuf:"bytes,3,rep,name=virtual_fields,json=virtualFields,proto3" json:"virtual_fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlainMessageParams) Reset() {
	*x = PlainMessageParams{}
	mi := &file_goplain_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlainMessageParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlainMessageParams) ProtoMessage() {}

func (x *PlainMessageParams) ProtoReflect() protoreflect.Message {
	mi := &file_goplain_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlainMessageParams.ProtoReflect.Descriptor instead.
func (*PlainMessageParams) Descriptor() ([]byte, []int) {
	return file_goplain_proto_rawDescGZIP(), []int{8}
}

func (x *PlainMessageParams) GetGenerate() bool {
	if x != nil {
		return x.Generate
	}
	return false
}

func (x *PlainMessageParams) GetTypeAlias() bool {
	if x != nil {
		return x.TypeAlias
	}
	return false
}

func (x *PlainMessageParams) GetVirtualFields() []*VirtualFieldSpec {
	if x != nil {
		return x.VirtualFields
	}
	return nil
}

var file_goplain_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*PlainFieldParams)(nil),
		Field:         50000,
		Name:          "goplain.field",
		Tag:           "bytes,50000,opt,name=field",
		Filename:      "goplain.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*PlainFileParams)(nil),
		Field:         50000,
		Name:          "goplain.file",
		Tag:           "bytes,50000,opt,name=file",
		Filename:      "goplain.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*PlainMessageParams)(nil),
		Field:         50000,
		Name:          "goplain.message",
		Tag:           "bytes,50000,opt,name=message",
		Filename:      "goplain.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional goplain.PlainFieldParams field = 50000;
	E_Field = &file_goplain_proto_extTypes[0]
)

// Extension fields to descriptorpb.FileOptions.
var (
	// optional goplain.PlainFileParams file = 50000;
	E_File = &file_goplain_proto_extTypes[1]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional goplain.PlainMessageParams message = 50000;
	E_Message = &file_goplain_proto_extTypes[2]
)

var File_goplain_proto protoreflect.FileDescriptor

const file_goplain_proto_rawDesc = "" +
	"\n" +
	"\rgoplain.proto\x12\agoplain\x1a google/protobuf/descriptor.proto\">\n" +
	"\aGoIdent\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vimport_path\x18\x02 \x01(\tR\n" +
	"importPath\"\xa1\x02\n" +
	"\rOverwriteType\x125\n" +
	"\bselector\x18\x01 \x03(\v2\x19.goplain.OverrideSelectorR\bselector\x12)\n" +
	"\ago_type\x18\x02 \x01(\v2\x10.goplain.GoIdentR\x06goType\x12+\n" +
	"\bto_plain\x18\x03 \x01(\v2\x10.goplain.GoIdentR\atoPlain\x12%\n" +
	"\x05to_pb\x18\x04 \x01(\v2\x10.goplain.GoIdentR\x04toPb\x12\x18\n" +
	"\apointer\x18\x05 \x01(\bR\apointer\x12\"\n" +
	"\rto_plain_body\x18\x06 \x01(\tR\vtoPlainBody\x12\x1c\n" +
	"\n" +
	"to_pb_body\x18\a \x01(\tR\btoPbBody\"\x8a\x03\n" +
	"\x10OverrideSelector\x12\x1d\n" +
	"\n" +
	"proto_type\x18\x01 \x01(\tR\tprotoType\x12\x1c\n" +
	"\ais_list\x18\x02 \x01(\bH\x00R\x06isList\x88\x01\x01\x12\x1a\n" +
	"\x06is_map\x18\x03 \x01(\bH\x01R\x05isMap\x88\x01\x01\x12$\n" +
	"\vis_optional\x18\x04 \x01(\bH\x02R\n" +
	"isOptional\x88\x01\x01\x12\x1e\n" +
	"\bis_oneof\x18\x05 \x01(\bH\x03R\aisOneof\x88\x01\x01\x12$\n" +
	"\vis_embedded\x18\x06 \x01(\bH\x04R\n" +
	"isEmbedded\x88\x01\x01\x12(\n" +
	"\ris_serialized\x18\a \x01(\bH\x05R\fisSerialized\x88\x01\x01\x12\"\n" +
	"\n" +
	"is_virtual\x18\b \x01(\bH\x06R\tisVirtual\x88\x01\x01B\n" +
	"\n" +
	"\b_is_listB\t\n" +
	"\a_is_mapB\x0e\n" +
	"\f_is_optionalB\v\n" +
	"\t_is_oneofB\x0e\n" +
	"\f_is_embeddedB\x10\n" +
	"\x0e_is_serializedB\r\n" +
	"\v_is_virtual\"p\n" +
	"\x10VirtualFieldSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12)\n" +
	"\ago_type\x18\x02 \x01(\v2\x10.goplain.GoIdentR\x06goType\x12\x1d\n" +
	"\n" +
	"proto_type\x18\x03 \x01(\tR\tprotoType\"Y\n" +
	"\fVirtualField\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12/\n" +
	"\x05field\x18\x02 \x01(\v2\x19.goplain.VirtualFieldSpecR\x05field\"W\n" +
	"\x0eVirtualMessage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x121\n" +
	"\x06fields\x18\x02 \x03(\v2\x19.goplain.VirtualFieldSpecR\x06fields\"\x84\x01\n" +
	"\x10PlainFieldParams\x12\x1a\n" +
	"\bembedded\x18\x01 \x01(\bR\bembedded\x12\x1e\n" +
	"\n" +
	"serialized\x18\x02 \x01(\bR\n" +
	"serialized\x124\n" +
	"\toverwrite\x18\x03 \x01(\v2\x16.goplain.OverwriteTypeR\toverwrite\"\xc5\x01\n" +
	"\x0fPlainFileParams\x124\n" +
	"\toverwrite\x18\x01 \x03(\v2\x16.goplain.OverwriteTypeR\toverwrite\x12:\n" +
	"\rvirtual_field\x18\x02 \x03(\v2\x15.goplain.VirtualFieldR\fvirtualField\x12@\n" +
	"\x0fvirtual_message\x18\x03 \x03(\v2\x17.goplain.VirtualMessageR\x0evirtualMessage\"\x91\x01\n" +
	"\x12PlainMessageParams\x12\x1a\n" +
	"\bgenerate\x18\x01 \x01(\bR\bgenerate\x12\x1d\n" +
	"\n" +
	"type_alias\x18\x02 \x01(\bR\ttypeAlias\x12@\n" +
	"\x0evirtual_fields\x18\x03 \x03(\v2\x19.goplain.VirtualFieldSpecR\rvirtualFields:P\n" +
	"\x05field\x12\x1d.google.protobuf.FieldOptions\x18І\x03 \x01(\v2\x19.goplain.PlainFieldParamsR\x05field:L\n" +
	"\x04file\x12\x1c.google.protobuf.FileOptions\x18І\x03 \x01(\v2\x18.goplain.PlainFileParamsR\x04file:X\n" +
	"\amessage\x12\x1f.google.protobuf.MessageOptions\x18І\x03 \x01(\v2\x1b.goplain.PlainMessageParamsR\amessageB0Z.github.com/yaroher/protoc-gen-go-plain/goplainb\x06proto3"

var (
	file_goplain_proto_rawDescOnce sync.Once
	file_goplain_proto_rawDescData []byte
)

func file_goplain_proto_rawDescGZIP() []byte {
	file_goplain_proto_rawDescOnce.Do(func() {
		file_goplain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_goplain_proto_rawDesc), len(file_goplain_proto_rawDesc)))
	})
	return file_goplain_proto_rawDescData
}

var file_goplain_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_goplain_proto_goTypes = []any{
	(*GoIdent)(nil),                     // 0: goplain.GoIdent
	(*OverwriteType)(nil),               // 1: goplain.OverwriteType
	(*OverrideSelector)(nil),            // 2: goplain.OverrideSelector
	(*VirtualFieldSpec)(nil),            // 3: goplain.VirtualFieldSpec
	(*VirtualField)(nil),                // 4: goplain.VirtualField
	(*VirtualMessage)(nil),              // 5: goplain.VirtualMessage
	(*PlainFieldParams)(nil),            // 6: goplain.PlainFieldParams
	(*PlainFileParams)(nil),             // 7: goplain.PlainFileParams
	(*PlainMessageParams)(nil),          // 8: goplain.PlainMessageParams
	(*descriptorpb.FieldOptions)(nil),   // 9: google.protobuf.FieldOptions
	(*descriptorpb.FileOptions)(nil),    // 10: google.protobuf.FileOptions
	(*descriptorpb.MessageOptions)(nil), // 11: google.protobuf.MessageOptions
}
var file_goplain_proto_depIdxs = []int32{
	2,  // 0: goplain.OverwriteType.selector:type_name -> goplain.OverrideSelector
	0,  // 1: goplain.OverwriteType.go_type:type_name -> goplain.GoIdent
	0,  // 2: goplain.OverwriteType.to_plain:type_name -> goplain.GoIdent
	0,  // 3: goplain.OverwriteType.to_pb:type_name -> goplain.GoIdent
	0,  // 4: goplain.VirtualFieldSpec.go_type:type_name -> goplain.GoIdent
	3,  // 5: goplain.VirtualField.field:type_name -> goplain.VirtualFieldSpec
	3,  // 6: goplain.VirtualMessage.fields:type_name -> goplain.VirtualFieldSpec
	1,  // 7: goplain.PlainFieldParams.overwrite:type_name -> goplain.OverwriteType
	1,  // 8: goplain.PlainFileParams.overwrite:type_name -> goplain.OverwriteType
	4,  // 9: goplain.PlainFileParams.virtual_field:type_name -> goplain.VirtualField
	5,  // 10: goplain.PlainFileParams.virtual_message:type_name -> goplain.VirtualMessage
	3,  // 11: goplain.PlainMessageParams.virtual_fields:type_name -> goplain.VirtualFieldSpec
	9,  // 12: goplain.field:extendee -> google.protobuf.FieldOptions
	10, // 13: goplain.file:extendee -> google.protobuf.FileOptions
	11, // 14: goplain.message:extendee -> google.protobuf.MessageOptions
	6,  // 15: goplain.field:type_name -> goplain.PlainFieldParams
	7,  // 16: goplain.file:type_name -> goplain.PlainFileParams
	8,  // 17: goplain.message:type_name -> goplain.PlainMessageParams
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	15, // [15:18] is the sub-list for extension type_name
	12, // [12:15] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_goplain_proto_init() }
func file_goplain_proto_init() {
	if File_goplain_proto != nil {
		return
	}
	file_goplain_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_goplain_proto_rawDesc), len(file_goplain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_goplain_proto_goTypes,
		DependencyIndexes: file_goplain_proto_depIdxs,
		MessageInfos:      file_goplain_proto_msgTypes,
		ExtensionInfos:    file_goplain_proto_extTypes,
	}.Build()
	File_goplain_proto = out.File
	file_goplain_proto_goTypes = nil
	file_goplain_proto_depIdxs = nil
}
