// Code generated by protoc-gen-go-plain. DO NOT EDIT.

package serialize

import (
	json "encoding/json"
	jx "github.com/go-faster/jx"
	cast "github.com/yaroher/protoc-gen-go-plain/cast"
	protojson "google.golang.org/protobuf/encoding/protojson"
)

type UserPlain struct {

	// src: .test.serialize.User.settings; transform: serialize
	Settings []byte
}

func (m *User) IntoPlain() *UserPlain {
	if m == nil {
		return nil
	}
	return &UserPlain{
		Settings: cast.MessageToSliceByte(m.GetSettings()),
	}
}

func (m *User) IntoPlainErr() (*UserPlain, error) {
	if m == nil {
		return nil, nil
	}
	SettingsVal, err := cast.MessageToSliceByteErr(m.GetSettings())
	if err != nil {
		return nil, err
	}
	return &UserPlain{
		Settings: SettingsVal,
	}, nil
}

func (m *UserPlain) IntoPb() *User {
	if m == nil {
		return nil
	}
	return &User{
		Settings: cast.MessageFromSliceByte[*Settings](m.Settings),
	}
}

func (m *UserPlain) IntoPbErr() (*User, error) {
	if m == nil {
		return nil, nil
	}
	SettingsVal, err := cast.MessageFromSliceByteErr[*Settings](m.Settings)
	if err != nil {
		return nil, err
	}
	return &User{
		Settings: SettingsVal,
	}, nil
}

func (m *UserPlain) MarshalJSON() ([]byte, error) {
	if m == nil {
		return []byte("null"), nil
	}
	_ = protojson.Marshal
	_ = json.Marshal
	var e jx.Encoder
	e.ObjStart()
	e.FieldStart("settings")
	if m.Settings == nil {
		e.Null()
	} else {
		e.Base64(m.Settings)
	}
	e.ObjEnd()
	return e.Bytes(), nil
}

func (m *UserPlain) UnmarshalJSON(data []byte) error {
	if m == nil {
		return nil
	}
	_ = protojson.Unmarshal
	_ = json.Unmarshal
	d := jx.DecodeBytes(data)
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		case "settings":
			v, err := d.Base64()
			if err != nil {
				return err
			}
			m.Settings = v
			return nil
		default:
			return d.Skip()
		}
	})
}
