// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: tests/integrations/serialize/test.proto

package serialize

import (
	_ "github.com/yaroher/protoc-gen-go-plain/goplain"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Settings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locale        string                 `protobuf:"bytes,1,opt,name=locale,proto3" json:"locale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Settings) Reset() {
	*x = Settings{}
	mi := &file_tests_integrations_serialize_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Settings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Settings) ProtoMessage() {}

func (x *Settings) ProtoReflect() protoreflect.Message {
	mi := &file_tests_integrations_serialize_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Settings.ProtoReflect.Descriptor instead.
func (*Settings) Descriptor() ([]byte, []int) {
	return file_tests_integrations_serialize_test_proto_rawDescGZIP(), []int{0}
}

func (x *Settings) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *Settings              `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_tests_integrations_serialize_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_tests_integrations_serialize_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_tests_integrations_serialize_test_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetSettings() *Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

var File_tests_integrations_serialize_test_proto protoreflect.FileDescriptor

const file_tests_integrations_serialize_test_proto_rawDesc = "" +
	"\n" +
	"'tests/integrations/serialize/test.proto\x12\x0etest.serialize\x1a\x15goplain/goplain.proto\"\"\n" +
	"\bSettings\x12\x16\n" +
	"\x06locale\x18\x01 \x01(\tR\x06locale\"L\n" +
	"\x04User\x12<\n" +
	"\bsettings\x18\x01 \x01(\v2\x18.test.serialize.SettingsB\x06\x82\xa6\x1d\x02\x10\x01R\bsettings:\x06\x82\xa6\x1d\x02\b\x01BOZMgithub.com/yaroher/protoc-gen-go-plain/tests/integrations/serialize;serializeb\x06proto3"

var (
	file_tests_integrations_serialize_test_proto_rawDescOnce sync.Once
	file_tests_integrations_serialize_test_proto_rawDescData []byte
)

func file_tests_integrations_serialize_test_proto_rawDescGZIP() []byte {
	file_tests_integrations_serialize_test_proto_rawDescOnce.Do(func() {
		file_tests_integrations_serialize_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tests_integrations_serialize_test_proto_rawDesc), len(file_tests_integrations_serialize_test_proto_rawDesc)))
	})
	return file_tests_integrations_serialize_test_proto_rawDescData
}

var file_tests_integrations_serialize_test_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tests_integrations_serialize_test_proto_goTypes = []any{
	(*Settings)(nil), // 0: test.serialize.Settings
	(*User)(nil),     // 1: test.serialize.User
}
var file_tests_integrations_serialize_test_proto_depIdxs = []int32{
	0, // 0: test.serialize.User.settings:type_name -> test.serialize.Settings
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tests_integrations_serialize_test_proto_init() }
func file_tests_integrations_serialize_test_proto_init() {
	if File_tests_integrations_serialize_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tests_integrations_serialize_test_proto_rawDesc), len(file_tests_integrations_serialize_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tests_integrations_serialize_test_proto_goTypes,
		DependencyIndexes: file_tests_integrations_serialize_test_proto_depIdxs,
		MessageInfos:      file_tests_integrations_serialize_test_proto_msgTypes,
	}.Build()
	File_tests_integrations_serialize_test_proto = out.File
	file_tests_integrations_serialize_test_proto_goTypes = nil
	file_tests_integrations_serialize_test_proto_depIdxs = nil
}
