// Code generated by protoc-gen-go-plain. DO NOT EDIT.

package serialize

import (
	cast "github.com/yaroher/protoc-gen-go-plain/cast"
)

type UserPlain struct {

	// src: .test.serialize.User.settings; transform: serialize
	Settings []byte
}

func (m *User) IntoPlain() *UserPlain {
	if m == nil {
		return nil
	}
	return &UserPlain{
		Settings: cast.MessageToSliceByte(m.GetSettings()),
	}
}

func (m *User) IntoPlainErr() (*UserPlain, error) {
	if m == nil {
		return nil, nil
	}
	SettingsVal, err := cast.MessageToSliceByteErr(m.GetSettings())
	if err != nil {
		return nil, err
	}
	return &UserPlain{
		Settings: SettingsVal,
	}, nil
}

func (m *UserPlain) IntoPb() *User {
	if m == nil {
		return nil
	}
	return &User{
		Settings: cast.MessageFromSliceByte[*Settings](m.Settings),
	}
}

func (m *UserPlain) IntoPbErr() (*User, error) {
	if m == nil {
		return nil, nil
	}
	SettingsVal, err := cast.MessageFromSliceByteErr[*Settings](m.Settings)
	if err != nil {
		return nil, err
	}
	return &User{
		Settings: SettingsVal,
	}, nil
}
