// Code generated by protoc-gen-go-plain. DO NOT EDIT.

package plain

type BaseInfoPlain struct {
	Id     string `json:"id"`
	Source string `json:"source"`
}

type UserPlain struct {
	Source       string  `json:"source"`
	Name         string  `json:"name"`
	ContactEmail *string `json:"contactEmail,omitempty"`
	ContactPhone *string `json:"contactPhone,omitempty"`
	Id           string  `json:"id"`
}

type UserEventPlain struct {
	Source       string  `json:"source"`
	Name         string  `json:"name"`
	ContactEmail *string `json:"contactEmail,omitempty"`
	ContactPhone *string `json:"contactPhone,omitempty"`
	Id           string  `json:"id"`
	EventType    string  `json:"eventType"`
}
