// Code generated by protoc-gen-go-plain. DO NOT EDIT.

package plain

import ()

func (x *BaseInfoPlain) IntoPb() *BaseInfo {
	if x == nil {
		return nil
	}
	out := &BaseInfo{}
	out.Id = x.Id
	out.Source = x.Source
	return out
}

func (x *BaseInfo) IntoPlain() *BaseInfoPlain {
	if x == nil {
		return nil
	}
	out := &BaseInfoPlain{}
	out.Id = x.Id
	out.Source = x.Source
	return out
}

func (x *BaseInfoPlain) IntoPbErr() (*BaseInfo, error) {
	if x == nil {
		return nil, nil
	}
	out := &BaseInfo{}
	out.Id = x.Id
	out.Source = x.Source
	return out, nil
}

func (x *BaseInfo) IntoPlainErr() (*BaseInfoPlain, error) {
	if x == nil {
		return nil, nil
	}
	out := &BaseInfoPlain{}
	out.Id = x.Id
	out.Source = x.Source
	return out, nil
}

func (x *UserPlain) IntoPb() *User {
	if x == nil {
		return nil
	}
	out := &User{}
	if out.Base == nil {
		out.Base = &BaseInfo{}
	}
	out.Base.Source = x.Source
	out.Name = x.Name
	if x.ContactEmail != nil {
		out.Contact = &User_Email{Email: *x.ContactEmail}
	}
	if x.ContactPhone != nil {
		out.Contact = &User_Phone{Phone: *x.ContactPhone}
	}
	if out.Base == nil {
		out.Base = &BaseInfo{}
	}
	out.Base.Id = x.Id
	return out
}

func (x *User) IntoPlain() *UserPlain {
	if x == nil {
		return nil
	}
	out := &UserPlain{}
	if x.Base != nil {
		out.Source = x.Base.Source
	}
	out.Name = x.Name
	if _oneofEmail0, ok := x.Contact.(*User_Email); ok {
		_valContactEmail := _oneofEmail0.Email
		out.ContactEmail = &_valContactEmail
	}
	if _oneofPhone0, ok := x.Contact.(*User_Phone); ok {
		_valContactPhone := _oneofPhone0.Phone
		out.ContactPhone = &_valContactPhone
	}
	if x.Base != nil {
		out.Id = x.Base.Id
	}
	return out
}

func (x *UserPlain) IntoPbErr() (*User, error) {
	if x == nil {
		return nil, nil
	}
	out := &User{}
	if out.Base == nil {
		out.Base = &BaseInfo{}
	}
	out.Base.Source = x.Source
	out.Name = x.Name
	if x.ContactEmail != nil {
		out.Contact = &User_Email{Email: *x.ContactEmail}
	}
	if x.ContactPhone != nil {
		out.Contact = &User_Phone{Phone: *x.ContactPhone}
	}
	if out.Base == nil {
		out.Base = &BaseInfo{}
	}
	out.Base.Id = x.Id
	return out, nil
}

func (x *User) IntoPlainErr() (*UserPlain, error) {
	if x == nil {
		return nil, nil
	}
	out := &UserPlain{}
	if x.Base != nil {
		out.Source = x.Base.Source
	}
	out.Name = x.Name
	if _oneofEmail0, ok := x.Contact.(*User_Email); ok {
		_valContactEmail := _oneofEmail0.Email
		out.ContactEmail = &_valContactEmail
	}
	if _oneofPhone0, ok := x.Contact.(*User_Phone); ok {
		_valContactPhone := _oneofPhone0.Phone
		out.ContactPhone = &_valContactPhone
	}
	if x.Base != nil {
		out.Id = x.Base.Id
	}
	return out, nil
}

func (x *UserEventPlain) IntoPb() *UserEvent {
	if x == nil {
		return nil
	}
	out := &UserEvent{}
	if out.User == nil {
		out.User = &User{}
	}
	if out.User.Base == nil {
		out.User.Base = &BaseInfo{}
	}
	out.User.Base.Source = x.Source
	if out.User == nil {
		out.User = &User{}
	}
	out.User.Name = x.Name
	if x.ContactEmail != nil {
		if out.User == nil {
			out.User = &User{}
		}
		out.User.Contact = &User_Email{Email: *x.ContactEmail}
	}
	if x.ContactPhone != nil {
		if out.User == nil {
			out.User = &User{}
		}
		out.User.Contact = &User_Phone{Phone: *x.ContactPhone}
	}
	if out.User == nil {
		out.User = &User{}
	}
	if out.User.Base == nil {
		out.User.Base = &BaseInfo{}
	}
	out.User.Base.Id = x.Id
	out.EventType = x.EventType
	return out
}

func (x *UserEvent) IntoPlain() *UserEventPlain {
	if x == nil {
		return nil
	}
	out := &UserEventPlain{}
	if x.User != nil {
		if x.User.Base != nil {
			out.Source = x.User.Base.Source
		}
	}
	if x.User != nil {
		out.Name = x.User.Name
	}
	if x.User != nil {
		if _oneofEmail1, ok := x.User.Contact.(*User_Email); ok {
			_valContactEmail := _oneofEmail1.Email
			out.ContactEmail = &_valContactEmail
		}
	}
	if x.User != nil {
		if _oneofPhone1, ok := x.User.Contact.(*User_Phone); ok {
			_valContactPhone := _oneofPhone1.Phone
			out.ContactPhone = &_valContactPhone
		}
	}
	if x.User != nil {
		if x.User.Base != nil {
			out.Id = x.User.Base.Id
		}
	}
	out.EventType = x.EventType
	return out
}

func (x *UserEventPlain) IntoPbErr() (*UserEvent, error) {
	if x == nil {
		return nil, nil
	}
	out := &UserEvent{}
	if out.User == nil {
		out.User = &User{}
	}
	if out.User.Base == nil {
		out.User.Base = &BaseInfo{}
	}
	out.User.Base.Source = x.Source
	if out.User == nil {
		out.User = &User{}
	}
	out.User.Name = x.Name
	if x.ContactEmail != nil {
		if out.User == nil {
			out.User = &User{}
		}
		out.User.Contact = &User_Email{Email: *x.ContactEmail}
	}
	if x.ContactPhone != nil {
		if out.User == nil {
			out.User = &User{}
		}
		out.User.Contact = &User_Phone{Phone: *x.ContactPhone}
	}
	if out.User == nil {
		out.User = &User{}
	}
	if out.User.Base == nil {
		out.User.Base = &BaseInfo{}
	}
	out.User.Base.Id = x.Id
	out.EventType = x.EventType
	return out, nil
}

func (x *UserEvent) IntoPlainErr() (*UserEventPlain, error) {
	if x == nil {
		return nil, nil
	}
	out := &UserEventPlain{}
	if x.User != nil {
		if x.User.Base != nil {
			out.Source = x.User.Base.Source
		}
	}
	if x.User != nil {
		out.Name = x.User.Name
	}
	if x.User != nil {
		if _oneofEmail1, ok := x.User.Contact.(*User_Email); ok {
			_valContactEmail := _oneofEmail1.Email
			out.ContactEmail = &_valContactEmail
		}
	}
	if x.User != nil {
		if _oneofPhone1, ok := x.User.Contact.(*User_Phone); ok {
			_valContactPhone := _oneofPhone1.Phone
			out.ContactPhone = &_valContactPhone
		}
	}
	if x.User != nil {
		if x.User.Base != nil {
			out.Id = x.User.Base.Id
		}
	}
	out.EventType = x.EventType
	return out, nil
}
