// Code generated by protoc-gen-go-plain. DO NOT EDIT.

package virtual

type UserPlain struct {

	// src: .test.virtual.User.name; transform: none
	Name string
	// src: <virtual>; transform: virtual
	VirtAddr *Address
	// src: <virtual>; transform: virtual
	VirtStatus Status
}

func (m *User) IntoPlain() *UserPlain {
	if m == nil {
		return nil
	}
	return &UserPlain{
		Name: m.GetName(),
	}
}

func (m *User) IntoPlainErr() (*UserPlain, error) {
	if m == nil {
		return nil, nil
	}
	return &UserPlain{
		Name: m.GetName(),
	}, nil
}

func (m *UserPlain) IntoPb() *User {
	if m == nil {
		return nil
	}
	return &User{
		Name: m.Name,
	}
}

func (m *UserPlain) IntoPbErr() (*User, error) {
	if m == nil {
		return nil, nil
	}
	return &User{
		Name: m.Name,
	}, nil
}
