// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: tests/integrations/virtual/test.proto

package virtual

import (
	_ "github.com/yaroher/protoc-gen-go-plain/goplain"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_ACTIVE      Status = 1
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_ACTIVE",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_ACTIVE":      1,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_tests_integrations_virtual_test_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_tests_integrations_virtual_test_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_tests_integrations_virtual_test_proto_rawDescGZIP(), []int{0}
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street        string                 `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_tests_integrations_virtual_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_tests_integrations_virtual_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_tests_integrations_virtual_test_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_tests_integrations_virtual_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_tests_integrations_virtual_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_tests_integrations_virtual_test_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_tests_integrations_virtual_test_proto protoreflect.FileDescriptor

const file_tests_integrations_virtual_test_proto_rawDesc = "" +
	"\n" +
	"%tests/integrations/virtual/test.proto\x12\ftest.virtual\x1a\x15goplain/goplain.proto\"!\n" +
	"\aAddress\x12\x16\n" +
	"\x06street\x18\x01 \x01(\tR\x06street\"o\n" +
	"\x04User\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name:S\x82\xa6\x1dO\b\x01\x1a$\b\v\"\tvirt_addr2\x15.test.virtual.Address\x1a%\b\x0e\"\vvirt_status2\x14.test.virtual.Status*3\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATUS_ACTIVE\x10\x01BKZIgithub.com/yaroher/protoc-gen-go-plain/tests/integrations/virtual;virtualb\x06proto3"

var (
	file_tests_integrations_virtual_test_proto_rawDescOnce sync.Once
	file_tests_integrations_virtual_test_proto_rawDescData []byte
)

func file_tests_integrations_virtual_test_proto_rawDescGZIP() []byte {
	file_tests_integrations_virtual_test_proto_rawDescOnce.Do(func() {
		file_tests_integrations_virtual_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tests_integrations_virtual_test_proto_rawDesc), len(file_tests_integrations_virtual_test_proto_rawDesc)))
	})
	return file_tests_integrations_virtual_test_proto_rawDescData
}

var file_tests_integrations_virtual_test_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tests_integrations_virtual_test_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tests_integrations_virtual_test_proto_goTypes = []any{
	(Status)(0),     // 0: test.virtual.Status
	(*Address)(nil), // 1: test.virtual.Address
	(*User)(nil),    // 2: test.virtual.User
}
var file_tests_integrations_virtual_test_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tests_integrations_virtual_test_proto_init() }
func file_tests_integrations_virtual_test_proto_init() {
	if File_tests_integrations_virtual_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tests_integrations_virtual_test_proto_rawDesc), len(file_tests_integrations_virtual_test_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tests_integrations_virtual_test_proto_goTypes,
		DependencyIndexes: file_tests_integrations_virtual_test_proto_depIdxs,
		EnumInfos:         file_tests_integrations_virtual_test_proto_enumTypes,
		MessageInfos:      file_tests_integrations_virtual_test_proto_msgTypes,
	}.Build()
	File_tests_integrations_virtual_test_proto = out.File
	file_tests_integrations_virtual_test_proto_goTypes = nil
	file_tests_integrations_virtual_test_proto_depIdxs = nil
}
