// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: tests/integrations/embed/test.proto

package embed

import (
	_ "github.com/yaroher/protoc-gen-go-plain/goplain"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContactType int32

const (
	ContactType_CONTACT_TYPE_UNSPECIFIED ContactType = 0
	ContactType_CONTACT_TYPE_EMAIL       ContactType = 1
	ContactType_CONTACT_TYPE_PHONE       ContactType = 2
)

// Enum value maps for ContactType.
var (
	ContactType_name = map[int32]string{
		0: "CONTACT_TYPE_UNSPECIFIED",
		1: "CONTACT_TYPE_EMAIL",
		2: "CONTACT_TYPE_PHONE",
	}
	ContactType_value = map[string]int32{
		"CONTACT_TYPE_UNSPECIFIED": 0,
		"CONTACT_TYPE_EMAIL":       1,
		"CONTACT_TYPE_PHONE":       2,
	}
)

func (x ContactType) Enum() *ContactType {
	p := new(ContactType)
	*p = x
	return p
}

func (x ContactType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContactType) Descriptor() protoreflect.EnumDescriptor {
	return file_tests_integrations_embed_test_proto_enumTypes[0].Descriptor()
}

func (ContactType) Type() protoreflect.EnumType {
	return &file_tests_integrations_embed_test_proto_enumTypes[0]
}

func (x ContactType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContactType.Descriptor instead.
func (ContactType) EnumDescriptor() ([]byte, []int) {
	return file_tests_integrations_embed_test_proto_rawDescGZIP(), []int{0}
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street        string                 `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_tests_integrations_embed_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_tests_integrations_embed_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_tests_integrations_embed_test_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type User struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Name        string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address     *Address               `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	WorkAddress *Address               `protobuf:"bytes,3,opt,name=work_address,json=workAddress,proto3" json:"work_address,omitempty"`
	// Types that are valid to be assigned to Contact:
	//
	//	*User_Email
	//	*User_Phone
	Contact isUser_Contact `protobuf_oneof:"contact"`
	// Types that are valid to be assigned to BackupContact:
	//
	//	*User_BackupEmail
	//	*User_BackupPhone
	BackupContact isUser_BackupContact `protobuf_oneof:"backup_contact"`
	ContactType   ContactType          `protobuf:"varint,8,opt,name=contact_type,json=contactType,proto3,enum=test.embed.ContactType" json:"contact_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_tests_integrations_embed_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_tests_integrations_embed_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_tests_integrations_embed_test_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *User) GetWorkAddress() *Address {
	if x != nil {
		return x.WorkAddress
	}
	return nil
}

func (x *User) GetContact() isUser_Contact {
	if x != nil {
		return x.Contact
	}
	return nil
}

func (x *User) GetEmail() string {
	if x != nil {
		if x, ok := x.Contact.(*User_Email); ok {
			return x.Email
		}
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		if x, ok := x.Contact.(*User_Phone); ok {
			return x.Phone
		}
	}
	return ""
}

func (x *User) GetBackupContact() isUser_BackupContact {
	if x != nil {
		return x.BackupContact
	}
	return nil
}

func (x *User) GetBackupEmail() string {
	if x != nil {
		if x, ok := x.BackupContact.(*User_BackupEmail); ok {
			return x.BackupEmail
		}
	}
	return ""
}

func (x *User) GetBackupPhone() string {
	if x != nil {
		if x, ok := x.BackupContact.(*User_BackupPhone); ok {
			return x.BackupPhone
		}
	}
	return ""
}

func (x *User) GetContactType() ContactType {
	if x != nil {
		return x.ContactType
	}
	return ContactType_CONTACT_TYPE_UNSPECIFIED
}

type isUser_Contact interface {
	isUser_Contact()
}

type User_Email struct {
	Email string `protobuf:"bytes,4,opt,name=email,proto3,oneof"`
}

type User_Phone struct {
	Phone string `protobuf:"bytes,5,opt,name=phone,proto3,oneof"`
}

func (*User_Email) isUser_Contact() {}

func (*User_Phone) isUser_Contact() {}

type isUser_BackupContact interface {
	isUser_BackupContact()
}

type User_BackupEmail struct {
	BackupEmail string `protobuf:"bytes,6,opt,name=backup_email,json=backupEmail,proto3,oneof"`
}

type User_BackupPhone struct {
	BackupPhone string `protobuf:"bytes,7,opt,name=backup_phone,json=backupPhone,proto3,oneof"`
}

func (*User_BackupEmail) isUser_BackupContact() {}

func (*User_BackupPhone) isUser_BackupContact() {}

var File_tests_integrations_embed_test_proto protoreflect.FileDescriptor

const file_tests_integrations_embed_test_proto_rawDesc = "" +
	"\n" +
	"#tests/integrations/embed/test.proto\x12\n" +
	"test.embed\x1a\x15goplain/goplain.proto\"5\n" +
	"\aAddress\x12\x16\n" +
	"\x06street\x18\x01 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\"\xfc\x02\n" +
	"\x04User\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x125\n" +
	"\aaddress\x18\x02 \x01(\v2\x13.test.embed.AddressB\x06\x82\xa6\x1d\x02 \x01R\aaddress\x12>\n" +
	"\fwork_address\x18\x03 \x01(\v2\x13.test.embed.AddressB\x06\x82\xa6\x1d\x02(\x01R\vworkAddress\x12\x16\n" +
	"\x05email\x18\x04 \x01(\tH\x00R\x05email\x12\x16\n" +
	"\x05phone\x18\x05 \x01(\tH\x00R\x05phone\x12#\n" +
	"\fbackup_email\x18\x06 \x01(\tH\x01R\vbackupEmail\x12#\n" +
	"\fbackup_phone\x18\a \x01(\tH\x01R\vbackupPhone\x12:\n" +
	"\fcontact_type\x18\b \x01(\x0e2\x17.test.embed.ContactTypeR\vcontactType:\x06\x82\xa6\x1d\x02\b\x01B\x11\n" +
	"\acontact\x12\x06\x82\xb5\x18\x02\b\x01B\x18\n" +
	"\x0ebackup_contact\x12\x06\x82\xb5\x18\x02\x10\x01*[\n" +
	"\vContactType\x12\x1c\n" +
	"\x18CONTACT_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12CONTACT_TYPE_EMAIL\x10\x01\x12\x16\n" +
	"\x12CONTACT_TYPE_PHONE\x10\x02BGZEgithub.com/yaroher/protoc-gen-go-plain/tests/integrations/embed;embedb\x06proto3"

var (
	file_tests_integrations_embed_test_proto_rawDescOnce sync.Once
	file_tests_integrations_embed_test_proto_rawDescData []byte
)

func file_tests_integrations_embed_test_proto_rawDescGZIP() []byte {
	file_tests_integrations_embed_test_proto_rawDescOnce.Do(func() {
		file_tests_integrations_embed_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tests_integrations_embed_test_proto_rawDesc), len(file_tests_integrations_embed_test_proto_rawDesc)))
	})
	return file_tests_integrations_embed_test_proto_rawDescData
}

var file_tests_integrations_embed_test_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tests_integrations_embed_test_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tests_integrations_embed_test_proto_goTypes = []any{
	(ContactType)(0), // 0: test.embed.ContactType
	(*Address)(nil),  // 1: test.embed.Address
	(*User)(nil),     // 2: test.embed.User
}
var file_tests_integrations_embed_test_proto_depIdxs = []int32{
	1, // 0: test.embed.User.address:type_name -> test.embed.Address
	1, // 1: test.embed.User.work_address:type_name -> test.embed.Address
	0, // 2: test.embed.User.contact_type:type_name -> test.embed.ContactType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_tests_integrations_embed_test_proto_init() }
func file_tests_integrations_embed_test_proto_init() {
	if File_tests_integrations_embed_test_proto != nil {
		return
	}
	file_tests_integrations_embed_test_proto_msgTypes[1].OneofWrappers = []any{
		(*User_Email)(nil),
		(*User_Phone)(nil),
		(*User_BackupEmail)(nil),
		(*User_BackupPhone)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tests_integrations_embed_test_proto_rawDesc), len(file_tests_integrations_embed_test_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tests_integrations_embed_test_proto_goTypes,
		DependencyIndexes: file_tests_integrations_embed_test_proto_depIdxs,
		EnumInfos:         file_tests_integrations_embed_test_proto_enumTypes,
		MessageInfos:      file_tests_integrations_embed_test_proto_msgTypes,
	}.Build()
	File_tests_integrations_embed_test_proto = out.File
	file_tests_integrations_embed_test_proto_goTypes = nil
	file_tests_integrations_embed_test_proto_depIdxs = nil
}
