// Code generated by protoc-gen-go-plain. DO NOT EDIT.

package type_alias

import (
	json "encoding/json"
	jx "github.com/go-faster/jx"
	protojson "google.golang.org/protobuf/encoding/protojson"
)

type UserPlain struct {

	// src: .test.type_alias.User.id; transform: type_alias
	Id string
}

func (m *User) IntoPlain() *UserPlain {
	if m == nil {
		return nil
	}
	return &UserPlain{
		Id: func() string {
			if m.GetId() == nil {
				return ""
			}
			return m.GetId().Value
		}(),
	}
}

func (m *User) IntoPlainErr() (*UserPlain, error) {
	if m == nil {
		return nil, nil
	}
	return &UserPlain{
		Id: func() string {
			if m.GetId() == nil {
				return ""
			}
			return m.GetId().Value
		}(),
	}, nil
}

func (m *UserPlain) IntoPb() *User {
	if m == nil {
		return nil
	}
	return &User{
		Id: &UserId{Value: m.Id},
	}
}

func (m *UserPlain) IntoPbErr() (*User, error) {
	if m == nil {
		return nil, nil
	}
	return &User{
		Id: &UserId{Value: m.Id},
	}, nil
}

func (m *UserPlain) MarshalJSON() ([]byte, error) {
	if m == nil {
		return []byte("null"), nil
	}
	_ = protojson.Marshal
	_ = json.Marshal
	var e jx.Encoder
	e.ObjStart()
	e.FieldStart("id")
	e.Str(m.Id)
	e.ObjEnd()
	return e.Bytes(), nil
}

func (m *UserPlain) UnmarshalJSON(data []byte) error {
	if m == nil {
		return nil
	}
	_ = protojson.Unmarshal
	_ = json.Unmarshal
	d := jx.DecodeBytes(data)
	return d.Obj(func(d *jx.Decoder, key string) error {
		switch key {
		case "id":
			v, err := d.Str()
			if err != nil {
				return err
			}
			m.Id = v
			return nil
		default:
			return d.Skip()
		}
	})
}
