// Code generated by protoc-gen-go-plain. DO NOT EDIT.

package full

import (
	"github.com/google/uuid"
	"google.golang.org/protobuf/types/known/timestamppb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

type BasePlain struct {
	Id     string `json:"id"`
	Source string `json:"source"`
}

type ComplexPlain struct {
	Raw          []byte                  `json:"raw"`
	RawList      [][]byte                `json:"rawList,omitempty"`
	Comment      *wrapperspb.StringValue `json:"comment,omitempty"`
	ContactEmail *string                 `json:"contactEmail,omitempty"`
	AliasList    []string                `json:"aliasList,omitempty"`
	Id           *string                 `json:"id,omitempty"`
	IdCRF        string                  `json:"idCRF"`
	Tag          string                  `json:"tag"`
	CreatedAt    *timestamppb.Timestamp  `json:"createdAt,omitempty"`
	Source       string                  `json:"source"`
	Note         *string                 `json:"note,omitempty"`
	Meta         map[string]string       `json:"meta,omitempty"`
	ContactPhone *string                 `json:"contactPhone,omitempty"`
	StatusList   []int32                 `json:"statusList,omitempty"`
	CustomId     uuid.UUID               `json:"customId"`
	AliasId      string                  `json:"aliasId"`
	Name         string                  `json:"name"`
	Archived     *bool                   `json:"archived,omitempty"`
	Counters     map[string]int32        `json:"counters,omitempty"`
	Status       int32                   `json:"status"`
	VirtualNote  string                  `json:"virtualNote"`
	Labels       []string                `json:"labels,omitempty"`
}

type ExtraPlain struct {
	Id  string `json:"id"`
	Tag string `json:"tag"`
}
