// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: test/full/full.proto

package full

import (
	_ "github.com/yaroher/protoc-gen-go-plain/goplain"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_ACTIVE      Status = 1
	Status_STATUS_DISABLED    Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_ACTIVE",
		2: "STATUS_DISABLED",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_ACTIVE":      1,
		"STATUS_DISABLED":    2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_test_full_full_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_test_full_full_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_test_full_full_proto_rawDescGZIP(), []int{0}
}

type Base struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Base) Reset() {
	*x = Base{}
	mi := &file_test_full_full_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Base) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Base) ProtoMessage() {}

func (x *Base) ProtoReflect() protoreflect.Message {
	mi := &file_test_full_full_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Base.ProtoReflect.Descriptor instead.
func (*Base) Descriptor() ([]byte, []int) {
	return file_test_full_full_proto_rawDescGZIP(), []int{0}
}

func (x *Base) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Base) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type Extra struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tag           string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Extra) Reset() {
	*x = Extra{}
	mi := &file_test_full_full_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Extra) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Extra) ProtoMessage() {}

func (x *Extra) ProtoReflect() protoreflect.Message {
	mi := &file_test_full_full_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Extra.ProtoReflect.Descriptor instead.
func (*Extra) Descriptor() ([]byte, []int) {
	return file_test_full_full_proto_rawDescGZIP(), []int{1}
}

func (x *Extra) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Extra) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type Complex struct {
	state     protoimpl.MessageState  `protogen:"open.v1"`
	Base      *Base                   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Extra     *Extra                  `protobuf:"bytes,2,opt,name=extra,proto3" json:"extra,omitempty"`
	Name      string                  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Labels    []string                `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty"`
	Note      *string                 `protobuf:"bytes,5,opt,name=note,proto3,oneof" json:"note,omitempty"`
	Archived  *bool                   `protobuf:"varint,6,opt,name=archived,proto3,oneof" json:"archived,omitempty"`
	Raw       []byte                  `protobuf:"bytes,7,opt,name=raw,proto3" json:"raw,omitempty"`
	RawList   [][]byte                `protobuf:"bytes,8,rep,name=raw_list,json=rawList,proto3" json:"raw_list,omitempty"`
	Counters  map[string]int32        `protobuf:"bytes,9,rep,name=counters,proto3" json:"counters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Meta      map[string]string       `protobuf:"bytes,10,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt *timestamppb.Timestamp  `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Comment   *wrapperspb.StringValue `protobuf:"bytes,12,opt,name=comment,proto3" json:"comment,omitempty"`
	// Types that are valid to be assigned to Contact:
	//
	//	*Complex_Email
	//	*Complex_Phone
	Contact       isComplex_Contact `protobuf_oneof:"contact"`
	Status        Status            `protobuf:"varint,15,opt,name=status,proto3,enum=testfull.Status" json:"status,omitempty"`
	StatusList    []Status          `protobuf:"varint,16,rep,packed,name=status_list,json=statusList,proto3,enum=testfull.Status" json:"status_list,omitempty"`
	CustomId      string            `protobuf:"bytes,17,opt,name=custom_id,json=customId,proto3" json:"custom_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Complex) Reset() {
	*x = Complex{}
	mi := &file_test_full_full_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Complex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Complex) ProtoMessage() {}

func (x *Complex) ProtoReflect() protoreflect.Message {
	mi := &file_test_full_full_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Complex.ProtoReflect.Descriptor instead.
func (*Complex) Descriptor() ([]byte, []int) {
	return file_test_full_full_proto_rawDescGZIP(), []int{2}
}

func (x *Complex) GetBase() *Base {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *Complex) GetExtra() *Extra {
	if x != nil {
		return x.Extra
	}
	return nil
}

func (x *Complex) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Complex) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Complex) GetNote() string {
	if x != nil && x.Note != nil {
		return *x.Note
	}
	return ""
}

func (x *Complex) GetArchived() bool {
	if x != nil && x.Archived != nil {
		return *x.Archived
	}
	return false
}

func (x *Complex) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

func (x *Complex) GetRawList() [][]byte {
	if x != nil {
		return x.RawList
	}
	return nil
}

func (x *Complex) GetCounters() map[string]int32 {
	if x != nil {
		return x.Counters
	}
	return nil
}

func (x *Complex) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Complex) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Complex) GetComment() *wrapperspb.StringValue {
	if x != nil {
		return x.Comment
	}
	return nil
}

func (x *Complex) GetContact() isComplex_Contact {
	if x != nil {
		return x.Contact
	}
	return nil
}

func (x *Complex) GetEmail() string {
	if x != nil {
		if x, ok := x.Contact.(*Complex_Email); ok {
			return x.Email
		}
	}
	return ""
}

func (x *Complex) GetPhone() string {
	if x != nil {
		if x, ok := x.Contact.(*Complex_Phone); ok {
			return x.Phone
		}
	}
	return ""
}

func (x *Complex) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *Complex) GetStatusList() []Status {
	if x != nil {
		return x.StatusList
	}
	return nil
}

func (x *Complex) GetCustomId() string {
	if x != nil {
		return x.CustomId
	}
	return ""
}

type isComplex_Contact interface {
	isComplex_Contact()
}

type Complex_Email struct {
	Email string `protobuf:"bytes,13,opt,name=email,proto3,oneof"`
}

type Complex_Phone struct {
	Phone string `protobuf:"bytes,14,opt,name=phone,proto3,oneof"`
}

func (*Complex_Email) isComplex_Contact() {}

func (*Complex_Phone) isComplex_Contact() {}

var File_test_full_full_proto protoreflect.FileDescriptor

const file_test_full_full_proto_rawDesc = "" +
	"\n" +
	"\x14test/full/full.proto\x12\btestfull\x1a\x15goplain/goplain.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"6\n" +
	"\x04Base\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source:\x06\x82\xa6\x1d\x02\b\x01\"1\n" +
	"\x05Extra\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag:\x06\x82\xa6\x1d\x02\b\x01\"\xe1\x06\n" +
	"\aComplex\x12*\n" +
	"\x04base\x18\x01 \x01(\v2\x0e.testfull.BaseB\x06\x82\xa6\x1d\x02 \x01R\x04base\x12-\n" +
	"\x05extra\x18\x02 \x01(\v2\x0f.testfull.ExtraB\x06\x82\xa6\x1d\x02 \x01R\x05extra\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06labels\x18\x04 \x03(\tR\x06labels\x12\x17\n" +
	"\x04note\x18\x05 \x01(\tH\x01R\x04note\x88\x01\x01\x12\x1f\n" +
	"\barchived\x18\x06 \x01(\bH\x02R\barchived\x88\x01\x01\x12\x10\n" +
	"\x03raw\x18\a \x01(\fR\x03raw\x12\x19\n" +
	"\braw_list\x18\b \x03(\fR\arawList\x12;\n" +
	"\bcounters\x18\t \x03(\v2\x1f.testfull.Complex.CountersEntryR\bcounters\x12/\n" +
	"\x04meta\x18\n" +
	" \x03(\v2\x1b.testfull.Complex.MetaEntryR\x04meta\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x126\n" +
	"\acomment\x18\f \x01(\v2\x1c.google.protobuf.StringValueR\acomment\x12\x16\n" +
	"\x05email\x18\r \x01(\tH\x00R\x05email\x12\x16\n" +
	"\x05phone\x18\x0e \x01(\tH\x00R\x05phone\x12(\n" +
	"\x06status\x18\x0f \x01(\x0e2\x10.testfull.StatusR\x06status\x121\n" +
	"\vstatus_list\x18\x10 \x03(\x0e2\x10.testfull.StatusR\n" +
	"statusList\x12A\n" +
	"\tcustom_id\x18\x11 \x01(\tB$\x82\xa6\x1d \n" +
	"\x1e\n" +
	"\x04UUID\x12\x16github.com/google/uuidR\bcustomId\x1a;\n" +
	"\rCountersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01:\x18\x82\xa6\x1d\x14\b\x01\"\x10\b\t\"\fvirtual_noteB\x11\n" +
	"\acontact\x12\x06\x82\xb5\x18\x02\x10\x01B\a\n" +
	"\x05_noteB\v\n" +
	"\t_archived*H\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATUS_ACTIVE\x10\x01\x12\x13\n" +
	"\x0fSTATUS_DISABLED\x10\x02B2Z0github.com/yaroher/protoc-gen-go-plain/test/fullb\x06proto3"

var (
	file_test_full_full_proto_rawDescOnce sync.Once
	file_test_full_full_proto_rawDescData []byte
)

func file_test_full_full_proto_rawDescGZIP() []byte {
	file_test_full_full_proto_rawDescOnce.Do(func() {
		file_test_full_full_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_full_full_proto_rawDesc), len(file_test_full_full_proto_rawDesc)))
	})
	return file_test_full_full_proto_rawDescData
}

var file_test_full_full_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_test_full_full_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_test_full_full_proto_goTypes = []any{
	(Status)(0),                    // 0: testfull.Status
	(*Base)(nil),                   // 1: testfull.Base
	(*Extra)(nil),                  // 2: testfull.Extra
	(*Complex)(nil),                // 3: testfull.Complex
	nil,                            // 4: testfull.Complex.CountersEntry
	nil,                            // 5: testfull.Complex.MetaEntry
	(*timestamppb.Timestamp)(nil),  // 6: google.protobuf.Timestamp
	(*wrapperspb.StringValue)(nil), // 7: google.protobuf.StringValue
}
var file_test_full_full_proto_depIdxs = []int32{
	1, // 0: testfull.Complex.base:type_name -> testfull.Base
	2, // 1: testfull.Complex.extra:type_name -> testfull.Extra
	4, // 2: testfull.Complex.counters:type_name -> testfull.Complex.CountersEntry
	5, // 3: testfull.Complex.meta:type_name -> testfull.Complex.MetaEntry
	6, // 4: testfull.Complex.created_at:type_name -> google.protobuf.Timestamp
	7, // 5: testfull.Complex.comment:type_name -> google.protobuf.StringValue
	0, // 6: testfull.Complex.status:type_name -> testfull.Status
	0, // 7: testfull.Complex.status_list:type_name -> testfull.Status
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_test_full_full_proto_init() }
func file_test_full_full_proto_init() {
	if File_test_full_full_proto != nil {
		return
	}
	file_test_full_full_proto_msgTypes[2].OneofWrappers = []any{
		(*Complex_Email)(nil),
		(*Complex_Phone)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_full_full_proto_rawDesc), len(file_test_full_full_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_full_full_proto_goTypes,
		DependencyIndexes: file_test_full_full_proto_depIdxs,
		EnumInfos:         file_test_full_full_proto_enumTypes,
		MessageInfos:      file_test_full_full_proto_msgTypes,
	}.Build()
	File_test_full_full_proto = out.File
	file_test_full_full_proto_goTypes = nil
	file_test_full_full_proto_depIdxs = nil
}
